// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=test/client_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	raw "github.com/tidepool-org/platform/data/raw"
	page "github.com/tidepool-org/platform/page"
	structured "github.com/tidepool-org/platform/store/structured"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStore) Create(ctx context.Context, userID, dataSetID string, create *raw.Create, data io.Reader) (*raw.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, dataSetID, create, data)
	ret0, _ := ret[0].(*raw.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(ctx, userID, dataSetID, create, data any) *MockStoreCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), ctx, userID, dataSetID, create, data)
	return &MockStoreCreateCall{Call: call}
}

// MockStoreCreateCall wrap *gomock.Call
type MockStoreCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCreateCall) Return(arg0 *raw.Raw, arg1 error) *MockStoreCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCreateCall) Do(f func(context.Context, string, string, *raw.Create, io.Reader) (*raw.Raw, error)) *MockStoreCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCreateCall) DoAndReturn(f func(context.Context, string, string, *raw.Create, io.Reader) (*raw.Raw, error)) *MockStoreCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockStore) Delete(ctx context.Context, id string, condition *structured.Condition) (*raw.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, condition)
	ret0, _ := ret[0].(*raw.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(ctx, id, condition any) *MockStoreDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), ctx, id, condition)
	return &MockStoreDeleteCall{Call: call}
}

// MockStoreDeleteCall wrap *gomock.Call
type MockStoreDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteCall) Return(arg0 *raw.Raw, arg1 error) *MockStoreDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteCall) Do(f func(context.Context, string, *structured.Condition) (*raw.Raw, error)) *MockStoreDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteCall) DoAndReturn(f func(context.Context, string, *structured.Condition) (*raw.Raw, error)) *MockStoreDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAllByDataSetID mocks base method.
func (m *MockStore) DeleteAllByDataSetID(ctx context.Context, userID, dataSetID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByDataSetID", ctx, userID, dataSetID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllByDataSetID indicates an expected call of DeleteAllByDataSetID.
func (mr *MockStoreMockRecorder) DeleteAllByDataSetID(ctx, userID, dataSetID any) *MockStoreDeleteAllByDataSetIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByDataSetID", reflect.TypeOf((*MockStore)(nil).DeleteAllByDataSetID), ctx, userID, dataSetID)
	return &MockStoreDeleteAllByDataSetIDCall{Call: call}
}

// MockStoreDeleteAllByDataSetIDCall wrap *gomock.Call
type MockStoreDeleteAllByDataSetIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteAllByDataSetIDCall) Return(arg0 int, arg1 error) *MockStoreDeleteAllByDataSetIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteAllByDataSetIDCall) Do(f func(context.Context, string, string) (int, error)) *MockStoreDeleteAllByDataSetIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteAllByDataSetIDCall) DoAndReturn(f func(context.Context, string, string) (int, error)) *MockStoreDeleteAllByDataSetIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAllByUserID mocks base method.
func (m *MockStore) DeleteAllByUserID(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllByUserID indicates an expected call of DeleteAllByUserID.
func (mr *MockStoreMockRecorder) DeleteAllByUserID(ctx, userID any) *MockStoreDeleteAllByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByUserID", reflect.TypeOf((*MockStore)(nil).DeleteAllByUserID), ctx, userID)
	return &MockStoreDeleteAllByUserIDCall{Call: call}
}

// MockStoreDeleteAllByUserIDCall wrap *gomock.Call
type MockStoreDeleteAllByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteAllByUserIDCall) Return(arg0 int, arg1 error) *MockStoreDeleteAllByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteAllByUserIDCall) Do(f func(context.Context, string) (int, error)) *MockStoreDeleteAllByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteAllByUserIDCall) DoAndReturn(f func(context.Context, string) (int, error)) *MockStoreDeleteAllByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteMultiple mocks base method.
func (m *MockStore) DeleteMultiple(ctx context.Context, ids []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultiple", ctx, ids)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMultiple indicates an expected call of DeleteMultiple.
func (mr *MockStoreMockRecorder) DeleteMultiple(ctx, ids any) *MockStoreDeleteMultipleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultiple", reflect.TypeOf((*MockStore)(nil).DeleteMultiple), ctx, ids)
	return &MockStoreDeleteMultipleCall{Call: call}
}

// MockStoreDeleteMultipleCall wrap *gomock.Call
type MockStoreDeleteMultipleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteMultipleCall) Return(arg0 int, arg1 error) *MockStoreDeleteMultipleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteMultipleCall) Do(f func(context.Context, []string) (int, error)) *MockStoreDeleteMultipleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteMultipleCall) DoAndReturn(f func(context.Context, []string) (int, error)) *MockStoreDeleteMultipleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, id string, condition *structured.Condition) (*raw.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, condition)
	ret0, _ := ret[0].(*raw.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, id, condition any) *MockStoreGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, id, condition)
	return &MockStoreGetCall{Call: call}
}

// MockStoreGetCall wrap *gomock.Call
type MockStoreGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetCall) Return(arg0 *raw.Raw, arg1 error) *MockStoreGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetCall) Do(f func(context.Context, string, *structured.Condition) (*raw.Raw, error)) *MockStoreGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetCall) DoAndReturn(f func(context.Context, string, *structured.Condition) (*raw.Raw, error)) *MockStoreGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetContent mocks base method.
func (m *MockStore) GetContent(ctx context.Context, id string, condition *structured.Condition) (*raw.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", ctx, id, condition)
	ret0, _ := ret[0].(*raw.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockStoreMockRecorder) GetContent(ctx, id, condition any) *MockStoreGetContentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockStore)(nil).GetContent), ctx, id, condition)
	return &MockStoreGetContentCall{Call: call}
}

// MockStoreGetContentCall wrap *gomock.Call
type MockStoreGetContentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetContentCall) Return(arg0 *raw.Content, arg1 error) *MockStoreGetContentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetContentCall) Do(f func(context.Context, string, *structured.Condition) (*raw.Content, error)) *MockStoreGetContentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetContentCall) DoAndReturn(f func(context.Context, string, *structured.Condition) (*raw.Content, error)) *MockStoreGetContentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockStore) List(ctx context.Context, userID string, filter *raw.Filter, pagination *page.Pagination) ([]*raw.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter, pagination)
	ret0, _ := ret[0].([]*raw.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(ctx, userID, filter, pagination any) *MockStoreListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), ctx, userID, filter, pagination)
	return &MockStoreListCall{Call: call}
}

// MockStoreListCall wrap *gomock.Call
type MockStoreListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreListCall) Return(arg0 []*raw.Raw, arg1 error) *MockStoreListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreListCall) Do(f func(context.Context, string, *raw.Filter, *page.Pagination) ([]*raw.Raw, error)) *MockStoreListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreListCall) DoAndReturn(f func(context.Context, string, *raw.Filter, *page.Pagination) ([]*raw.Raw, error)) *MockStoreListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockStore) Update(ctx context.Context, id string, condition *structured.Condition, update *raw.Update) (*raw.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, condition, update)
	ret0, _ := ret[0].(*raw.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStoreMockRecorder) Update(ctx, id, condition, update any) *MockStoreUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStore)(nil).Update), ctx, id, condition, update)
	return &MockStoreUpdateCall{Call: call}
}

// MockStoreUpdateCall wrap *gomock.Call
type MockStoreUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUpdateCall) Return(arg0 *raw.Raw, arg1 error) *MockStoreUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUpdateCall) Do(f func(context.Context, string, *structured.Condition, *raw.Update) (*raw.Raw, error)) *MockStoreUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUpdateCall) DoAndReturn(f func(context.Context, string, *structured.Condition, *raw.Update) (*raw.Raw, error)) *MockStoreUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
