// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=./test/client.go -package=test Client
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	shopify "github.com/tidepool-org/platform/oura/shopify"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateDiscountCode mocks base method.
func (m *MockClient) CreateDiscountCode(ctx context.Context, discountCodeInput shopify.DiscountCodeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscountCode", ctx, discountCodeInput)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDiscountCode indicates an expected call of CreateDiscountCode.
func (mr *MockClientMockRecorder) CreateDiscountCode(ctx, discountCodeInput any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscountCode", reflect.TypeOf((*MockClient)(nil).CreateDiscountCode), ctx, discountCodeInput)
}

// GetDeliveredProducts mocks base method.
func (m *MockClient) GetDeliveredProducts(ctx context.Context, orderID string) (*shopify.DeliveredProducts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveredProducts", ctx, orderID)
	ret0, _ := ret[0].(*shopify.DeliveredProducts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveredProducts indicates an expected call of GetDeliveredProducts.
func (mr *MockClientMockRecorder) GetDeliveredProducts(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveredProducts", reflect.TypeOf((*MockClient)(nil).GetDeliveredProducts), ctx, orderID)
}
