os: linux

dist: jammy

language: minimal

services:
  - docker

jobs:
  include:
    - name: Public plugins
      env: PLUGINS_VISIBILITY=public
    - name: Private plugins
      env: PLUGINS_VISIBILITY=private

cache:
  timeout: 600
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/gopath/pkg/sumdb

install: skip

script:
  - bash ci/run.sh
