# Development
FROM golang:1.15-alpine AS development
ENV GO111MODULE on
WORKDIR /go/src/github.com/tidepool-org/platform
RUN apk --no-cache add git make tzdata && \
    apk add --no-cache ca-certificates tzdata && \
    go get github.com/githubnemo/CompileDaemon && \
    adduser -D tidepool && \
    chown -R tidepool /go/src/github.com/tidepool-org/platform && \
    chown -R tidepool /go/pkg/mod 
USER tidepool
COPY . .
ENV SERVICE=services/data
RUN ["make", "service-build"]
CMD ["make", "service-start"]

# Production
FROM alpine:latest AS production
RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache ca-certificates tzdata && \
    adduser -D tidepool
WORKDIR /home/tidepool
USER tidepool
ENV ZONEINFO=/usr/local/go/lib/time/zoneinfo.zip
COPY --from=development --chown=tidepool /go/src/github.com/tidepool-org/platform/_bin/services/data/ .
COPY --from=development --chown=tidepool /usr/local/go/lib/time/zoneinfo.zip /usr/local/go/lib/time/
CMD ["./data"]
