# Development
FROM golang:1.23.4-alpine AS development
RUN apk --no-cache update && apk --no-cache upgrade && apk --no-cache add ca-certificates tzdata git make
RUN [ ! -d /go/pkg/mod ] || chmod -R go+w /go/pkg/mod
RUN adduser --disabled-password tidepool
USER tidepool
WORKDIR /go/src/github.com/tidepool-org/platform
COPY --chown=tidepool:tidepool . .
RUN ["make", "init", "CompileDaemon", "plugins-visibility"]
RUN ["make", "services-build-common"]
ENV SERVICE=services/data
CMD ["make", "service-start"]

# Production
FROM alpine:latest AS production
RUN apk --no-cache update && apk --no-cache upgrade && apk --no-cache add ca-certificates tzdata
RUN adduser --disabled-password tidepool
USER tidepool
WORKDIR /home/tidepool
COPY --from=development --chown=tidepool:tidepool /go/src/github.com/tidepool-org/platform/_bin/services/data/ .
CMD ["./data"]
