FROM golang:1.7.1-alpine

# Container specific ENV
ENV TIDEPOOL_ENV="local" \
    TIDEPOOL_CONFIG_DIRECTORY="$GOPATH/src/github.com/tidepool-org/platform/_config" \
    TIDEPOOL_USERSERVICES_CLIENT_SERVERTOKENSECRET="This needs to be the same secret everywhere. YaHut75NsK1f9UKUXuWqxNN0RUwHFBCy"


# $GOPATH=/go FROM the golang container
WORKDIR /go

COPY . ${GOPATH}/src/github.com/tidepool-org/platform
RUN apk --no-cache add git make \
 && cd ${GOPATH}/src/github.com/tidepool-org/platform \
 && sed -i -e 's/localhost/mongo/' _config/userservices/message_store.local.json \
 && sed -i -e 's/localhost/mongo/' _config/userservices/notification_store.local.json \
 && sed -i -e 's/localhost/mongo/' _config/userservices/permission_store.local.json \
 && sed -i -e 's/localhost/mongo/' _config/userservices/profile_store.local.json \
 && sed -i -e 's/localhost/mongo/' _config/userservices/session_store.local.json \
 && sed -i -e 's/localhost/mongo/' _config/userservices/user_store.local.json \
 && sed -i -e 's/localhost/styx/' _config/userservices/metricservices_client.local.json \
 && sed -i -e 's/localhost/styx/' _config/userservices/dataservices_client.local.json \
 && sed -i -e 's/localhost/styx/' _config/userservices/userservices_client.local.json \
 && rm -rf src _bin \
 && BUILD=userservices make build

# Prod builds should exclude or remove .git files

CMD ["/go/src/github.com/tidepool-org/platform/_bin/userservices/userservices"]
