// Code generated by MockGen. DO NOT EDIT.
// Source: history.go
//
// Generated by this command:
//
//	mockgen -source=history.go -destination=test/history_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	history "github.com/tidepool-org/platform/notifications/history"
	page "github.com/tidepool-org/platform/page"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecorder) Create(ctx context.Context, entry history.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRecorderMockRecorder) Create(ctx, entry any) *MockRecorderCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecorder)(nil).Create), ctx, entry)
	return &MockRecorderCreateCall{Call: call}
}

// MockRecorderCreateCall wrap *gomock.Call
type MockRecorderCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecorderCreateCall) Return(arg0 error) *MockRecorderCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecorderCreateCall) Do(f func(context.Context, history.Entry) error) *MockRecorderCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecorderCreateCall) DoAndReturn(f func(context.Context, history.Entry) error) *MockRecorderCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockRecorder) List(ctx context.Context, filter history.Filter, pagination *page.Pagination) ([]history.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, pagination)
	ret0, _ := ret[0].([]history.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRecorderMockRecorder) List(ctx, filter, pagination any) *MockRecorderListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRecorder)(nil).List), ctx, filter, pagination)
	return &MockRecorderListCall{Call: call}
}

// MockRecorderListCall wrap *gomock.Call
type MockRecorderListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecorderListCall) Return(arg0 []history.Entry, arg1 error) *MockRecorderListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecorderListCall) Do(f func(context.Context, history.Filter, *page.Pagination) ([]history.Entry, error)) *MockRecorderListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecorderListCall) DoAndReturn(f func(context.Context, history.Filter, *page.Pagination) ([]history.Entry, error)) *MockRecorderListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
