// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -source=task.go -destination=test/task_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	page "github.com/tidepool-org/platform/page"
	request "github.com/tidepool-org/platform/request"
	task "github.com/tidepool-org/platform/task"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockClient) CreateTask(ctx context.Context, create *task.TaskCreate) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, create)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockClientMockRecorder) CreateTask(ctx, create any) *MockClientCreateTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockClient)(nil).CreateTask), ctx, create)
	return &MockClientCreateTaskCall{Call: call}
}

// MockClientCreateTaskCall wrap *gomock.Call
type MockClientCreateTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateTaskCall) Return(arg0 *task.Task, arg1 error) *MockClientCreateTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateTaskCall) Do(f func(context.Context, *task.TaskCreate) (*task.Task, error)) *MockClientCreateTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateTaskCall) DoAndReturn(f func(context.Context, *task.TaskCreate) (*task.Task, error)) *MockClientCreateTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTask mocks base method.
func (m *MockClient) DeleteTask(ctx context.Context, id string, condition *request.Condition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockClientMockRecorder) DeleteTask(ctx, id, condition any) *MockClientDeleteTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockClient)(nil).DeleteTask), ctx, id, condition)
	return &MockClientDeleteTaskCall{Call: call}
}

// MockClientDeleteTaskCall wrap *gomock.Call
type MockClientDeleteTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteTaskCall) Return(arg0 error) *MockClientDeleteTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteTaskCall) Do(f func(context.Context, string, *request.Condition) error) *MockClientDeleteTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteTaskCall) DoAndReturn(f func(context.Context, string, *request.Condition) error) *MockClientDeleteTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTask mocks base method.
func (m *MockClient) GetTask(ctx context.Context, id string, condition *request.Condition) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id, condition)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockClientMockRecorder) GetTask(ctx, id, condition any) *MockClientGetTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockClient)(nil).GetTask), ctx, id, condition)
	return &MockClientGetTaskCall{Call: call}
}

// MockClientGetTaskCall wrap *gomock.Call
type MockClientGetTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetTaskCall) Return(arg0 *task.Task, arg1 error) *MockClientGetTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetTaskCall) Do(f func(context.Context, string, *request.Condition) (*task.Task, error)) *MockClientGetTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetTaskCall) DoAndReturn(f func(context.Context, string, *request.Condition) (*task.Task, error)) *MockClientGetTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTasks mocks base method.
func (m *MockClient) ListTasks(ctx context.Context, filter *task.TaskFilter, pagination *page.Pagination) (task.Tasks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, filter, pagination)
	ret0, _ := ret[0].(task.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockClientMockRecorder) ListTasks(ctx, filter, pagination any) *MockClientListTasksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockClient)(nil).ListTasks), ctx, filter, pagination)
	return &MockClientListTasksCall{Call: call}
}

// MockClientListTasksCall wrap *gomock.Call
type MockClientListTasksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientListTasksCall) Return(arg0 task.Tasks, arg1 error) *MockClientListTasksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientListTasksCall) Do(f func(context.Context, *task.TaskFilter, *page.Pagination) (task.Tasks, error)) *MockClientListTasksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientListTasksCall) DoAndReturn(f func(context.Context, *task.TaskFilter, *page.Pagination) (task.Tasks, error)) *MockClientListTasksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTask mocks base method.
func (m *MockClient) UpdateTask(ctx context.Context, id string, condition *request.Condition, update *task.TaskUpdate) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, id, condition, update)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockClientMockRecorder) UpdateTask(ctx, id, condition, update any) *MockClientUpdateTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockClient)(nil).UpdateTask), ctx, id, condition, update)
	return &MockClientUpdateTaskCall{Call: call}
}

// MockClientUpdateTaskCall wrap *gomock.Call
type MockClientUpdateTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateTaskCall) Return(arg0 *task.Task, arg1 error) *MockClientUpdateTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateTaskCall) Do(f func(context.Context, string, *request.Condition, *task.TaskUpdate) (*task.Task, error)) *MockClientUpdateTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateTaskCall) DoAndReturn(f func(context.Context, string, *request.Condition, *task.TaskUpdate) (*task.Task, error)) *MockClientUpdateTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
