// Code generated by MockGen. DO NOT EDIT.
// Source: summary.go
//
// Generated by this command:
//
//	mockgen -source=summary.go -destination=test/summary_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/tidepool-org/platform/summary/types"
	mongo "go.mongodb.org/mongo-driver/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockSummarizer is a mock of Summarizer interface.
type MockSummarizer[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	ctrl     *gomock.Controller
	recorder *MockSummarizerMockRecorder[PP, PB, P, B]
	isgomock struct{}
}

// MockSummarizerMockRecorder is the mock recorder for MockSummarizer.
type MockSummarizerMockRecorder[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	mock *MockSummarizer[PP, PB, P, B]
}

// NewMockSummarizer creates a new mock instance.
func NewMockSummarizer[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData](ctrl *gomock.Controller) *MockSummarizer[PP, PB, P, B] {
	mock := &MockSummarizer[PP, PB, P, B]{ctrl: ctrl}
	mock.recorder = &MockSummarizerMockRecorder[PP, PB, P, B]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummarizer[PP, PB, P, B]) EXPECT() *MockSummarizerMockRecorder[PP, PB, P, B] {
	return m.recorder
}

// GetBucketsRange mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) GetBucketsRange(ctx context.Context, userId string, startTime, endTime time.Time) (*mongo.Cursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketsRange", ctx, userId, startTime, endTime)
	ret0, _ := ret[0].(*mongo.Cursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketsRange indicates an expected call of GetBucketsRange.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) GetBucketsRange(ctx, userId, startTime, endTime any) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketsRange", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).GetBucketsRange), ctx, userId, startTime, endTime)
	return &MockSummarizerGetBucketsRangeCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerGetBucketsRangeCall wrap *gomock.Call
type MockSummarizerGetBucketsRangeCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerGetBucketsRangeCall[PP, PB, P, B]) Return(arg0 *mongo.Cursor, arg1 error) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerGetBucketsRangeCall[PP, PB, P, B]) Do(f func(context.Context, string, time.Time, time.Time) (*mongo.Cursor, error)) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerGetBucketsRangeCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string, time.Time, time.Time) (*mongo.Cursor, error)) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSummary mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) GetSummary(ctx context.Context, userId string) (*types.Summary[PP, PB, P, B], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, userId)
	ret0, _ := ret[0].(*types.Summary[PP, PB, P, B])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) GetSummary(ctx, userId any) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).GetSummary), ctx, userId)
	return &MockSummarizerGetSummaryCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerGetSummaryCall wrap *gomock.Call
type MockSummarizerGetSummaryCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerGetSummaryCall[PP, PB, P, B]) Return(arg0 *types.Summary[PP, PB, P, B], arg1 error) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerGetSummaryCall[PP, PB, P, B]) Do(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerGetSummaryCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSummary mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) UpdateSummary(ctx context.Context, userId string) (*types.Summary[PP, PB, P, B], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSummary", ctx, userId)
	ret0, _ := ret[0].(*types.Summary[PP, PB, P, B])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSummary indicates an expected call of UpdateSummary.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) UpdateSummary(ctx, userId any) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSummary", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).UpdateSummary), ctx, userId)
	return &MockSummarizerUpdateSummaryCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerUpdateSummaryCall wrap *gomock.Call
type MockSummarizerUpdateSummaryCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerUpdateSummaryCall[PP, PB, P, B]) Return(arg0 *types.Summary[PP, PB, P, B], arg1 error) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerUpdateSummaryCall[PP, PB, P, B]) Do(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerUpdateSummaryCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
