// Code generated by MockGen. DO NOT EDIT.
// Source: summary.go
//
// Generated by this command:
//
//	mockgen -source=summary.go -destination=test/summary_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"
	time "time"

	mongo "go.mongodb.org/mongo-driver/mongo"
	gomock "go.uber.org/mock/gomock"

	data "github.com/tidepool-org/platform/data"
	page "github.com/tidepool-org/platform/page"
	types "github.com/tidepool-org/platform/summary/types"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CheckDataUpdatesSummary mocks base method.
func (m *MockClient) CheckDataUpdatesSummary(datumArray data.Data, updatesSummary map[string]struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckDataUpdatesSummary", datumArray, updatesSummary)
}

// CheckDataUpdatesSummary indicates an expected call of CheckDataUpdatesSummary.
func (mr *MockClientMockRecorder) CheckDataUpdatesSummary(datumArray, updatesSummary any) *MockClientCheckDataUpdatesSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDataUpdatesSummary", reflect.TypeOf((*MockClient)(nil).CheckDataUpdatesSummary), datumArray, updatesSummary)
	return &MockClientCheckDataUpdatesSummaryCall{Call: call}
}

// MockClientCheckDataUpdatesSummaryCall wrap *gomock.Call
type MockClientCheckDataUpdatesSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCheckDataUpdatesSummaryCall) Return() *MockClientCheckDataUpdatesSummaryCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCheckDataUpdatesSummaryCall) Do(f func(data.Data, map[string]struct{})) *MockClientCheckDataUpdatesSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCheckDataUpdatesSummaryCall) DoAndReturn(f func(data.Data, map[string]struct{})) *MockClientCheckDataUpdatesSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MaybeUpdateSummary mocks base method.
func (m *MockClient) MaybeUpdateSummary(ctx context.Context, userID, reason string, updatesSummary map[string]struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MaybeUpdateSummary", ctx, userID, reason, updatesSummary)
}

// MaybeUpdateSummary indicates an expected call of MaybeUpdateSummary.
func (mr *MockClientMockRecorder) MaybeUpdateSummary(ctx, userID, reason, updatesSummary any) *MockClientMaybeUpdateSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaybeUpdateSummary", reflect.TypeOf((*MockClient)(nil).MaybeUpdateSummary), ctx, userID, reason, updatesSummary)
	return &MockClientMaybeUpdateSummaryCall{Call: call}
}

// MockClientMaybeUpdateSummaryCall wrap *gomock.Call
type MockClientMaybeUpdateSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientMaybeUpdateSummaryCall) Return() *MockClientMaybeUpdateSummaryCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientMaybeUpdateSummaryCall) Do(f func(context.Context, string, string, map[string]struct{})) *MockClientMaybeUpdateSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientMaybeUpdateSummaryCall) DoAndReturn(f func(context.Context, string, string, map[string]struct{})) *MockClientMaybeUpdateSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSummarizer is a mock of Summarizer interface.
type MockSummarizer[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	ctrl     *gomock.Controller
	recorder *MockSummarizerMockRecorder[PP, PB, P, B]
	isgomock struct{}
}

// MockSummarizerMockRecorder is the mock recorder for MockSummarizer.
type MockSummarizerMockRecorder[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	mock *MockSummarizer[PP, PB, P, B]
}

// NewMockSummarizer creates a new mock instance.
func NewMockSummarizer[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData](ctrl *gomock.Controller) *MockSummarizer[PP, PB, P, B] {
	mock := &MockSummarizer[PP, PB, P, B]{ctrl: ctrl}
	mock.recorder = &MockSummarizerMockRecorder[PP, PB, P, B]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummarizer[PP, PB, P, B]) EXPECT() *MockSummarizerMockRecorder[PP, PB, P, B] {
	return m.recorder
}

// GetBucketsRange mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) GetBucketsRange(ctx context.Context, userId string, startTime, endTime time.Time) (*mongo.Cursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketsRange", ctx, userId, startTime, endTime)
	ret0, _ := ret[0].(*mongo.Cursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketsRange indicates an expected call of GetBucketsRange.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) GetBucketsRange(ctx, userId, startTime, endTime any) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketsRange", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).GetBucketsRange), ctx, userId, startTime, endTime)
	return &MockSummarizerGetBucketsRangeCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerGetBucketsRangeCall wrap *gomock.Call
type MockSummarizerGetBucketsRangeCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerGetBucketsRangeCall[PP, PB, P, B]) Return(arg0 *mongo.Cursor, arg1 error) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerGetBucketsRangeCall[PP, PB, P, B]) Do(f func(context.Context, string, time.Time, time.Time) (*mongo.Cursor, error)) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerGetBucketsRangeCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string, time.Time, time.Time) (*mongo.Cursor, error)) *MockSummarizerGetBucketsRangeCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMigratableUserIDs mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) GetMigratableUserIDs(ctx context.Context, pagination *page.Pagination) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMigratableUserIDs", ctx, pagination)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMigratableUserIDs indicates an expected call of GetMigratableUserIDs.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) GetMigratableUserIDs(ctx, pagination any) *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMigratableUserIDs", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).GetMigratableUserIDs), ctx, pagination)
	return &MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerGetMigratableUserIDsCall wrap *gomock.Call
type MockSummarizerGetMigratableUserIDsCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B]) Return(arg0 []string, arg1 error) *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B]) Do(f func(context.Context, *page.Pagination) ([]string, error)) *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, *page.Pagination) ([]string, error)) *MockSummarizerGetMigratableUserIDsCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOutdatedUserIDs mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) GetOutdatedUserIDs(ctx context.Context, pagination *page.Pagination) (*types.OutdatedSummariesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutdatedUserIDs", ctx, pagination)
	ret0, _ := ret[0].(*types.OutdatedSummariesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutdatedUserIDs indicates an expected call of GetOutdatedUserIDs.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) GetOutdatedUserIDs(ctx, pagination any) *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutdatedUserIDs", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).GetOutdatedUserIDs), ctx, pagination)
	return &MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerGetOutdatedUserIDsCall wrap *gomock.Call
type MockSummarizerGetOutdatedUserIDsCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B]) Return(arg0 *types.OutdatedSummariesResponse, arg1 error) *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B]) Do(f func(context.Context, *page.Pagination) (*types.OutdatedSummariesResponse, error)) *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, *page.Pagination) (*types.OutdatedSummariesResponse, error)) *MockSummarizerGetOutdatedUserIDsCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSummary mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) GetSummary(ctx context.Context, userId string) (*types.Summary[PP, PB, P, B], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, userId)
	ret0, _ := ret[0].(*types.Summary[PP, PB, P, B])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) GetSummary(ctx, userId any) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).GetSummary), ctx, userId)
	return &MockSummarizerGetSummaryCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerGetSummaryCall wrap *gomock.Call
type MockSummarizerGetSummaryCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerGetSummaryCall[PP, PB, P, B]) Return(arg0 *types.Summary[PP, PB, P, B], arg1 error) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerGetSummaryCall[PP, PB, P, B]) Do(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerGetSummaryCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerGetSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetOutdated mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) SetOutdated(ctx context.Context, userId, reason string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOutdated", ctx, userId, reason)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetOutdated indicates an expected call of SetOutdated.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) SetOutdated(ctx, userId, reason any) *MockSummarizerSetOutdatedCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutdated", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).SetOutdated), ctx, userId, reason)
	return &MockSummarizerSetOutdatedCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerSetOutdatedCall wrap *gomock.Call
type MockSummarizerSetOutdatedCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerSetOutdatedCall[PP, PB, P, B]) Return(arg0 *time.Time, arg1 error) *MockSummarizerSetOutdatedCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerSetOutdatedCall[PP, PB, P, B]) Do(f func(context.Context, string, string) (*time.Time, error)) *MockSummarizerSetOutdatedCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerSetOutdatedCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string, string) (*time.Time, error)) *MockSummarizerSetOutdatedCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSummary mocks base method.
func (m *MockSummarizer[PP, PB, P, B]) UpdateSummary(ctx context.Context, userId string) (*types.Summary[PP, PB, P, B], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSummary", ctx, userId)
	ret0, _ := ret[0].(*types.Summary[PP, PB, P, B])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSummary indicates an expected call of UpdateSummary.
func (mr *MockSummarizerMockRecorder[PP, PB, P, B]) UpdateSummary(ctx, userId any) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSummary", reflect.TypeOf((*MockSummarizer[PP, PB, P, B])(nil).UpdateSummary), ctx, userId)
	return &MockSummarizerUpdateSummaryCall[PP, PB, P, B]{Call: call}
}

// MockSummarizerUpdateSummaryCall wrap *gomock.Call
type MockSummarizerUpdateSummaryCall[PP types.PeriodsPt[P, PB, B], PB types.BucketDataPt[B], P types.Periods, B types.BucketData] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummarizerUpdateSummaryCall[PP, PB, P, B]) Return(arg0 *types.Summary[PP, PB, P, B], arg1 error) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummarizerUpdateSummaryCall[PP, PB, P, B]) Do(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummarizerUpdateSummaryCall[PP, PB, P, B]) DoAndReturn(f func(context.Context, string) (*types.Summary[PP, PB, P, B], error)) *MockSummarizerUpdateSummaryCall[PP, PB, P, B] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
