// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package clinics is a generated GoMock package.
package clinics

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	api "github.com/tidepool-org/clinic/client"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetClinician mocks base method.
func (m *MockClient) GetClinician(ctx context.Context, clinicID, clinicianID string) (*api.Clinician, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClinician", ctx, clinicID, clinicianID)
	ret0, _ := ret[0].(*api.Clinician)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClinician indicates an expected call of GetClinician.
func (mr *MockClientMockRecorder) GetClinician(ctx, clinicID, clinicianID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClinician", reflect.TypeOf((*MockClient)(nil).GetClinician), ctx, clinicID, clinicianID)
}

// GetPatients mocks base method.
func (m *MockClient) GetPatients(ctx context.Context, clinicId string) ([]api.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatients", ctx, clinicId)
	ret0, _ := ret[0].([]api.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatients indicates an expected call of GetPatients.
func (mr *MockClientMockRecorder) GetPatients(ctx, clinicId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatients", reflect.TypeOf((*MockClient)(nil).GetPatients), ctx, clinicId)
}

// ListEHREnabledClinics mocks base method.
func (m *MockClient) ListEHREnabledClinics(ctx context.Context) ([]api.Clinic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEHREnabledClinics", ctx)
	ret0, _ := ret[0].([]api.Clinic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEHREnabledClinics indicates an expected call of ListEHREnabledClinics.
func (mr *MockClientMockRecorder) ListEHREnabledClinics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEHREnabledClinics", reflect.TypeOf((*MockClient)(nil).ListEHREnabledClinics), ctx)
}

// SharePatientAccount mocks base method.
func (m *MockClient) SharePatientAccount(ctx context.Context, clinicID, patientID string) (*api.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SharePatientAccount", ctx, clinicID, patientID)
	ret0, _ := ret[0].(*api.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SharePatientAccount indicates an expected call of SharePatientAccount.
func (mr *MockClientMockRecorder) SharePatientAccount(ctx, clinicID, patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SharePatientAccount", reflect.TypeOf((*MockClient)(nil).SharePatientAccount), ctx, clinicID, patientID)
}

// SyncEHRData mocks base method.
func (m *MockClient) SyncEHRData(ctx context.Context, clinicID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncEHRData", ctx, clinicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncEHRData indicates an expected call of SyncEHRData.
func (mr *MockClientMockRecorder) SyncEHRData(ctx, clinicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncEHRData", reflect.TypeOf((*MockClient)(nil).SyncEHRData), ctx, clinicID)
}
