// Code generated by MockGen. DO NOT EDIT.
// Source: bddp.go
//
// Generated by this command:
//
//	mockgen -source=bddp.go -destination=test/bddp_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBigDataDonationProjectSharer is a mock of BigDataDonationProjectSharer interface.
type MockBigDataDonationProjectSharer struct {
	ctrl     *gomock.Controller
	recorder *MockBigDataDonationProjectSharerMockRecorder
	isgomock struct{}
}

// MockBigDataDonationProjectSharerMockRecorder is the mock recorder for MockBigDataDonationProjectSharer.
type MockBigDataDonationProjectSharerMockRecorder struct {
	mock *MockBigDataDonationProjectSharer
}

// NewMockBigDataDonationProjectSharer creates a new mock instance.
func NewMockBigDataDonationProjectSharer(ctrl *gomock.Controller) *MockBigDataDonationProjectSharer {
	mock := &MockBigDataDonationProjectSharer{ctrl: ctrl}
	mock.recorder = &MockBigDataDonationProjectSharerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBigDataDonationProjectSharer) EXPECT() *MockBigDataDonationProjectSharerMockRecorder {
	return m.recorder
}

// Share mocks base method.
func (m *MockBigDataDonationProjectSharer) Share(ctx context.Context, sharerUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Share", ctx, sharerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Share indicates an expected call of Share.
func (mr *MockBigDataDonationProjectSharerMockRecorder) Share(ctx, sharerUserID any) *MockBigDataDonationProjectSharerShareCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Share", reflect.TypeOf((*MockBigDataDonationProjectSharer)(nil).Share), ctx, sharerUserID)
	return &MockBigDataDonationProjectSharerShareCall{Call: call}
}

// MockBigDataDonationProjectSharerShareCall wrap *gomock.Call
type MockBigDataDonationProjectSharerShareCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBigDataDonationProjectSharerShareCall) Return(arg0 error) *MockBigDataDonationProjectSharerShareCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBigDataDonationProjectSharerShareCall) Do(f func(context.Context, string) error) *MockBigDataDonationProjectSharerShareCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBigDataDonationProjectSharerShareCall) DoAndReturn(f func(context.Context, string) error) *MockBigDataDonationProjectSharerShareCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Unshare mocks base method.
func (m *MockBigDataDonationProjectSharer) Unshare(ctx context.Context, sharerUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unshare", ctx, sharerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unshare indicates an expected call of Unshare.
func (mr *MockBigDataDonationProjectSharerMockRecorder) Unshare(ctx, sharerUserID any) *MockBigDataDonationProjectSharerUnshareCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unshare", reflect.TypeOf((*MockBigDataDonationProjectSharer)(nil).Unshare), ctx, sharerUserID)
	return &MockBigDataDonationProjectSharerUnshareCall{Call: call}
}

// MockBigDataDonationProjectSharerUnshareCall wrap *gomock.Call
type MockBigDataDonationProjectSharerUnshareCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBigDataDonationProjectSharerUnshareCall) Return(arg0 error) *MockBigDataDonationProjectSharerUnshareCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBigDataDonationProjectSharerUnshareCall) Do(f func(context.Context, string) error) *MockBigDataDonationProjectSharerUnshareCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBigDataDonationProjectSharerUnshareCall) DoAndReturn(f func(context.Context, string) error) *MockBigDataDonationProjectSharerUnshareCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
