// Code generated by MockGen. DO NOT EDIT.
// Source: oauth.go
//
// Generated by this command:
//
//	mockgen -source=oauth.go -destination=test/oauth_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	http "net/http"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v4"
	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"

	auth "github.com/tidepool-org/platform/auth"
	oauth "github.com/tidepool-org/platform/oauth"
)

// MockTokenSourceSource is a mock of TokenSourceSource interface.
type MockTokenSourceSource struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSourceSourceMockRecorder
	isgomock struct{}
}

// MockTokenSourceSourceMockRecorder is the mock recorder for MockTokenSourceSource.
type MockTokenSourceSourceMockRecorder struct {
	mock *MockTokenSourceSource
}

// NewMockTokenSourceSource creates a new mock instance.
func NewMockTokenSourceSource(ctrl *gomock.Controller) *MockTokenSourceSource {
	mock := &MockTokenSourceSource{ctrl: ctrl}
	mock.recorder = &MockTokenSourceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSourceSource) EXPECT() *MockTokenSourceSourceMockRecorder {
	return m.recorder
}

// TokenSource mocks base method.
func (m *MockTokenSourceSource) TokenSource(ctx context.Context, token *auth.OAuthToken) (oauth2.TokenSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenSource", ctx, token)
	ret0, _ := ret[0].(oauth2.TokenSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenSource indicates an expected call of TokenSource.
func (mr *MockTokenSourceSourceMockRecorder) TokenSource(ctx, token any) *MockTokenSourceSourceTokenSourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenSource", reflect.TypeOf((*MockTokenSourceSource)(nil).TokenSource), ctx, token)
	return &MockTokenSourceSourceTokenSourceCall{Call: call}
}

// MockTokenSourceSourceTokenSourceCall wrap *gomock.Call
type MockTokenSourceSourceTokenSourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenSourceSourceTokenSourceCall) Return(arg0 oauth2.TokenSource, arg1 error) *MockTokenSourceSourceTokenSourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenSourceSourceTokenSourceCall) Do(f func(context.Context, *auth.OAuthToken) (oauth2.TokenSource, error)) *MockTokenSourceSourceTokenSourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenSourceSourceTokenSourceCall) DoAndReturn(f func(context.Context, *auth.OAuthToken) (oauth2.TokenSource, error)) *MockTokenSourceSourceTokenSourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// AllowUserInitiatedAction mocks base method.
func (m *MockProvider) AllowUserInitiatedAction(ctx context.Context, userID, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowUserInitiatedAction", ctx, userID, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllowUserInitiatedAction indicates an expected call of AllowUserInitiatedAction.
func (mr *MockProviderMockRecorder) AllowUserInitiatedAction(ctx, userID, action any) *MockProviderAllowUserInitiatedActionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowUserInitiatedAction", reflect.TypeOf((*MockProvider)(nil).AllowUserInitiatedAction), ctx, userID, action)
	return &MockProviderAllowUserInitiatedActionCall{Call: call}
}

// MockProviderAllowUserInitiatedActionCall wrap *gomock.Call
type MockProviderAllowUserInitiatedActionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderAllowUserInitiatedActionCall) Return(arg0 bool, arg1 error) *MockProviderAllowUserInitiatedActionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderAllowUserInitiatedActionCall) Do(f func(context.Context, string, string) (bool, error)) *MockProviderAllowUserInitiatedActionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderAllowUserInitiatedActionCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockProviderAllowUserInitiatedActionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CalculateStateForRestrictedToken mocks base method.
func (m *MockProvider) CalculateStateForRestrictedToken(restrictedToken string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateStateForRestrictedToken", restrictedToken)
	ret0, _ := ret[0].(string)
	return ret0
}

// CalculateStateForRestrictedToken indicates an expected call of CalculateStateForRestrictedToken.
func (mr *MockProviderMockRecorder) CalculateStateForRestrictedToken(restrictedToken any) *MockProviderCalculateStateForRestrictedTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateStateForRestrictedToken", reflect.TypeOf((*MockProvider)(nil).CalculateStateForRestrictedToken), restrictedToken)
	return &MockProviderCalculateStateForRestrictedTokenCall{Call: call}
}

// MockProviderCalculateStateForRestrictedTokenCall wrap *gomock.Call
type MockProviderCalculateStateForRestrictedTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderCalculateStateForRestrictedTokenCall) Return(arg0 string) *MockProviderCalculateStateForRestrictedTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderCalculateStateForRestrictedTokenCall) Do(f func(string) string) *MockProviderCalculateStateForRestrictedTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderCalculateStateForRestrictedTokenCall) DoAndReturn(f func(string) string) *MockProviderCalculateStateForRestrictedTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CookieDisabled mocks base method.
func (m *MockProvider) CookieDisabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CookieDisabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CookieDisabled indicates an expected call of CookieDisabled.
func (mr *MockProviderMockRecorder) CookieDisabled() *MockProviderCookieDisabledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CookieDisabled", reflect.TypeOf((*MockProvider)(nil).CookieDisabled))
	return &MockProviderCookieDisabledCall{Call: call}
}

// MockProviderCookieDisabledCall wrap *gomock.Call
type MockProviderCookieDisabledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderCookieDisabledCall) Return(arg0 bool) *MockProviderCookieDisabledCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderCookieDisabledCall) Do(f func() bool) *MockProviderCookieDisabledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderCookieDisabledCall) DoAndReturn(f func() bool) *MockProviderCookieDisabledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExchangeAuthorizationCodeForToken mocks base method.
func (m *MockProvider) ExchangeAuthorizationCodeForToken(ctx context.Context, authorizationCode string) (*auth.OAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeAuthorizationCodeForToken", ctx, authorizationCode)
	ret0, _ := ret[0].(*auth.OAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeAuthorizationCodeForToken indicates an expected call of ExchangeAuthorizationCodeForToken.
func (mr *MockProviderMockRecorder) ExchangeAuthorizationCodeForToken(ctx, authorizationCode any) *MockProviderExchangeAuthorizationCodeForTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeAuthorizationCodeForToken", reflect.TypeOf((*MockProvider)(nil).ExchangeAuthorizationCodeForToken), ctx, authorizationCode)
	return &MockProviderExchangeAuthorizationCodeForTokenCall{Call: call}
}

// MockProviderExchangeAuthorizationCodeForTokenCall wrap *gomock.Call
type MockProviderExchangeAuthorizationCodeForTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderExchangeAuthorizationCodeForTokenCall) Return(arg0 *auth.OAuthToken, arg1 error) *MockProviderExchangeAuthorizationCodeForTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderExchangeAuthorizationCodeForTokenCall) Do(f func(context.Context, string) (*auth.OAuthToken, error)) *MockProviderExchangeAuthorizationCodeForTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderExchangeAuthorizationCodeForTokenCall) DoAndReturn(f func(context.Context, string) (*auth.OAuthToken, error)) *MockProviderExchangeAuthorizationCodeForTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAuthorizationCodeURLWithState mocks base method.
func (m *MockProvider) GetAuthorizationCodeURLWithState(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationCodeURLWithState", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthorizationCodeURLWithState indicates an expected call of GetAuthorizationCodeURLWithState.
func (mr *MockProviderMockRecorder) GetAuthorizationCodeURLWithState(state any) *MockProviderGetAuthorizationCodeURLWithStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationCodeURLWithState", reflect.TypeOf((*MockProvider)(nil).GetAuthorizationCodeURLWithState), state)
	return &MockProviderGetAuthorizationCodeURLWithStateCall{Call: call}
}

// MockProviderGetAuthorizationCodeURLWithStateCall wrap *gomock.Call
type MockProviderGetAuthorizationCodeURLWithStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderGetAuthorizationCodeURLWithStateCall) Return(arg0 string) *MockProviderGetAuthorizationCodeURLWithStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderGetAuthorizationCodeURLWithStateCall) Do(f func(string) string) *MockProviderGetAuthorizationCodeURLWithStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderGetAuthorizationCodeURLWithStateCall) DoAndReturn(f func(string) string) *MockProviderGetAuthorizationCodeURLWithStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsErrorCodeAccessDenied mocks base method.
func (m *MockProvider) IsErrorCodeAccessDenied(errorCode string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsErrorCodeAccessDenied", errorCode)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsErrorCodeAccessDenied indicates an expected call of IsErrorCodeAccessDenied.
func (mr *MockProviderMockRecorder) IsErrorCodeAccessDenied(errorCode any) *MockProviderIsErrorCodeAccessDeniedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsErrorCodeAccessDenied", reflect.TypeOf((*MockProvider)(nil).IsErrorCodeAccessDenied), errorCode)
	return &MockProviderIsErrorCodeAccessDeniedCall{Call: call}
}

// MockProviderIsErrorCodeAccessDeniedCall wrap *gomock.Call
type MockProviderIsErrorCodeAccessDeniedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderIsErrorCodeAccessDeniedCall) Return(arg0 bool) *MockProviderIsErrorCodeAccessDeniedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderIsErrorCodeAccessDeniedCall) Do(f func(string) bool) *MockProviderIsErrorCodeAccessDeniedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderIsErrorCodeAccessDeniedCall) DoAndReturn(f func(string) bool) *MockProviderIsErrorCodeAccessDeniedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *MockProviderNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
	return &MockProviderNameCall{Call: call}
}

// MockProviderNameCall wrap *gomock.Call
type MockProviderNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderNameCall) Return(arg0 string) *MockProviderNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderNameCall) Do(f func() string) *MockProviderNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderNameCall) DoAndReturn(f func() string) *MockProviderNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OnCreate mocks base method.
func (m *MockProvider) OnCreate(ctx context.Context, providerSession *auth.ProviderSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCreate", ctx, providerSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCreate indicates an expected call of OnCreate.
func (mr *MockProviderMockRecorder) OnCreate(ctx, providerSession any) *MockProviderOnCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCreate", reflect.TypeOf((*MockProvider)(nil).OnCreate), ctx, providerSession)
	return &MockProviderOnCreateCall{Call: call}
}

// MockProviderOnCreateCall wrap *gomock.Call
type MockProviderOnCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderOnCreateCall) Return(arg0 error) *MockProviderOnCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderOnCreateCall) Do(f func(context.Context, *auth.ProviderSession) error) *MockProviderOnCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderOnCreateCall) DoAndReturn(f func(context.Context, *auth.ProviderSession) error) *MockProviderOnCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OnDelete mocks base method.
func (m *MockProvider) OnDelete(ctx context.Context, providerSession *auth.ProviderSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDelete", ctx, providerSession)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnDelete indicates an expected call of OnDelete.
func (mr *MockProviderMockRecorder) OnDelete(ctx, providerSession any) *MockProviderOnDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDelete", reflect.TypeOf((*MockProvider)(nil).OnDelete), ctx, providerSession)
	return &MockProviderOnDeleteCall{Call: call}
}

// MockProviderOnDeleteCall wrap *gomock.Call
type MockProviderOnDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderOnDeleteCall) Return(arg0 error) *MockProviderOnDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderOnDeleteCall) Do(f func(context.Context, *auth.ProviderSession) error) *MockProviderOnDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderOnDeleteCall) DoAndReturn(f func(context.Context, *auth.ProviderSession) error) *MockProviderOnDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseToken mocks base method.
func (m *MockProvider) ParseToken(token string, claims jwt.Claims) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", token, claims)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockProviderMockRecorder) ParseToken(token, claims any) *MockProviderParseTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockProvider)(nil).ParseToken), token, claims)
	return &MockProviderParseTokenCall{Call: call}
}

// MockProviderParseTokenCall wrap *gomock.Call
type MockProviderParseTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderParseTokenCall) Return(arg0 error) *MockProviderParseTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderParseTokenCall) Do(f func(string, jwt.Claims) error) *MockProviderParseTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderParseTokenCall) DoAndReturn(f func(string, jwt.Claims) error) *MockProviderParseTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TokenSource mocks base method.
func (m *MockProvider) TokenSource(ctx context.Context, token *auth.OAuthToken) (oauth2.TokenSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenSource", ctx, token)
	ret0, _ := ret[0].(oauth2.TokenSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenSource indicates an expected call of TokenSource.
func (mr *MockProviderMockRecorder) TokenSource(ctx, token any) *MockProviderTokenSourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenSource", reflect.TypeOf((*MockProvider)(nil).TokenSource), ctx, token)
	return &MockProviderTokenSourceCall{Call: call}
}

// MockProviderTokenSourceCall wrap *gomock.Call
type MockProviderTokenSourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderTokenSourceCall) Return(arg0 oauth2.TokenSource, arg1 error) *MockProviderTokenSourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderTokenSourceCall) Do(f func(context.Context, *auth.OAuthToken) (oauth2.TokenSource, error)) *MockProviderTokenSourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderTokenSourceCall) DoAndReturn(f func(context.Context, *auth.OAuthToken) (oauth2.TokenSource, error)) *MockProviderTokenSourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Type mocks base method.
func (m *MockProvider) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockProviderMockRecorder) Type() *MockProviderTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockProvider)(nil).Type))
	return &MockProviderTypeCall{Call: call}
}

// MockProviderTypeCall wrap *gomock.Call
type MockProviderTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderTypeCall) Return(arg0 string) *MockProviderTypeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderTypeCall) Do(f func() string) *MockProviderTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderTypeCall) DoAndReturn(f func() string) *MockProviderTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UserActionAcceptURL mocks base method.
func (m *MockProvider) UserActionAcceptURL(ctx context.Context, userID, action string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserActionAcceptURL", ctx, userID, action)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserActionAcceptURL indicates an expected call of UserActionAcceptURL.
func (mr *MockProviderMockRecorder) UserActionAcceptURL(ctx, userID, action any) *MockProviderUserActionAcceptURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserActionAcceptURL", reflect.TypeOf((*MockProvider)(nil).UserActionAcceptURL), ctx, userID, action)
	return &MockProviderUserActionAcceptURLCall{Call: call}
}

// MockProviderUserActionAcceptURLCall wrap *gomock.Call
type MockProviderUserActionAcceptURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderUserActionAcceptURLCall) Return(arg0 *string, arg1 error) *MockProviderUserActionAcceptURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderUserActionAcceptURLCall) Do(f func(context.Context, string, string) (*string, error)) *MockProviderUserActionAcceptURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderUserActionAcceptURLCall) DoAndReturn(f func(context.Context, string, string) (*string, error)) *MockProviderUserActionAcceptURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTokenSource is a mock of TokenSource interface.
type MockTokenSource struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSourceMockRecorder
	isgomock struct{}
}

// MockTokenSourceMockRecorder is the mock recorder for MockTokenSource.
type MockTokenSourceMockRecorder struct {
	mock *MockTokenSource
}

// NewMockTokenSource creates a new mock instance.
func NewMockTokenSource(ctrl *gomock.Controller) *MockTokenSource {
	mock := &MockTokenSource{ctrl: ctrl}
	mock.recorder = &MockTokenSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSource) EXPECT() *MockTokenSourceMockRecorder {
	return m.recorder
}

// ExpireToken mocks base method.
func (m *MockTokenSource) ExpireToken(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireToken", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireToken indicates an expected call of ExpireToken.
func (mr *MockTokenSourceMockRecorder) ExpireToken(ctx any) *MockTokenSourceExpireTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireToken", reflect.TypeOf((*MockTokenSource)(nil).ExpireToken), ctx)
	return &MockTokenSourceExpireTokenCall{Call: call}
}

// MockTokenSourceExpireTokenCall wrap *gomock.Call
type MockTokenSourceExpireTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenSourceExpireTokenCall) Return(arg0 bool, arg1 error) *MockTokenSourceExpireTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenSourceExpireTokenCall) Do(f func(context.Context) (bool, error)) *MockTokenSourceExpireTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenSourceExpireTokenCall) DoAndReturn(f func(context.Context) (bool, error)) *MockTokenSourceExpireTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HTTPClient mocks base method.
func (m *MockTokenSource) HTTPClient(ctx context.Context, tokenSourceSource oauth.TokenSourceSource) (*http.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClient", ctx, tokenSourceSource)
	ret0, _ := ret[0].(*http.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockTokenSourceMockRecorder) HTTPClient(ctx, tokenSourceSource any) *MockTokenSourceHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClient", reflect.TypeOf((*MockTokenSource)(nil).HTTPClient), ctx, tokenSourceSource)
	return &MockTokenSourceHTTPClientCall{Call: call}
}

// MockTokenSourceHTTPClientCall wrap *gomock.Call
type MockTokenSourceHTTPClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenSourceHTTPClientCall) Return(arg0 *http.Client, arg1 error) *MockTokenSourceHTTPClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenSourceHTTPClientCall) Do(f func(context.Context, oauth.TokenSourceSource) (*http.Client, error)) *MockTokenSourceHTTPClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenSourceHTTPClientCall) DoAndReturn(f func(context.Context, oauth.TokenSourceSource) (*http.Client, error)) *MockTokenSourceHTTPClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateToken mocks base method.
func (m *MockTokenSource) UpdateToken(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateToken indicates an expected call of UpdateToken.
func (mr *MockTokenSourceMockRecorder) UpdateToken(ctx any) *MockTokenSourceUpdateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockTokenSource)(nil).UpdateToken), ctx)
	return &MockTokenSourceUpdateTokenCall{Call: call}
}

// MockTokenSourceUpdateTokenCall wrap *gomock.Call
type MockTokenSourceUpdateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenSourceUpdateTokenCall) Return(arg0 bool, arg1 error) *MockTokenSourceUpdateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenSourceUpdateTokenCall) Do(f func(context.Context) (bool, error)) *MockTokenSourceUpdateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenSourceUpdateTokenCall) DoAndReturn(f func(context.Context) (bool, error)) *MockTokenSourceUpdateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
