// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tidepool-org/hydrophone/client (interfaces: ClientWithResponsesInterface)
//
// Generated by this command:
//
//	mockgen -destination=test/confirmation_mocks.go -package=test -typed -mock_names=ClientWithResponsesInterface=MockConfirmationClient github.com/tidepool-org/hydrophone/client ClientWithResponsesInterface
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	io "io"
	reflect "reflect"

	api "github.com/tidepool-org/hydrophone/client"
	gomock "go.uber.org/mock/gomock"
)

// MockConfirmationClient is a mock of ClientWithResponsesInterface interface.
type MockConfirmationClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationClientMockRecorder
	isgomock struct{}
}

// MockConfirmationClientMockRecorder is the mock recorder for MockConfirmationClient.
type MockConfirmationClientMockRecorder struct {
	mock *MockConfirmationClient
}

// NewMockConfirmationClient creates a new mock instance.
func NewMockConfirmationClient(ctrl *gomock.Controller) *MockConfirmationClient {
	mock := &MockConfirmationClient{ctrl: ctrl}
	mock.recorder = &MockConfirmationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationClient) EXPECT() *MockConfirmationClientMockRecorder {
	return m.recorder
}

// AcceptCareTeamInviteWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) AcceptCareTeamInviteWithBodyWithResponse(ctx context.Context, userId api.UserId, invitedBy api.InvitedByUser, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.AcceptCareTeamInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, invitedBy, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptCareTeamInviteWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AcceptCareTeamInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptCareTeamInviteWithBodyWithResponse indicates an expected call of AcceptCareTeamInviteWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) AcceptCareTeamInviteWithBodyWithResponse(ctx, userId, invitedBy, contentType, body any, reqEditors ...any) *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, invitedBy, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptCareTeamInviteWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).AcceptCareTeamInviteWithBodyWithResponse), varargs...)
	return &MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall) Return(arg0 *api.AcceptCareTeamInviteResponse, arg1 error) *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, api.InvitedByUser, string, io.Reader, ...api.RequestEditorFn) (*api.AcceptCareTeamInviteResponse, error)) *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.InvitedByUser, string, io.Reader, ...api.RequestEditorFn) (*api.AcceptCareTeamInviteResponse, error)) *MockConfirmationClientAcceptCareTeamInviteWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AcceptCareTeamInviteWithResponse mocks base method.
func (m *MockConfirmationClient) AcceptCareTeamInviteWithResponse(ctx context.Context, userId api.UserId, invitedBy api.InvitedByUser, body api.AcceptCareTeamInviteJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.AcceptCareTeamInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, invitedBy, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptCareTeamInviteWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AcceptCareTeamInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptCareTeamInviteWithResponse indicates an expected call of AcceptCareTeamInviteWithResponse.
func (mr *MockConfirmationClientMockRecorder) AcceptCareTeamInviteWithResponse(ctx, userId, invitedBy, body any, reqEditors ...any) *MockConfirmationClientAcceptCareTeamInviteWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, invitedBy, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptCareTeamInviteWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).AcceptCareTeamInviteWithResponse), varargs...)
	return &MockConfirmationClientAcceptCareTeamInviteWithResponseCall{Call: call}
}

// MockConfirmationClientAcceptCareTeamInviteWithResponseCall wrap *gomock.Call
type MockConfirmationClientAcceptCareTeamInviteWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientAcceptCareTeamInviteWithResponseCall) Return(arg0 *api.AcceptCareTeamInviteResponse, arg1 error) *MockConfirmationClientAcceptCareTeamInviteWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientAcceptCareTeamInviteWithResponseCall) Do(f func(context.Context, api.UserId, api.InvitedByUser, api.AcceptCareTeamInviteJSONRequestBody, ...api.RequestEditorFn) (*api.AcceptCareTeamInviteResponse, error)) *MockConfirmationClientAcceptCareTeamInviteWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientAcceptCareTeamInviteWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.InvitedByUser, api.AcceptCareTeamInviteJSONRequestBody, ...api.RequestEditorFn) (*api.AcceptCareTeamInviteResponse, error)) *MockConfirmationClientAcceptCareTeamInviteWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AcceptPasswordChangeWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) AcceptPasswordChangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.AcceptPasswordChangeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptPasswordChangeWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AcceptPasswordChangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptPasswordChangeWithBodyWithResponse indicates an expected call of AcceptPasswordChangeWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) AcceptPasswordChangeWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptPasswordChangeWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).AcceptPasswordChangeWithBodyWithResponse), varargs...)
	return &MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall) Return(arg0 *api.AcceptPasswordChangeResponse, arg1 error) *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall) Do(f func(context.Context, string, io.Reader, ...api.RequestEditorFn) (*api.AcceptPasswordChangeResponse, error)) *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall) DoAndReturn(f func(context.Context, string, io.Reader, ...api.RequestEditorFn) (*api.AcceptPasswordChangeResponse, error)) *MockConfirmationClientAcceptPasswordChangeWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AcceptPasswordChangeWithResponse mocks base method.
func (m *MockConfirmationClient) AcceptPasswordChangeWithResponse(ctx context.Context, body api.AcceptPasswordChangeJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.AcceptPasswordChangeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptPasswordChangeWithResponse", varargs...)
	ret0, _ := ret[0].(*api.AcceptPasswordChangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptPasswordChangeWithResponse indicates an expected call of AcceptPasswordChangeWithResponse.
func (mr *MockConfirmationClientMockRecorder) AcceptPasswordChangeWithResponse(ctx, body any, reqEditors ...any) *MockConfirmationClientAcceptPasswordChangeWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptPasswordChangeWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).AcceptPasswordChangeWithResponse), varargs...)
	return &MockConfirmationClientAcceptPasswordChangeWithResponseCall{Call: call}
}

// MockConfirmationClientAcceptPasswordChangeWithResponseCall wrap *gomock.Call
type MockConfirmationClientAcceptPasswordChangeWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientAcceptPasswordChangeWithResponseCall) Return(arg0 *api.AcceptPasswordChangeResponse, arg1 error) *MockConfirmationClientAcceptPasswordChangeWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientAcceptPasswordChangeWithResponseCall) Do(f func(context.Context, api.AcceptPasswordChangeJSONRequestBody, ...api.RequestEditorFn) (*api.AcceptPasswordChangeResponse, error)) *MockConfirmationClientAcceptPasswordChangeWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientAcceptPasswordChangeWithResponseCall) DoAndReturn(f func(context.Context, api.AcceptPasswordChangeJSONRequestBody, ...api.RequestEditorFn) (*api.AcceptPasswordChangeResponse, error)) *MockConfirmationClientAcceptPasswordChangeWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelAccountSignupConfirmationWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) CancelAccountSignupConfirmationWithBodyWithResponse(ctx context.Context, userId api.UserId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CancelAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelAccountSignupConfirmationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CancelAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAccountSignupConfirmationWithBodyWithResponse indicates an expected call of CancelAccountSignupConfirmationWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) CancelAccountSignupConfirmationWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAccountSignupConfirmationWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).CancelAccountSignupConfirmationWithBodyWithResponse), varargs...)
	return &MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall) Return(arg0 *api.CancelAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.CancelAccountSignupConfirmationResponse, error)) *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.CancelAccountSignupConfirmationResponse, error)) *MockConfirmationClientCancelAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelAccountSignupConfirmationWithResponse mocks base method.
func (m *MockConfirmationClient) CancelAccountSignupConfirmationWithResponse(ctx context.Context, userId api.UserId, body api.CancelAccountSignupConfirmationJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CancelAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelAccountSignupConfirmationWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CancelAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAccountSignupConfirmationWithResponse indicates an expected call of CancelAccountSignupConfirmationWithResponse.
func (mr *MockConfirmationClientMockRecorder) CancelAccountSignupConfirmationWithResponse(ctx, userId, body any, reqEditors ...any) *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAccountSignupConfirmationWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).CancelAccountSignupConfirmationWithResponse), varargs...)
	return &MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall{Call: call}
}

// MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall wrap *gomock.Call
type MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall) Return(arg0 *api.CancelAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall) Do(f func(context.Context, api.UserId, api.CancelAccountSignupConfirmationJSONRequestBody, ...api.RequestEditorFn) (*api.CancelAccountSignupConfirmationResponse, error)) *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.CancelAccountSignupConfirmationJSONRequestBody, ...api.RequestEditorFn) (*api.CancelAccountSignupConfirmationResponse, error)) *MockConfirmationClientCancelAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelInviteWithResponse mocks base method.
func (m *MockConfirmationClient) CancelInviteWithResponse(ctx context.Context, userId api.UserId, invitedBy api.InvitedByEmail, reqEditors ...api.RequestEditorFn) (*api.CancelInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, invitedBy}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelInviteWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CancelInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelInviteWithResponse indicates an expected call of CancelInviteWithResponse.
func (mr *MockConfirmationClientMockRecorder) CancelInviteWithResponse(ctx, userId, invitedBy any, reqEditors ...any) *MockConfirmationClientCancelInviteWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, invitedBy}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInviteWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).CancelInviteWithResponse), varargs...)
	return &MockConfirmationClientCancelInviteWithResponseCall{Call: call}
}

// MockConfirmationClientCancelInviteWithResponseCall wrap *gomock.Call
type MockConfirmationClientCancelInviteWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientCancelInviteWithResponseCall) Return(arg0 *api.CancelInviteResponse, arg1 error) *MockConfirmationClientCancelInviteWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientCancelInviteWithResponseCall) Do(f func(context.Context, api.UserId, api.InvitedByEmail, ...api.RequestEditorFn) (*api.CancelInviteResponse, error)) *MockConfirmationClientCancelInviteWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientCancelInviteWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.InvitedByEmail, ...api.RequestEditorFn) (*api.CancelInviteResponse, error)) *MockConfirmationClientCancelInviteWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfirmAccountSignupWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) ConfirmAccountSignupWithBodyWithResponse(ctx context.Context, key api.Key, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.ConfirmAccountSignupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConfirmAccountSignupWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ConfirmAccountSignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmAccountSignupWithBodyWithResponse indicates an expected call of ConfirmAccountSignupWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) ConfirmAccountSignupWithBodyWithResponse(ctx, key, contentType, body any, reqEditors ...any) *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAccountSignupWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).ConfirmAccountSignupWithBodyWithResponse), varargs...)
	return &MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall) Return(arg0 *api.ConfirmAccountSignupResponse, arg1 error) *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall) Do(f func(context.Context, api.Key, string, io.Reader, ...api.RequestEditorFn) (*api.ConfirmAccountSignupResponse, error)) *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.Key, string, io.Reader, ...api.RequestEditorFn) (*api.ConfirmAccountSignupResponse, error)) *MockConfirmationClientConfirmAccountSignupWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfirmAccountSignupWithResponse mocks base method.
func (m *MockConfirmationClient) ConfirmAccountSignupWithResponse(ctx context.Context, key api.Key, body api.ConfirmAccountSignupJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.ConfirmAccountSignupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConfirmAccountSignupWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ConfirmAccountSignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmAccountSignupWithResponse indicates an expected call of ConfirmAccountSignupWithResponse.
func (mr *MockConfirmationClientMockRecorder) ConfirmAccountSignupWithResponse(ctx, key, body any, reqEditors ...any) *MockConfirmationClientConfirmAccountSignupWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAccountSignupWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).ConfirmAccountSignupWithResponse), varargs...)
	return &MockConfirmationClientConfirmAccountSignupWithResponseCall{Call: call}
}

// MockConfirmationClientConfirmAccountSignupWithResponseCall wrap *gomock.Call
type MockConfirmationClientConfirmAccountSignupWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientConfirmAccountSignupWithResponseCall) Return(arg0 *api.ConfirmAccountSignupResponse, arg1 error) *MockConfirmationClientConfirmAccountSignupWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientConfirmAccountSignupWithResponseCall) Do(f func(context.Context, api.Key, api.ConfirmAccountSignupJSONRequestBody, ...api.RequestEditorFn) (*api.ConfirmAccountSignupResponse, error)) *MockConfirmationClientConfirmAccountSignupWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientConfirmAccountSignupWithResponseCall) DoAndReturn(f func(context.Context, api.Key, api.ConfirmAccountSignupJSONRequestBody, ...api.RequestEditorFn) (*api.ConfirmAccountSignupResponse, error)) *MockConfirmationClientConfirmAccountSignupWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DismissAccountSignupWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) DismissAccountSignupWithBodyWithResponse(ctx context.Context, userId api.UserId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.DismissAccountSignupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DismissAccountSignupWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DismissAccountSignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DismissAccountSignupWithBodyWithResponse indicates an expected call of DismissAccountSignupWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) DismissAccountSignupWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissAccountSignupWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).DismissAccountSignupWithBodyWithResponse), varargs...)
	return &MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall) Return(arg0 *api.DismissAccountSignupResponse, arg1 error) *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.DismissAccountSignupResponse, error)) *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.DismissAccountSignupResponse, error)) *MockConfirmationClientDismissAccountSignupWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DismissAccountSignupWithResponse mocks base method.
func (m *MockConfirmationClient) DismissAccountSignupWithResponse(ctx context.Context, userId api.UserId, body api.DismissAccountSignupJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.DismissAccountSignupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DismissAccountSignupWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DismissAccountSignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DismissAccountSignupWithResponse indicates an expected call of DismissAccountSignupWithResponse.
func (mr *MockConfirmationClientMockRecorder) DismissAccountSignupWithResponse(ctx, userId, body any, reqEditors ...any) *MockConfirmationClientDismissAccountSignupWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissAccountSignupWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).DismissAccountSignupWithResponse), varargs...)
	return &MockConfirmationClientDismissAccountSignupWithResponseCall{Call: call}
}

// MockConfirmationClientDismissAccountSignupWithResponseCall wrap *gomock.Call
type MockConfirmationClientDismissAccountSignupWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientDismissAccountSignupWithResponseCall) Return(arg0 *api.DismissAccountSignupResponse, arg1 error) *MockConfirmationClientDismissAccountSignupWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientDismissAccountSignupWithResponseCall) Do(f func(context.Context, api.UserId, api.DismissAccountSignupJSONRequestBody, ...api.RequestEditorFn) (*api.DismissAccountSignupResponse, error)) *MockConfirmationClientDismissAccountSignupWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientDismissAccountSignupWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.DismissAccountSignupJSONRequestBody, ...api.RequestEditorFn) (*api.DismissAccountSignupResponse, error)) *MockConfirmationClientDismissAccountSignupWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DismissInviteWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) DismissInviteWithBodyWithResponse(ctx context.Context, userId api.UserId, invitedBy api.InvitedByUser, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.DismissInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, invitedBy, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DismissInviteWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DismissInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DismissInviteWithBodyWithResponse indicates an expected call of DismissInviteWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) DismissInviteWithBodyWithResponse(ctx, userId, invitedBy, contentType, body any, reqEditors ...any) *MockConfirmationClientDismissInviteWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, invitedBy, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissInviteWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).DismissInviteWithBodyWithResponse), varargs...)
	return &MockConfirmationClientDismissInviteWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientDismissInviteWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientDismissInviteWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientDismissInviteWithBodyWithResponseCall) Return(arg0 *api.DismissInviteResponse, arg1 error) *MockConfirmationClientDismissInviteWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientDismissInviteWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, api.InvitedByUser, string, io.Reader, ...api.RequestEditorFn) (*api.DismissInviteResponse, error)) *MockConfirmationClientDismissInviteWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientDismissInviteWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.InvitedByUser, string, io.Reader, ...api.RequestEditorFn) (*api.DismissInviteResponse, error)) *MockConfirmationClientDismissInviteWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DismissInviteWithResponse mocks base method.
func (m *MockConfirmationClient) DismissInviteWithResponse(ctx context.Context, userId api.UserId, invitedBy api.InvitedByUser, body api.DismissInviteJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.DismissInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, invitedBy, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DismissInviteWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DismissInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DismissInviteWithResponse indicates an expected call of DismissInviteWithResponse.
func (mr *MockConfirmationClientMockRecorder) DismissInviteWithResponse(ctx, userId, invitedBy, body any, reqEditors ...any) *MockConfirmationClientDismissInviteWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, invitedBy, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissInviteWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).DismissInviteWithResponse), varargs...)
	return &MockConfirmationClientDismissInviteWithResponseCall{Call: call}
}

// MockConfirmationClientDismissInviteWithResponseCall wrap *gomock.Call
type MockConfirmationClientDismissInviteWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientDismissInviteWithResponseCall) Return(arg0 *api.DismissInviteResponse, arg1 error) *MockConfirmationClientDismissInviteWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientDismissInviteWithResponseCall) Do(f func(context.Context, api.UserId, api.InvitedByUser, api.DismissInviteJSONRequestBody, ...api.RequestEditorFn) (*api.DismissInviteResponse, error)) *MockConfirmationClientDismissInviteWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientDismissInviteWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.InvitedByUser, api.DismissInviteJSONRequestBody, ...api.RequestEditorFn) (*api.DismissInviteResponse, error)) *MockConfirmationClientDismissInviteWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAccountSignupConfirmationWithResponse mocks base method.
func (m *MockConfirmationClient) GetAccountSignupConfirmationWithResponse(ctx context.Context, userId api.UserId, reqEditors ...api.RequestEditorFn) (*api.GetAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountSignupConfirmationWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSignupConfirmationWithResponse indicates an expected call of GetAccountSignupConfirmationWithResponse.
func (mr *MockConfirmationClientMockRecorder) GetAccountSignupConfirmationWithResponse(ctx, userId any, reqEditors ...any) *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSignupConfirmationWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).GetAccountSignupConfirmationWithResponse), varargs...)
	return &MockConfirmationClientGetAccountSignupConfirmationWithResponseCall{Call: call}
}

// MockConfirmationClientGetAccountSignupConfirmationWithResponseCall wrap *gomock.Call
type MockConfirmationClientGetAccountSignupConfirmationWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall) Return(arg0 *api.GetAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall) Do(f func(context.Context, api.UserId, ...api.RequestEditorFn) (*api.GetAccountSignupConfirmationResponse, error)) *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, ...api.RequestEditorFn) (*api.GetAccountSignupConfirmationResponse, error)) *MockConfirmationClientGetAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetReceivedInvitationsWithResponse mocks base method.
func (m *MockConfirmationClient) GetReceivedInvitationsWithResponse(ctx context.Context, userId api.UserId, reqEditors ...api.RequestEditorFn) (*api.GetReceivedInvitationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReceivedInvitationsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetReceivedInvitationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceivedInvitationsWithResponse indicates an expected call of GetReceivedInvitationsWithResponse.
func (mr *MockConfirmationClientMockRecorder) GetReceivedInvitationsWithResponse(ctx, userId any, reqEditors ...any) *MockConfirmationClientGetReceivedInvitationsWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivedInvitationsWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).GetReceivedInvitationsWithResponse), varargs...)
	return &MockConfirmationClientGetReceivedInvitationsWithResponseCall{Call: call}
}

// MockConfirmationClientGetReceivedInvitationsWithResponseCall wrap *gomock.Call
type MockConfirmationClientGetReceivedInvitationsWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientGetReceivedInvitationsWithResponseCall) Return(arg0 *api.GetReceivedInvitationsResponse, arg1 error) *MockConfirmationClientGetReceivedInvitationsWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientGetReceivedInvitationsWithResponseCall) Do(f func(context.Context, api.UserId, ...api.RequestEditorFn) (*api.GetReceivedInvitationsResponse, error)) *MockConfirmationClientGetReceivedInvitationsWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientGetReceivedInvitationsWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, ...api.RequestEditorFn) (*api.GetReceivedInvitationsResponse, error)) *MockConfirmationClientGetReceivedInvitationsWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSentInvitationsWithResponse mocks base method.
func (m *MockConfirmationClient) GetSentInvitationsWithResponse(ctx context.Context, userId api.UserId, reqEditors ...api.RequestEditorFn) (*api.GetSentInvitationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSentInvitationsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetSentInvitationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentInvitationsWithResponse indicates an expected call of GetSentInvitationsWithResponse.
func (mr *MockConfirmationClientMockRecorder) GetSentInvitationsWithResponse(ctx, userId any, reqEditors ...any) *MockConfirmationClientGetSentInvitationsWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentInvitationsWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).GetSentInvitationsWithResponse), varargs...)
	return &MockConfirmationClientGetSentInvitationsWithResponseCall{Call: call}
}

// MockConfirmationClientGetSentInvitationsWithResponseCall wrap *gomock.Call
type MockConfirmationClientGetSentInvitationsWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientGetSentInvitationsWithResponseCall) Return(arg0 *api.GetSentInvitationsResponse, arg1 error) *MockConfirmationClientGetSentInvitationsWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientGetSentInvitationsWithResponseCall) Do(f func(context.Context, api.UserId, ...api.RequestEditorFn) (*api.GetSentInvitationsResponse, error)) *MockConfirmationClientGetSentInvitationsWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientGetSentInvitationsWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, ...api.RequestEditorFn) (*api.GetSentInvitationsResponse, error)) *MockConfirmationClientGetSentInvitationsWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResendAccountSignupWithResponse mocks base method.
func (m *MockConfirmationClient) ResendAccountSignupWithResponse(ctx context.Context, email api.Email, reqEditors ...api.RequestEditorFn) (*api.ResendAccountSignupResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, email}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResendAccountSignupWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ResendAccountSignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendAccountSignupWithResponse indicates an expected call of ResendAccountSignupWithResponse.
func (mr *MockConfirmationClientMockRecorder) ResendAccountSignupWithResponse(ctx, email any, reqEditors ...any) *MockConfirmationClientResendAccountSignupWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, email}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendAccountSignupWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).ResendAccountSignupWithResponse), varargs...)
	return &MockConfirmationClientResendAccountSignupWithResponseCall{Call: call}
}

// MockConfirmationClientResendAccountSignupWithResponseCall wrap *gomock.Call
type MockConfirmationClientResendAccountSignupWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientResendAccountSignupWithResponseCall) Return(arg0 *api.ResendAccountSignupResponse, arg1 error) *MockConfirmationClientResendAccountSignupWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientResendAccountSignupWithResponseCall) Do(f func(context.Context, api.Email, ...api.RequestEditorFn) (*api.ResendAccountSignupResponse, error)) *MockConfirmationClientResendAccountSignupWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientResendAccountSignupWithResponseCall) DoAndReturn(f func(context.Context, api.Email, ...api.RequestEditorFn) (*api.ResendAccountSignupResponse, error)) *MockConfirmationClientResendAccountSignupWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendAccountSignupConfirmationWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) SendAccountSignupConfirmationWithBodyWithResponse(ctx context.Context, userId api.UserId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SendAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendAccountSignupConfirmationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SendAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAccountSignupConfirmationWithBodyWithResponse indicates an expected call of SendAccountSignupConfirmationWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) SendAccountSignupConfirmationWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAccountSignupConfirmationWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).SendAccountSignupConfirmationWithBodyWithResponse), varargs...)
	return &MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall) Return(arg0 *api.SendAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.SendAccountSignupConfirmationResponse, error)) *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.SendAccountSignupConfirmationResponse, error)) *MockConfirmationClientSendAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendAccountSignupConfirmationWithResponse mocks base method.
func (m *MockConfirmationClient) SendAccountSignupConfirmationWithResponse(ctx context.Context, userId api.UserId, body api.SendAccountSignupConfirmationJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SendAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendAccountSignupConfirmationWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SendAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAccountSignupConfirmationWithResponse indicates an expected call of SendAccountSignupConfirmationWithResponse.
func (mr *MockConfirmationClientMockRecorder) SendAccountSignupConfirmationWithResponse(ctx, userId, body any, reqEditors ...any) *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAccountSignupConfirmationWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).SendAccountSignupConfirmationWithResponse), varargs...)
	return &MockConfirmationClientSendAccountSignupConfirmationWithResponseCall{Call: call}
}

// MockConfirmationClientSendAccountSignupConfirmationWithResponseCall wrap *gomock.Call
type MockConfirmationClientSendAccountSignupConfirmationWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall) Return(arg0 *api.SendAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall) Do(f func(context.Context, api.UserId, api.SendAccountSignupConfirmationJSONRequestBody, ...api.RequestEditorFn) (*api.SendAccountSignupConfirmationResponse, error)) *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.SendAccountSignupConfirmationJSONRequestBody, ...api.RequestEditorFn) (*api.SendAccountSignupConfirmationResponse, error)) *MockConfirmationClientSendAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendCareTeamInviteWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) SendCareTeamInviteWithBodyWithResponse(ctx context.Context, userId api.UserId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SendCareTeamInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendCareTeamInviteWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SendCareTeamInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCareTeamInviteWithBodyWithResponse indicates an expected call of SendCareTeamInviteWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) SendCareTeamInviteWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCareTeamInviteWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).SendCareTeamInviteWithBodyWithResponse), varargs...)
	return &MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall) Return(arg0 *api.SendCareTeamInviteResponse, arg1 error) *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.SendCareTeamInviteResponse, error)) *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.SendCareTeamInviteResponse, error)) *MockConfirmationClientSendCareTeamInviteWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendCareTeamInviteWithResponse mocks base method.
func (m *MockConfirmationClient) SendCareTeamInviteWithResponse(ctx context.Context, userId api.UserId, body api.SendCareTeamInviteJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SendCareTeamInviteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendCareTeamInviteWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SendCareTeamInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCareTeamInviteWithResponse indicates an expected call of SendCareTeamInviteWithResponse.
func (mr *MockConfirmationClientMockRecorder) SendCareTeamInviteWithResponse(ctx, userId, body any, reqEditors ...any) *MockConfirmationClientSendCareTeamInviteWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCareTeamInviteWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).SendCareTeamInviteWithResponse), varargs...)
	return &MockConfirmationClientSendCareTeamInviteWithResponseCall{Call: call}
}

// MockConfirmationClientSendCareTeamInviteWithResponseCall wrap *gomock.Call
type MockConfirmationClientSendCareTeamInviteWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientSendCareTeamInviteWithResponseCall) Return(arg0 *api.SendCareTeamInviteResponse, arg1 error) *MockConfirmationClientSendCareTeamInviteWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientSendCareTeamInviteWithResponseCall) Do(f func(context.Context, api.UserId, api.SendCareTeamInviteJSONRequestBody, ...api.RequestEditorFn) (*api.SendCareTeamInviteResponse, error)) *MockConfirmationClientSendCareTeamInviteWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientSendCareTeamInviteWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.SendCareTeamInviteJSONRequestBody, ...api.RequestEditorFn) (*api.SendCareTeamInviteResponse, error)) *MockConfirmationClientSendCareTeamInviteWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendPasswordResetWithResponse mocks base method.
func (m *MockConfirmationClient) SendPasswordResetWithResponse(ctx context.Context, email api.Email, reqEditors ...api.RequestEditorFn) (*api.SendPasswordResetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, email}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendPasswordResetWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SendPasswordResetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPasswordResetWithResponse indicates an expected call of SendPasswordResetWithResponse.
func (mr *MockConfirmationClientMockRecorder) SendPasswordResetWithResponse(ctx, email any, reqEditors ...any) *MockConfirmationClientSendPasswordResetWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, email}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).SendPasswordResetWithResponse), varargs...)
	return &MockConfirmationClientSendPasswordResetWithResponseCall{Call: call}
}

// MockConfirmationClientSendPasswordResetWithResponseCall wrap *gomock.Call
type MockConfirmationClientSendPasswordResetWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientSendPasswordResetWithResponseCall) Return(arg0 *api.SendPasswordResetResponse, arg1 error) *MockConfirmationClientSendPasswordResetWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientSendPasswordResetWithResponseCall) Do(f func(context.Context, api.Email, ...api.RequestEditorFn) (*api.SendPasswordResetResponse, error)) *MockConfirmationClientSendPasswordResetWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientSendPasswordResetWithResponseCall) DoAndReturn(f func(context.Context, api.Email, ...api.RequestEditorFn) (*api.SendPasswordResetResponse, error)) *MockConfirmationClientSendPasswordResetWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpsertAccountSignupConfirmationWithBodyWithResponse mocks base method.
func (m *MockConfirmationClient) UpsertAccountSignupConfirmationWithBodyWithResponse(ctx context.Context, userId api.UserId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.UpsertAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpsertAccountSignupConfirmationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpsertAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAccountSignupConfirmationWithBodyWithResponse indicates an expected call of UpsertAccountSignupConfirmationWithBodyWithResponse.
func (mr *MockConfirmationClientMockRecorder) UpsertAccountSignupConfirmationWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAccountSignupConfirmationWithBodyWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).UpsertAccountSignupConfirmationWithBodyWithResponse), varargs...)
	return &MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall{Call: call}
}

// MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall wrap *gomock.Call
type MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall) Return(arg0 *api.UpsertAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall) Do(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.UpsertAccountSignupConfirmationResponse, error)) *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, string, io.Reader, ...api.RequestEditorFn) (*api.UpsertAccountSignupConfirmationResponse, error)) *MockConfirmationClientUpsertAccountSignupConfirmationWithBodyWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpsertAccountSignupConfirmationWithResponse mocks base method.
func (m *MockConfirmationClient) UpsertAccountSignupConfirmationWithResponse(ctx context.Context, userId api.UserId, body api.UpsertAccountSignupConfirmationJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.UpsertAccountSignupConfirmationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpsertAccountSignupConfirmationWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpsertAccountSignupConfirmationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAccountSignupConfirmationWithResponse indicates an expected call of UpsertAccountSignupConfirmationWithResponse.
func (mr *MockConfirmationClientMockRecorder) UpsertAccountSignupConfirmationWithResponse(ctx, userId, body any, reqEditors ...any) *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAccountSignupConfirmationWithResponse", reflect.TypeOf((*MockConfirmationClient)(nil).UpsertAccountSignupConfirmationWithResponse), varargs...)
	return &MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall{Call: call}
}

// MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall wrap *gomock.Call
type MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall) Return(arg0 *api.UpsertAccountSignupConfirmationResponse, arg1 error) *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall) Do(f func(context.Context, api.UserId, api.UpsertAccountSignupConfirmationJSONRequestBody, ...api.RequestEditorFn) (*api.UpsertAccountSignupConfirmationResponse, error)) *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall) DoAndReturn(f func(context.Context, api.UserId, api.UpsertAccountSignupConfirmationJSONRequestBody, ...api.RequestEditorFn) (*api.UpsertAccountSignupConfirmationResponse, error)) *MockConfirmationClientUpsertAccountSignupConfirmationWithResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
