// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tidepool-org/platform/permission (interfaces: Client)

// Package permission is a generated GoMock package.
package permission

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetUserPermissions mocks base method.
func (m *MockClient) GetUserPermissions(arg0 context.Context, arg1, arg2 string) (Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", arg0, arg1, arg2)
	ret0, _ := ret[0].(Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockClientMockRecorder) GetUserPermissions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockClient)(nil).GetUserPermissions), arg0, arg1, arg2)
}

// GroupsForUser mocks base method.
func (m *MockClient) GroupsForUser(arg0 context.Context, arg1 string) (Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupsForUser", arg0, arg1)
	ret0, _ := ret[0].(Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupsForUser indicates an expected call of GroupsForUser.
func (mr *MockClientMockRecorder) GroupsForUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupsForUser", reflect.TypeOf((*MockClient)(nil).GroupsForUser), arg0, arg1)
}

// HasCustodianPermissions mocks base method.
func (m *MockClient) HasCustodianPermissions(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCustodianPermissions", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasCustodianPermissions indicates an expected call of HasCustodianPermissions.
func (mr *MockClientMockRecorder) HasCustodianPermissions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCustodianPermissions", reflect.TypeOf((*MockClient)(nil).HasCustodianPermissions), arg0, arg1, arg2)
}

// HasMembershipRelationship mocks base method.
func (m *MockClient) HasMembershipRelationship(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMembershipRelationship", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMembershipRelationship indicates an expected call of HasMembershipRelationship.
func (mr *MockClientMockRecorder) HasMembershipRelationship(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMembershipRelationship", reflect.TypeOf((*MockClient)(nil).HasMembershipRelationship), arg0, arg1, arg2)
}

// HasWritePermissions mocks base method.
func (m *MockClient) HasWritePermissions(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWritePermissions", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasWritePermissions indicates an expected call of HasWritePermissions.
func (mr *MockClientMockRecorder) HasWritePermissions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWritePermissions", reflect.TypeOf((*MockClient)(nil).HasWritePermissions), arg0, arg1, arg2)
}

// UsersInGroup mocks base method.
func (m *MockClient) UsersInGroup(arg0 context.Context, arg1 string) (Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersInGroup", arg0, arg1)
	ret0, _ := ret[0].(Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersInGroup indicates an expected call of UsersInGroup.
func (mr *MockClientMockRecorder) UsersInGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersInGroup", reflect.TypeOf((*MockClient)(nil).UsersInGroup), arg0, arg1)
}
