// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tidepool-org/platform/permission (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination=./client_mock.go -package=permission . Client
//

// Package permission is a generated GoMock package.
package permission

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetUserPermissions mocks base method.
func (m *MockClient) GetUserPermissions(ctx context.Context, requestUserID, targetUserID string) (Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, requestUserID, targetUserID)
	ret0, _ := ret[0].(Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockClientMockRecorder) GetUserPermissions(ctx, requestUserID, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockClient)(nil).GetUserPermissions), ctx, requestUserID, targetUserID)
}

// HasCustodianPermissions mocks base method.
func (m *MockClient) HasCustodianPermissions(ctx context.Context, granteeUserID, grantorUserID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCustodianPermissions", ctx, granteeUserID, grantorUserID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasCustodianPermissions indicates an expected call of HasCustodianPermissions.
func (mr *MockClientMockRecorder) HasCustodianPermissions(ctx, granteeUserID, grantorUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCustodianPermissions", reflect.TypeOf((*MockClient)(nil).HasCustodianPermissions), ctx, granteeUserID, grantorUserID)
}

// HasMembershipRelationship mocks base method.
func (m *MockClient) HasMembershipRelationship(ctx context.Context, granteeUserID, grantorUserID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMembershipRelationship", ctx, granteeUserID, grantorUserID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMembershipRelationship indicates an expected call of HasMembershipRelationship.
func (mr *MockClientMockRecorder) HasMembershipRelationship(ctx, granteeUserID, grantorUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMembershipRelationship", reflect.TypeOf((*MockClient)(nil).HasMembershipRelationship), ctx, granteeUserID, grantorUserID)
}

// PermissionsGrantedByUser mocks base method.
func (m *MockClient) PermissionsGrantedByUser(ctx context.Context, sharerID string) (Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionsGrantedByUser", ctx, sharerID)
	ret0, _ := ret[0].(Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermissionsGrantedByUser indicates an expected call of PermissionsGrantedByUser.
func (mr *MockClientMockRecorder) PermissionsGrantedByUser(ctx, sharerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionsGrantedByUser", reflect.TypeOf((*MockClient)(nil).PermissionsGrantedByUser), ctx, sharerID)
}

// PermissionsGrantedToUser mocks base method.
func (m *MockClient) PermissionsGrantedToUser(ctx context.Context, granteeUserID string) (Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionsGrantedToUser", ctx, granteeUserID)
	ret0, _ := ret[0].(Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermissionsGrantedToUser indicates an expected call of PermissionsGrantedToUser.
func (mr *MockClientMockRecorder) PermissionsGrantedToUser(ctx, granteeUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionsGrantedToUser", reflect.TypeOf((*MockClient)(nil).PermissionsGrantedToUser), ctx, granteeUserID)
}

// UpdateUserPermissions mocks base method.
func (m *MockClient) UpdateUserPermissions(ctx context.Context, requestUserID, targetUserID string, permissions Permissions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPermissions", ctx, requestUserID, targetUserID, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPermissions indicates an expected call of UpdateUserPermissions.
func (mr *MockClientMockRecorder) UpdateUserPermissions(ctx, requestUserID, targetUserID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPermissions", reflect.TypeOf((*MockClient)(nil).UpdateUserPermissions), ctx, requestUserID, targetUserID, permissions)
}
