// Code generated by MockGen. DO NOT EDIT.
// Source: rest.go
//
// Generated by this command:
//
//	mockgen -source=rest.go -destination=rest_mocks.go -package=rest -typed
//

// Package rest is a generated GoMock package.
package rest

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
	isgomock struct{}
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// EncodeJson mocks base method.
func (m *MockResponse) EncodeJson(v any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeJson", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncodeJson indicates an expected call of EncodeJson.
func (mr *MockResponseMockRecorder) EncodeJson(v any) *MockResponseEncodeJsonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeJson", reflect.TypeOf((*MockResponse)(nil).EncodeJson), v)
	return &MockResponseEncodeJsonCall{Call: call}
}

// MockResponseEncodeJsonCall wrap *gomock.Call
type MockResponseEncodeJsonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResponseEncodeJsonCall) Return(arg0 []byte, arg1 error) *MockResponseEncodeJsonCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResponseEncodeJsonCall) Do(f func(any) ([]byte, error)) *MockResponseEncodeJsonCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResponseEncodeJsonCall) DoAndReturn(f func(any) ([]byte, error)) *MockResponseEncodeJsonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Header mocks base method.
func (m *MockResponse) Header() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockResponseMockRecorder) Header() *MockResponseHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockResponse)(nil).Header))
	return &MockResponseHeaderCall{Call: call}
}

// MockResponseHeaderCall wrap *gomock.Call
type MockResponseHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResponseHeaderCall) Return(arg0 http.Header) *MockResponseHeaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResponseHeaderCall) Do(f func() http.Header) *MockResponseHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResponseHeaderCall) DoAndReturn(f func() http.Header) *MockResponseHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *MockResponse) Write(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockResponseMockRecorder) Write(arg0 any) *MockResponseWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockResponse)(nil).Write), arg0)
	return &MockResponseWriteCall{Call: call}
}

// MockResponseWriteCall wrap *gomock.Call
type MockResponseWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResponseWriteCall) Return(arg0 int, arg1 error) *MockResponseWriteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResponseWriteCall) Do(f func([]byte) (int, error)) *MockResponseWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResponseWriteCall) DoAndReturn(f func([]byte) (int, error)) *MockResponseWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteHeader mocks base method.
func (m *MockResponse) WriteHeader(statusCode int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteHeader", statusCode)
}

// WriteHeader indicates an expected call of WriteHeader.
func (mr *MockResponseMockRecorder) WriteHeader(statusCode any) *MockResponseWriteHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteHeader", reflect.TypeOf((*MockResponse)(nil).WriteHeader), statusCode)
	return &MockResponseWriteHeaderCall{Call: call}
}

// MockResponseWriteHeaderCall wrap *gomock.Call
type MockResponseWriteHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResponseWriteHeaderCall) Return() *MockResponseWriteHeaderCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResponseWriteHeaderCall) Do(f func(int)) *MockResponseWriteHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResponseWriteHeaderCall) DoAndReturn(f func(int)) *MockResponseWriteHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteJson mocks base method.
func (m *MockResponse) WriteJson(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJson", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJson indicates an expected call of WriteJson.
func (mr *MockResponseMockRecorder) WriteJson(v any) *MockResponseWriteJsonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJson", reflect.TypeOf((*MockResponse)(nil).WriteJson), v)
	return &MockResponseWriteJsonCall{Call: call}
}

// MockResponseWriteJsonCall wrap *gomock.Call
type MockResponseWriteJsonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResponseWriteJsonCall) Return(arg0 error) *MockResponseWriteJsonCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResponseWriteJsonCall) Do(f func(any) error) *MockResponseWriteJsonCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResponseWriteJsonCall) DoAndReturn(f func(any) error) *MockResponseWriteJsonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
