// Code generated by MockGen. DO NOT EDIT.
// Source: source.go
//
// Generated by this command:
//
//	mockgen -source=source.go -destination=test/source_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	source "github.com/tidepool-org/platform/data/source"
	page "github.com/tidepool-org/platform/page"
	request "github.com/tidepool-org/platform/request"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, userID string, create *source.Create) (*source.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, create)
	ret0, _ := ret[0].(*source.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, userID, create any) *MockClientCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, userID, create)
	return &MockClientCreateCall{Call: call}
}

// MockClientCreateCall wrap *gomock.Call
type MockClientCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateCall) Return(arg0 *source.Source, arg1 error) *MockClientCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateCall) Do(f func(context.Context, string, *source.Create) (*source.Source, error)) *MockClientCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateCall) DoAndReturn(f func(context.Context, string, *source.Create) (*source.Source, error)) *MockClientCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, id string, condition *request.Condition) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, condition)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, id, condition any) *MockClientDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), ctx, id, condition)
	return &MockClientDeleteCall{Call: call}
}

// MockClientDeleteCall wrap *gomock.Call
type MockClientDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteCall) Return(arg0 bool, arg1 error) *MockClientDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteCall) Do(f func(context.Context, string, *request.Condition) (bool, error)) *MockClientDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteCall) DoAndReturn(f func(context.Context, string, *request.Condition) (bool, error)) *MockClientDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAll mocks base method.
func (m *MockClient) DeleteAll(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockClientMockRecorder) DeleteAll(ctx, userID any) *MockClientDeleteAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockClient)(nil).DeleteAll), ctx, userID)
	return &MockClientDeleteAllCall{Call: call}
}

// MockClientDeleteAllCall wrap *gomock.Call
type MockClientDeleteAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteAllCall) Return(arg0 error) *MockClientDeleteAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteAllCall) Do(f func(context.Context, string) error) *MockClientDeleteAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteAllCall) DoAndReturn(f func(context.Context, string) error) *MockClientDeleteAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, id string) (*source.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*source.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, id any) *MockClientGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), ctx, id)
	return &MockClientGetCall{Call: call}
}

// MockClientGetCall wrap *gomock.Call
type MockClientGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetCall) Return(arg0 *source.Source, arg1 error) *MockClientGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetCall) Do(f func(context.Context, string) (*source.Source, error)) *MockClientGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetCall) DoAndReturn(f func(context.Context, string) (*source.Source, error)) *MockClientGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFromProviderSession mocks base method.
func (m *MockClient) GetFromProviderSession(ctx context.Context, providerSessionID string) (*source.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromProviderSession", ctx, providerSessionID)
	ret0, _ := ret[0].(*source.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromProviderSession indicates an expected call of GetFromProviderSession.
func (mr *MockClientMockRecorder) GetFromProviderSession(ctx, providerSessionID any) *MockClientGetFromProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromProviderSession", reflect.TypeOf((*MockClient)(nil).GetFromProviderSession), ctx, providerSessionID)
	return &MockClientGetFromProviderSessionCall{Call: call}
}

// MockClientGetFromProviderSessionCall wrap *gomock.Call
type MockClientGetFromProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetFromProviderSessionCall) Return(arg0 *source.Source, arg1 error) *MockClientGetFromProviderSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetFromProviderSessionCall) Do(f func(context.Context, string) (*source.Source, error)) *MockClientGetFromProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetFromProviderSessionCall) DoAndReturn(f func(context.Context, string) (*source.Source, error)) *MockClientGetFromProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockClient) List(ctx context.Context, userID string, filter *source.Filter, pagination *page.Pagination) (source.SourceArray, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter, pagination)
	ret0, _ := ret[0].(source.SourceArray)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientMockRecorder) List(ctx, userID, filter, pagination any) *MockClientListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClient)(nil).List), ctx, userID, filter, pagination)
	return &MockClientListCall{Call: call}
}

// MockClientListCall wrap *gomock.Call
type MockClientListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientListCall) Return(arg0 source.SourceArray, arg1 error) *MockClientListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientListCall) Do(f func(context.Context, string, *source.Filter, *page.Pagination) (source.SourceArray, error)) *MockClientListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientListCall) DoAndReturn(f func(context.Context, string, *source.Filter, *page.Pagination) (source.SourceArray, error)) *MockClientListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockClient) Update(ctx context.Context, id string, condition *request.Condition, update *source.Update) (*source.Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, condition, update)
	ret0, _ := ret[0].(*source.Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClientMockRecorder) Update(ctx, id, condition, update any) *MockClientUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClient)(nil).Update), ctx, id, condition, update)
	return &MockClientUpdateCall{Call: call}
}

// MockClientUpdateCall wrap *gomock.Call
type MockClientUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientUpdateCall) Return(arg0 *source.Source, arg1 error) *MockClientUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientUpdateCall) Do(f func(context.Context, string, *request.Condition, *source.Update) (*source.Source, error)) *MockClientUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientUpdateCall) DoAndReturn(f func(context.Context, string, *request.Condition, *source.Update) (*source.Source, error)) *MockClientUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
