// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=test/repository_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	appvalidate "github.com/tidepool-org/platform/appvalidate"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, f appvalidate.Filter) (*appvalidate.AppValidation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, f)
	ret0, _ := ret[0].(*appvalidate.AppValidation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, f any) *MockRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, f)
	return &MockRepositoryGetCall{Call: call}
}

// MockRepositoryGetCall wrap *gomock.Call
type MockRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetCall) Return(arg0 *appvalidate.AppValidation, arg1 error) *MockRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetCall) Do(f func(context.Context, appvalidate.Filter) (*appvalidate.AppValidation, error)) *MockRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetCall) DoAndReturn(f func(context.Context, appvalidate.Filter) (*appvalidate.AppValidation, error)) *MockRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAttestationChallenge mocks base method.
func (m *MockRepository) GetAttestationChallenge(ctx context.Context, f appvalidate.Filter) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttestationChallenge", ctx, f)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttestationChallenge indicates an expected call of GetAttestationChallenge.
func (mr *MockRepositoryMockRecorder) GetAttestationChallenge(ctx, f any) *MockRepositoryGetAttestationChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttestationChallenge", reflect.TypeOf((*MockRepository)(nil).GetAttestationChallenge), ctx, f)
	return &MockRepositoryGetAttestationChallengeCall{Call: call}
}

// MockRepositoryGetAttestationChallengeCall wrap *gomock.Call
type MockRepositoryGetAttestationChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetAttestationChallengeCall) Return(arg0 string, arg1 error) *MockRepositoryGetAttestationChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetAttestationChallengeCall) Do(f func(context.Context, appvalidate.Filter) (string, error)) *MockRepositoryGetAttestationChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetAttestationChallengeCall) DoAndReturn(f func(context.Context, appvalidate.Filter) (string, error)) *MockRepositoryGetAttestationChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsVerified mocks base method.
func (m *MockRepository) IsVerified(ctx context.Context, f appvalidate.Filter) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVerified", ctx, f)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsVerified indicates an expected call of IsVerified.
func (mr *MockRepositoryMockRecorder) IsVerified(ctx, f any) *MockRepositoryIsVerifiedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVerified", reflect.TypeOf((*MockRepository)(nil).IsVerified), ctx, f)
	return &MockRepositoryIsVerifiedCall{Call: call}
}

// MockRepositoryIsVerifiedCall wrap *gomock.Call
type MockRepositoryIsVerifiedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryIsVerifiedCall) Return(arg0 bool, arg1 error) *MockRepositoryIsVerifiedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryIsVerifiedCall) Do(f func(context.Context, appvalidate.Filter) (bool, error)) *MockRepositoryIsVerifiedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryIsVerifiedCall) DoAndReturn(f func(context.Context, appvalidate.Filter) (bool, error)) *MockRepositoryIsVerifiedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateAssertion mocks base method.
func (m *MockRepository) UpdateAssertion(ctx context.Context, f appvalidate.Filter, u appvalidate.AssertionUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAssertion", ctx, f, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAssertion indicates an expected call of UpdateAssertion.
func (mr *MockRepositoryMockRecorder) UpdateAssertion(ctx, f, u any) *MockRepositoryUpdateAssertionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAssertion", reflect.TypeOf((*MockRepository)(nil).UpdateAssertion), ctx, f, u)
	return &MockRepositoryUpdateAssertionCall{Call: call}
}

// MockRepositoryUpdateAssertionCall wrap *gomock.Call
type MockRepositoryUpdateAssertionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateAssertionCall) Return(arg0 error) *MockRepositoryUpdateAssertionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateAssertionCall) Do(f func(context.Context, appvalidate.Filter, appvalidate.AssertionUpdate) error) *MockRepositoryUpdateAssertionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateAssertionCall) DoAndReturn(f func(context.Context, appvalidate.Filter, appvalidate.AssertionUpdate) error) *MockRepositoryUpdateAssertionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateAttestation mocks base method.
func (m *MockRepository) UpdateAttestation(ctx context.Context, f appvalidate.Filter, u appvalidate.AttestationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttestation", ctx, f, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttestation indicates an expected call of UpdateAttestation.
func (mr *MockRepositoryMockRecorder) UpdateAttestation(ctx, f, u any) *MockRepositoryUpdateAttestationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttestation", reflect.TypeOf((*MockRepository)(nil).UpdateAttestation), ctx, f, u)
	return &MockRepositoryUpdateAttestationCall{Call: call}
}

// MockRepositoryUpdateAttestationCall wrap *gomock.Call
type MockRepositoryUpdateAttestationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateAttestationCall) Return(arg0 error) *MockRepositoryUpdateAttestationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateAttestationCall) Do(f func(context.Context, appvalidate.Filter, appvalidate.AttestationUpdate) error) *MockRepositoryUpdateAttestationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateAttestationCall) DoAndReturn(f func(context.Context, appvalidate.Filter, appvalidate.AttestationUpdate) error) *MockRepositoryUpdateAttestationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Upsert mocks base method.
func (m *MockRepository) Upsert(ctx context.Context, v *appvalidate.AppValidation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRepositoryMockRecorder) Upsert(ctx, v any) *MockRepositoryUpsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRepository)(nil).Upsert), ctx, v)
	return &MockRepositoryUpsertCall{Call: call}
}

// MockRepositoryUpsertCall wrap *gomock.Call
type MockRepositoryUpsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpsertCall) Return(arg0 error) *MockRepositoryUpsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpsertCall) Do(f func(context.Context, *appvalidate.AppValidation) error) *MockRepositoryUpsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpsertCall) DoAndReturn(f func(context.Context, *appvalidate.AppValidation) error) *MockRepositoryUpsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
