// Code generated by MockGen. DO NOT EDIT.
// Source: mixin.go
//
// Generated by this command:
//
//	mockgen -source=mixin.go -destination=test/mixin_mocks.go -package=test MixinFromWorkWithParsedMetadata
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	raw "github.com/tidepool-org/platform/data/raw"
	work "github.com/tidepool-org/platform/work"
)

// MockMixin is a mock of Mixin interface.
type MockMixin struct {
	ctrl     *gomock.Controller
	recorder *MockMixinMockRecorder
	isgomock struct{}
}

// MockMixinMockRecorder is the mock recorder for MockMixin.
type MockMixinMockRecorder struct {
	mock *MockMixin
}

// NewMockMixin creates a new mock instance.
func NewMockMixin(ctrl *gomock.Controller) *MockMixin {
	mock := &MockMixin{ctrl: ctrl}
	mock.recorder = &MockMixinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixin) EXPECT() *MockMixinMockRecorder {
	return m.recorder
}

// AddDataRawToContext mocks base method.
func (m *MockMixin) AddDataRawToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDataRawToContext")
}

// AddDataRawToContext indicates an expected call of AddDataRawToContext.
func (mr *MockMixinMockRecorder) AddDataRawToContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataRawToContext", reflect.TypeOf((*MockMixin)(nil).AddDataRawToContext))
}

// CloseDataRawContent mocks base method.
func (m *MockMixin) CloseDataRawContent() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseDataRawContent")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// CloseDataRawContent indicates an expected call of CloseDataRawContent.
func (mr *MockMixinMockRecorder) CloseDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseDataRawContent", reflect.TypeOf((*MockMixin)(nil).CloseDataRawContent))
}

// DataRaw mocks base method.
func (m *MockMixin) DataRaw() *raw.Raw {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRaw")
	ret0, _ := ret[0].(*raw.Raw)
	return ret0
}

// DataRaw indicates an expected call of DataRaw.
func (mr *MockMixinMockRecorder) DataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRaw", reflect.TypeOf((*MockMixin)(nil).DataRaw))
}

// DataRawClient mocks base method.
func (m *MockMixin) DataRawClient() raw.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawClient")
	ret0, _ := ret[0].(raw.Client)
	return ret0
}

// DataRawClient indicates an expected call of DataRawClient.
func (mr *MockMixinMockRecorder) DataRawClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawClient", reflect.TypeOf((*MockMixin)(nil).DataRawClient))
}

// DataRawContent mocks base method.
func (m *MockMixin) DataRawContent() *raw.Content {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawContent")
	ret0, _ := ret[0].(*raw.Content)
	return ret0
}

// DataRawContent indicates an expected call of DataRawContent.
func (mr *MockMixinMockRecorder) DataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawContent", reflect.TypeOf((*MockMixin)(nil).DataRawContent))
}

// FetchDataRaw mocks base method.
func (m *MockMixin) FetchDataRaw(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRaw", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRaw indicates an expected call of FetchDataRaw.
func (mr *MockMixinMockRecorder) FetchDataRaw(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRaw", reflect.TypeOf((*MockMixin)(nil).FetchDataRaw), dataRawID)
}

// FetchDataRawContent mocks base method.
func (m *MockMixin) FetchDataRawContent(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContent", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContent indicates an expected call of FetchDataRawContent.
func (mr *MockMixinMockRecorder) FetchDataRawContent(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContent", reflect.TypeOf((*MockMixin)(nil).FetchDataRawContent), dataRawID)
}

// FetchDataRawContentFromDataRaw mocks base method.
func (m *MockMixin) FetchDataRawContentFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContentFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContentFromDataRaw indicates an expected call of FetchDataRawContentFromDataRaw.
func (mr *MockMixinMockRecorder) FetchDataRawContentFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContentFromDataRaw", reflect.TypeOf((*MockMixin)(nil).FetchDataRawContentFromDataRaw))
}

// HasDataRaw mocks base method.
func (m *MockMixin) HasDataRaw() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRaw")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRaw indicates an expected call of HasDataRaw.
func (mr *MockMixinMockRecorder) HasDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRaw", reflect.TypeOf((*MockMixin)(nil).HasDataRaw))
}

// HasDataRawContent mocks base method.
func (m *MockMixin) HasDataRawContent() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawContent")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawContent indicates an expected call of HasDataRawContent.
func (mr *MockMixinMockRecorder) HasDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawContent", reflect.TypeOf((*MockMixin)(nil).HasDataRawContent))
}

// SetDataRaw mocks base method.
func (m *MockMixin) SetDataRaw(dataRaw *raw.Raw) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRaw", dataRaw)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRaw indicates an expected call of SetDataRaw.
func (mr *MockMixinMockRecorder) SetDataRaw(dataRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRaw", reflect.TypeOf((*MockMixin)(nil).SetDataRaw), dataRaw)
}

// UpdateDataRaw mocks base method.
func (m *MockMixin) UpdateDataRaw(dataRawUpdate *raw.Update) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRaw", dataRawUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRaw indicates an expected call of UpdateDataRaw.
func (mr *MockMixinMockRecorder) UpdateDataRaw(dataRawUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRaw", reflect.TypeOf((*MockMixin)(nil).UpdateDataRaw), dataRawUpdate)
}

// MockFromWork is a mock of FromWork interface.
type MockFromWork struct {
	ctrl     *gomock.Controller
	recorder *MockFromWorkMockRecorder
	isgomock struct{}
}

// MockFromWorkMockRecorder is the mock recorder for MockFromWork.
type MockFromWorkMockRecorder struct {
	mock *MockFromWork
}

// NewMockFromWork creates a new mock instance.
func NewMockFromWork(ctrl *gomock.Controller) *MockFromWork {
	mock := &MockFromWork{ctrl: ctrl}
	mock.recorder = &MockFromWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFromWork) EXPECT() *MockFromWorkMockRecorder {
	return m.recorder
}

// FetchDataRawFromWorkMetadata mocks base method.
func (m *MockFromWork) FetchDataRawFromWorkMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawFromWorkMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawFromWorkMetadata indicates an expected call of FetchDataRawFromWorkMetadata.
func (mr *MockFromWorkMockRecorder) FetchDataRawFromWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawFromWorkMetadata", reflect.TypeOf((*MockFromWork)(nil).FetchDataRawFromWorkMetadata))
}

// HasWorkMetadata mocks base method.
func (m *MockFromWork) HasWorkMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWorkMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWorkMetadata indicates an expected call of HasWorkMetadata.
func (mr *MockFromWorkMockRecorder) HasWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWorkMetadata", reflect.TypeOf((*MockFromWork)(nil).HasWorkMetadata))
}

// UpdateWorkMetadataFromDataRaw mocks base method.
func (m *MockFromWork) UpdateWorkMetadataFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkMetadataFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateWorkMetadataFromDataRaw indicates an expected call of UpdateWorkMetadataFromDataRaw.
func (mr *MockFromWorkMockRecorder) UpdateWorkMetadataFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkMetadataFromDataRaw", reflect.TypeOf((*MockFromWork)(nil).UpdateWorkMetadataFromDataRaw))
}

// MockWithParsedMetadata is a mock of WithParsedMetadata interface.
type MockWithParsedMetadata[M any] struct {
	ctrl     *gomock.Controller
	recorder *MockWithParsedMetadataMockRecorder[M]
	isgomock struct{}
}

// MockWithParsedMetadataMockRecorder is the mock recorder for MockWithParsedMetadata.
type MockWithParsedMetadataMockRecorder[M any] struct {
	mock *MockWithParsedMetadata[M]
}

// NewMockWithParsedMetadata creates a new mock instance.
func NewMockWithParsedMetadata[M any](ctrl *gomock.Controller) *MockWithParsedMetadata[M] {
	mock := &MockWithParsedMetadata[M]{ctrl: ctrl}
	mock.recorder = &MockWithParsedMetadataMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithParsedMetadata[M]) EXPECT() *MockWithParsedMetadataMockRecorder[M] {
	return m.recorder
}

// DataRawMetadata mocks base method.
func (m *MockWithParsedMetadata[M]) DataRawMetadata() *M {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawMetadata")
	ret0, _ := ret[0].(*M)
	return ret0
}

// DataRawMetadata indicates an expected call of DataRawMetadata.
func (mr *MockWithParsedMetadataMockRecorder[M]) DataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawMetadata", reflect.TypeOf((*MockWithParsedMetadata[M])(nil).DataRawMetadata))
}

// HasDataRawMetadata mocks base method.
func (m *MockWithParsedMetadata[M]) HasDataRawMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawMetadata indicates an expected call of HasDataRawMetadata.
func (mr *MockWithParsedMetadataMockRecorder[M]) HasDataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawMetadata", reflect.TypeOf((*MockWithParsedMetadata[M])(nil).HasDataRawMetadata))
}

// SetDataRawMetadata mocks base method.
func (m *MockWithParsedMetadata[M]) SetDataRawMetadata(dataRawMetadata *M) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRawMetadata", dataRawMetadata)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRawMetadata indicates an expected call of SetDataRawMetadata.
func (mr *MockWithParsedMetadataMockRecorder[M]) SetDataRawMetadata(dataRawMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRawMetadata", reflect.TypeOf((*MockWithParsedMetadata[M])(nil).SetDataRawMetadata), dataRawMetadata)
}

// UpdateDataRawMetadata mocks base method.
func (m *MockWithParsedMetadata[M]) UpdateDataRawMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRawMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRawMetadata indicates an expected call of UpdateDataRawMetadata.
func (mr *MockWithParsedMetadataMockRecorder[M]) UpdateDataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRawMetadata", reflect.TypeOf((*MockWithParsedMetadata[M])(nil).UpdateDataRawMetadata))
}

// MockMixinFromWork is a mock of MixinFromWork interface.
type MockMixinFromWork struct {
	ctrl     *gomock.Controller
	recorder *MockMixinFromWorkMockRecorder
	isgomock struct{}
}

// MockMixinFromWorkMockRecorder is the mock recorder for MockMixinFromWork.
type MockMixinFromWorkMockRecorder struct {
	mock *MockMixinFromWork
}

// NewMockMixinFromWork creates a new mock instance.
func NewMockMixinFromWork(ctrl *gomock.Controller) *MockMixinFromWork {
	mock := &MockMixinFromWork{ctrl: ctrl}
	mock.recorder = &MockMixinFromWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinFromWork) EXPECT() *MockMixinFromWorkMockRecorder {
	return m.recorder
}

// AddDataRawToContext mocks base method.
func (m *MockMixinFromWork) AddDataRawToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDataRawToContext")
}

// AddDataRawToContext indicates an expected call of AddDataRawToContext.
func (mr *MockMixinFromWorkMockRecorder) AddDataRawToContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataRawToContext", reflect.TypeOf((*MockMixinFromWork)(nil).AddDataRawToContext))
}

// CloseDataRawContent mocks base method.
func (m *MockMixinFromWork) CloseDataRawContent() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseDataRawContent")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// CloseDataRawContent indicates an expected call of CloseDataRawContent.
func (mr *MockMixinFromWorkMockRecorder) CloseDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseDataRawContent", reflect.TypeOf((*MockMixinFromWork)(nil).CloseDataRawContent))
}

// DataRaw mocks base method.
func (m *MockMixinFromWork) DataRaw() *raw.Raw {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRaw")
	ret0, _ := ret[0].(*raw.Raw)
	return ret0
}

// DataRaw indicates an expected call of DataRaw.
func (mr *MockMixinFromWorkMockRecorder) DataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).DataRaw))
}

// DataRawClient mocks base method.
func (m *MockMixinFromWork) DataRawClient() raw.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawClient")
	ret0, _ := ret[0].(raw.Client)
	return ret0
}

// DataRawClient indicates an expected call of DataRawClient.
func (mr *MockMixinFromWorkMockRecorder) DataRawClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawClient", reflect.TypeOf((*MockMixinFromWork)(nil).DataRawClient))
}

// DataRawContent mocks base method.
func (m *MockMixinFromWork) DataRawContent() *raw.Content {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawContent")
	ret0, _ := ret[0].(*raw.Content)
	return ret0
}

// DataRawContent indicates an expected call of DataRawContent.
func (mr *MockMixinFromWorkMockRecorder) DataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawContent", reflect.TypeOf((*MockMixinFromWork)(nil).DataRawContent))
}

// FetchDataRaw mocks base method.
func (m *MockMixinFromWork) FetchDataRaw(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRaw", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRaw indicates an expected call of FetchDataRaw.
func (mr *MockMixinFromWorkMockRecorder) FetchDataRaw(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).FetchDataRaw), dataRawID)
}

// FetchDataRawContent mocks base method.
func (m *MockMixinFromWork) FetchDataRawContent(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContent", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContent indicates an expected call of FetchDataRawContent.
func (mr *MockMixinFromWorkMockRecorder) FetchDataRawContent(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContent", reflect.TypeOf((*MockMixinFromWork)(nil).FetchDataRawContent), dataRawID)
}

// FetchDataRawContentFromDataRaw mocks base method.
func (m *MockMixinFromWork) FetchDataRawContentFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContentFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContentFromDataRaw indicates an expected call of FetchDataRawContentFromDataRaw.
func (mr *MockMixinFromWorkMockRecorder) FetchDataRawContentFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContentFromDataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).FetchDataRawContentFromDataRaw))
}

// FetchDataRawFromWorkMetadata mocks base method.
func (m *MockMixinFromWork) FetchDataRawFromWorkMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawFromWorkMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawFromWorkMetadata indicates an expected call of FetchDataRawFromWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) FetchDataRawFromWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawFromWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).FetchDataRawFromWorkMetadata))
}

// HasDataRaw mocks base method.
func (m *MockMixinFromWork) HasDataRaw() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRaw")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRaw indicates an expected call of HasDataRaw.
func (mr *MockMixinFromWorkMockRecorder) HasDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).HasDataRaw))
}

// HasDataRawContent mocks base method.
func (m *MockMixinFromWork) HasDataRawContent() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawContent")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawContent indicates an expected call of HasDataRawContent.
func (mr *MockMixinFromWorkMockRecorder) HasDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawContent", reflect.TypeOf((*MockMixinFromWork)(nil).HasDataRawContent))
}

// HasWorkMetadata mocks base method.
func (m *MockMixinFromWork) HasWorkMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWorkMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWorkMetadata indicates an expected call of HasWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) HasWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).HasWorkMetadata))
}

// SetDataRaw mocks base method.
func (m *MockMixinFromWork) SetDataRaw(dataRaw *raw.Raw) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRaw", dataRaw)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRaw indicates an expected call of SetDataRaw.
func (mr *MockMixinFromWorkMockRecorder) SetDataRaw(dataRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).SetDataRaw), dataRaw)
}

// UpdateDataRaw mocks base method.
func (m *MockMixinFromWork) UpdateDataRaw(dataRawUpdate *raw.Update) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRaw", dataRawUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRaw indicates an expected call of UpdateDataRaw.
func (mr *MockMixinFromWorkMockRecorder) UpdateDataRaw(dataRawUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateDataRaw), dataRawUpdate)
}

// UpdateWorkMetadataFromDataRaw mocks base method.
func (m *MockMixinFromWork) UpdateWorkMetadataFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkMetadataFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateWorkMetadataFromDataRaw indicates an expected call of UpdateWorkMetadataFromDataRaw.
func (mr *MockMixinFromWorkMockRecorder) UpdateWorkMetadataFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkMetadataFromDataRaw", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateWorkMetadataFromDataRaw))
}

// MockMixinWithParsedMetadata is a mock of MixinWithParsedMetadata interface.
type MockMixinWithParsedMetadata[M any] struct {
	ctrl     *gomock.Controller
	recorder *MockMixinWithParsedMetadataMockRecorder[M]
	isgomock struct{}
}

// MockMixinWithParsedMetadataMockRecorder is the mock recorder for MockMixinWithParsedMetadata.
type MockMixinWithParsedMetadataMockRecorder[M any] struct {
	mock *MockMixinWithParsedMetadata[M]
}

// NewMockMixinWithParsedMetadata creates a new mock instance.
func NewMockMixinWithParsedMetadata[M any](ctrl *gomock.Controller) *MockMixinWithParsedMetadata[M] {
	mock := &MockMixinWithParsedMetadata[M]{ctrl: ctrl}
	mock.recorder = &MockMixinWithParsedMetadataMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinWithParsedMetadata[M]) EXPECT() *MockMixinWithParsedMetadataMockRecorder[M] {
	return m.recorder
}

// AddDataRawToContext mocks base method.
func (m *MockMixinWithParsedMetadata[M]) AddDataRawToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDataRawToContext")
}

// AddDataRawToContext indicates an expected call of AddDataRawToContext.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) AddDataRawToContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataRawToContext", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).AddDataRawToContext))
}

// CloseDataRawContent mocks base method.
func (m *MockMixinWithParsedMetadata[M]) CloseDataRawContent() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseDataRawContent")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// CloseDataRawContent indicates an expected call of CloseDataRawContent.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) CloseDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseDataRawContent", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).CloseDataRawContent))
}

// DataRaw mocks base method.
func (m *MockMixinWithParsedMetadata[M]) DataRaw() *raw.Raw {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRaw")
	ret0, _ := ret[0].(*raw.Raw)
	return ret0
}

// DataRaw indicates an expected call of DataRaw.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) DataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRaw", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).DataRaw))
}

// DataRawClient mocks base method.
func (m *MockMixinWithParsedMetadata[M]) DataRawClient() raw.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawClient")
	ret0, _ := ret[0].(raw.Client)
	return ret0
}

// DataRawClient indicates an expected call of DataRawClient.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) DataRawClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawClient", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).DataRawClient))
}

// DataRawContent mocks base method.
func (m *MockMixinWithParsedMetadata[M]) DataRawContent() *raw.Content {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawContent")
	ret0, _ := ret[0].(*raw.Content)
	return ret0
}

// DataRawContent indicates an expected call of DataRawContent.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) DataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawContent", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).DataRawContent))
}

// DataRawMetadata mocks base method.
func (m *MockMixinWithParsedMetadata[M]) DataRawMetadata() *M {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawMetadata")
	ret0, _ := ret[0].(*M)
	return ret0
}

// DataRawMetadata indicates an expected call of DataRawMetadata.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) DataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawMetadata", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).DataRawMetadata))
}

// FetchDataRaw mocks base method.
func (m *MockMixinWithParsedMetadata[M]) FetchDataRaw(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRaw", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRaw indicates an expected call of FetchDataRaw.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) FetchDataRaw(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRaw", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).FetchDataRaw), dataRawID)
}

// FetchDataRawContent mocks base method.
func (m *MockMixinWithParsedMetadata[M]) FetchDataRawContent(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContent", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContent indicates an expected call of FetchDataRawContent.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) FetchDataRawContent(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContent", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).FetchDataRawContent), dataRawID)
}

// FetchDataRawContentFromDataRaw mocks base method.
func (m *MockMixinWithParsedMetadata[M]) FetchDataRawContentFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContentFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContentFromDataRaw indicates an expected call of FetchDataRawContentFromDataRaw.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) FetchDataRawContentFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContentFromDataRaw", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).FetchDataRawContentFromDataRaw))
}

// HasDataRaw mocks base method.
func (m *MockMixinWithParsedMetadata[M]) HasDataRaw() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRaw")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRaw indicates an expected call of HasDataRaw.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) HasDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRaw", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).HasDataRaw))
}

// HasDataRawContent mocks base method.
func (m *MockMixinWithParsedMetadata[M]) HasDataRawContent() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawContent")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawContent indicates an expected call of HasDataRawContent.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) HasDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawContent", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).HasDataRawContent))
}

// HasDataRawMetadata mocks base method.
func (m *MockMixinWithParsedMetadata[M]) HasDataRawMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawMetadata indicates an expected call of HasDataRawMetadata.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) HasDataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawMetadata", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).HasDataRawMetadata))
}

// SetDataRaw mocks base method.
func (m *MockMixinWithParsedMetadata[M]) SetDataRaw(dataRaw *raw.Raw) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRaw", dataRaw)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRaw indicates an expected call of SetDataRaw.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) SetDataRaw(dataRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRaw", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).SetDataRaw), dataRaw)
}

// SetDataRawMetadata mocks base method.
func (m *MockMixinWithParsedMetadata[M]) SetDataRawMetadata(dataRawMetadata *M) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRawMetadata", dataRawMetadata)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRawMetadata indicates an expected call of SetDataRawMetadata.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) SetDataRawMetadata(dataRawMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRawMetadata", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).SetDataRawMetadata), dataRawMetadata)
}

// UpdateDataRaw mocks base method.
func (m *MockMixinWithParsedMetadata[M]) UpdateDataRaw(dataRawUpdate *raw.Update) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRaw", dataRawUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRaw indicates an expected call of UpdateDataRaw.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) UpdateDataRaw(dataRawUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRaw", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).UpdateDataRaw), dataRawUpdate)
}

// UpdateDataRawMetadata mocks base method.
func (m *MockMixinWithParsedMetadata[M]) UpdateDataRawMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRawMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRawMetadata indicates an expected call of UpdateDataRawMetadata.
func (mr *MockMixinWithParsedMetadataMockRecorder[M]) UpdateDataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRawMetadata", reflect.TypeOf((*MockMixinWithParsedMetadata[M])(nil).UpdateDataRawMetadata))
}

// MockMixinFromWorkWithParsedMetadata is a mock of MixinFromWorkWithParsedMetadata interface.
type MockMixinFromWorkWithParsedMetadata[M any] struct {
	ctrl     *gomock.Controller
	recorder *MockMixinFromWorkWithParsedMetadataMockRecorder[M]
	isgomock struct{}
}

// MockMixinFromWorkWithParsedMetadataMockRecorder is the mock recorder for MockMixinFromWorkWithParsedMetadata.
type MockMixinFromWorkWithParsedMetadataMockRecorder[M any] struct {
	mock *MockMixinFromWorkWithParsedMetadata[M]
}

// NewMockMixinFromWorkWithParsedMetadata creates a new mock instance.
func NewMockMixinFromWorkWithParsedMetadata[M any](ctrl *gomock.Controller) *MockMixinFromWorkWithParsedMetadata[M] {
	mock := &MockMixinFromWorkWithParsedMetadata[M]{ctrl: ctrl}
	mock.recorder = &MockMixinFromWorkWithParsedMetadataMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinFromWorkWithParsedMetadata[M]) EXPECT() *MockMixinFromWorkWithParsedMetadataMockRecorder[M] {
	return m.recorder
}

// AddDataRawToContext mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) AddDataRawToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDataRawToContext")
}

// AddDataRawToContext indicates an expected call of AddDataRawToContext.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) AddDataRawToContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataRawToContext", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).AddDataRawToContext))
}

// CloseDataRawContent mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) CloseDataRawContent() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseDataRawContent")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// CloseDataRawContent indicates an expected call of CloseDataRawContent.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) CloseDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseDataRawContent", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).CloseDataRawContent))
}

// DataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) DataRaw() *raw.Raw {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRaw")
	ret0, _ := ret[0].(*raw.Raw)
	return ret0
}

// DataRaw indicates an expected call of DataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) DataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).DataRaw))
}

// DataRawClient mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) DataRawClient() raw.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawClient")
	ret0, _ := ret[0].(raw.Client)
	return ret0
}

// DataRawClient indicates an expected call of DataRawClient.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) DataRawClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawClient", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).DataRawClient))
}

// DataRawContent mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) DataRawContent() *raw.Content {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawContent")
	ret0, _ := ret[0].(*raw.Content)
	return ret0
}

// DataRawContent indicates an expected call of DataRawContent.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) DataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawContent", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).DataRawContent))
}

// DataRawMetadata mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) DataRawMetadata() *M {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawMetadata")
	ret0, _ := ret[0].(*M)
	return ret0
}

// DataRawMetadata indicates an expected call of DataRawMetadata.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) DataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawMetadata", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).DataRawMetadata))
}

// FetchDataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) FetchDataRaw(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRaw", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRaw indicates an expected call of FetchDataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) FetchDataRaw(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).FetchDataRaw), dataRawID)
}

// FetchDataRawContent mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) FetchDataRawContent(dataRawID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContent", dataRawID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContent indicates an expected call of FetchDataRawContent.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) FetchDataRawContent(dataRawID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContent", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).FetchDataRawContent), dataRawID)
}

// FetchDataRawContentFromDataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) FetchDataRawContentFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawContentFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawContentFromDataRaw indicates an expected call of FetchDataRawContentFromDataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) FetchDataRawContentFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawContentFromDataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).FetchDataRawContentFromDataRaw))
}

// FetchDataRawFromWorkMetadata mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) FetchDataRawFromWorkMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataRawFromWorkMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataRawFromWorkMetadata indicates an expected call of FetchDataRawFromWorkMetadata.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) FetchDataRawFromWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataRawFromWorkMetadata", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).FetchDataRawFromWorkMetadata))
}

// HasDataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) HasDataRaw() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRaw")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRaw indicates an expected call of HasDataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) HasDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).HasDataRaw))
}

// HasDataRawContent mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) HasDataRawContent() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawContent")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawContent indicates an expected call of HasDataRawContent.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) HasDataRawContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawContent", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).HasDataRawContent))
}

// HasDataRawMetadata mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) HasDataRawMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataRawMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataRawMetadata indicates an expected call of HasDataRawMetadata.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) HasDataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataRawMetadata", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).HasDataRawMetadata))
}

// HasWorkMetadata mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) HasWorkMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWorkMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWorkMetadata indicates an expected call of HasWorkMetadata.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) HasWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWorkMetadata", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).HasWorkMetadata))
}

// SetDataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) SetDataRaw(dataRaw *raw.Raw) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRaw", dataRaw)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRaw indicates an expected call of SetDataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) SetDataRaw(dataRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).SetDataRaw), dataRaw)
}

// SetDataRawMetadata mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) SetDataRawMetadata(dataRawMetadata *M) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataRawMetadata", dataRawMetadata)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataRawMetadata indicates an expected call of SetDataRawMetadata.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) SetDataRawMetadata(dataRawMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataRawMetadata", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).SetDataRawMetadata), dataRawMetadata)
}

// UpdateDataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) UpdateDataRaw(dataRawUpdate *raw.Update) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRaw", dataRawUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRaw indicates an expected call of UpdateDataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) UpdateDataRaw(dataRawUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).UpdateDataRaw), dataRawUpdate)
}

// UpdateDataRawMetadata mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) UpdateDataRawMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataRawMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataRawMetadata indicates an expected call of UpdateDataRawMetadata.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) UpdateDataRawMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataRawMetadata", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).UpdateDataRawMetadata))
}

// UpdateWorkMetadataFromDataRaw mocks base method.
func (m *MockMixinFromWorkWithParsedMetadata[M]) UpdateWorkMetadataFromDataRaw() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkMetadataFromDataRaw")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateWorkMetadataFromDataRaw indicates an expected call of UpdateWorkMetadataFromDataRaw.
func (mr *MockMixinFromWorkWithParsedMetadataMockRecorder[M]) UpdateWorkMetadataFromDataRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkMetadataFromDataRaw", reflect.TypeOf((*MockMixinFromWorkWithParsedMetadata[M])(nil).UpdateWorkMetadataFromDataRaw))
}
