// Code generated by MockGen. DO NOT EDIT.
// Source: mixin.go
//
// Generated by this command:
//
//	mockgen -source=mixin.go -destination=test/mixin_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	auth "github.com/tidepool-org/platform/auth"
	providersession "github.com/tidepool-org/platform/auth/providersession"
	work "github.com/tidepool-org/platform/work"
)

// MockMixin is a mock of Mixin interface.
type MockMixin struct {
	ctrl     *gomock.Controller
	recorder *MockMixinMockRecorder
	isgomock struct{}
}

// MockMixinMockRecorder is the mock recorder for MockMixin.
type MockMixinMockRecorder struct {
	mock *MockMixin
}

// NewMockMixin creates a new mock instance.
func NewMockMixin(ctrl *gomock.Controller) *MockMixin {
	mock := &MockMixin{ctrl: ctrl}
	mock.recorder = &MockMixinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixin) EXPECT() *MockMixinMockRecorder {
	return m.recorder
}

// AddProviderSessionToContext mocks base method.
func (m *MockMixin) AddProviderSessionToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProviderSessionToContext")
}

// AddProviderSessionToContext indicates an expected call of AddProviderSessionToContext.
func (mr *MockMixinMockRecorder) AddProviderSessionToContext() *MockMixinAddProviderSessionToContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProviderSessionToContext", reflect.TypeOf((*MockMixin)(nil).AddProviderSessionToContext))
	return &MockMixinAddProviderSessionToContextCall{Call: call}
}

// MockMixinAddProviderSessionToContextCall wrap *gomock.Call
type MockMixinAddProviderSessionToContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinAddProviderSessionToContextCall) Return() *MockMixinAddProviderSessionToContextCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinAddProviderSessionToContextCall) Do(f func()) *MockMixinAddProviderSessionToContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinAddProviderSessionToContextCall) DoAndReturn(f func()) *MockMixinAddProviderSessionToContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchProviderSession mocks base method.
func (m *MockMixin) FetchProviderSession(providerSessionID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProviderSession", providerSessionID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchProviderSession indicates an expected call of FetchProviderSession.
func (mr *MockMixinMockRecorder) FetchProviderSession(providerSessionID any) *MockMixinFetchProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProviderSession", reflect.TypeOf((*MockMixin)(nil).FetchProviderSession), providerSessionID)
	return &MockMixinFetchProviderSessionCall{Call: call}
}

// MockMixinFetchProviderSessionCall wrap *gomock.Call
type MockMixinFetchProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFetchProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinFetchProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFetchProviderSessionCall) Do(f func(string) *work.ProcessResult) *MockMixinFetchProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFetchProviderSessionCall) DoAndReturn(f func(string) *work.ProcessResult) *MockMixinFetchProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasProviderSession mocks base method.
func (m *MockMixin) HasProviderSession() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProviderSession")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProviderSession indicates an expected call of HasProviderSession.
func (mr *MockMixinMockRecorder) HasProviderSession() *MockMixinHasProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProviderSession", reflect.TypeOf((*MockMixin)(nil).HasProviderSession))
	return &MockMixinHasProviderSessionCall{Call: call}
}

// MockMixinHasProviderSessionCall wrap *gomock.Call
type MockMixinHasProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinHasProviderSessionCall) Return(arg0 bool) *MockMixinHasProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinHasProviderSessionCall) Do(f func() bool) *MockMixinHasProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinHasProviderSessionCall) DoAndReturn(f func() bool) *MockMixinHasProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProviderSession mocks base method.
func (m *MockMixin) ProviderSession() *auth.ProviderSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSession")
	ret0, _ := ret[0].(*auth.ProviderSession)
	return ret0
}

// ProviderSession indicates an expected call of ProviderSession.
func (mr *MockMixinMockRecorder) ProviderSession() *MockMixinProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSession", reflect.TypeOf((*MockMixin)(nil).ProviderSession))
	return &MockMixinProviderSessionCall{Call: call}
}

// MockMixinProviderSessionCall wrap *gomock.Call
type MockMixinProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinProviderSessionCall) Return(arg0 *auth.ProviderSession) *MockMixinProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinProviderSessionCall) Do(f func() *auth.ProviderSession) *MockMixinProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinProviderSessionCall) DoAndReturn(f func() *auth.ProviderSession) *MockMixinProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProviderSessionClient mocks base method.
func (m *MockMixin) ProviderSessionClient() providersession.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSessionClient")
	ret0, _ := ret[0].(providersession.Client)
	return ret0
}

// ProviderSessionClient indicates an expected call of ProviderSessionClient.
func (mr *MockMixinMockRecorder) ProviderSessionClient() *MockMixinProviderSessionClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSessionClient", reflect.TypeOf((*MockMixin)(nil).ProviderSessionClient))
	return &MockMixinProviderSessionClientCall{Call: call}
}

// MockMixinProviderSessionClientCall wrap *gomock.Call
type MockMixinProviderSessionClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinProviderSessionClientCall) Return(arg0 providersession.Client) *MockMixinProviderSessionClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinProviderSessionClientCall) Do(f func() providersession.Client) *MockMixinProviderSessionClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinProviderSessionClientCall) DoAndReturn(f func() providersession.Client) *MockMixinProviderSessionClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetProviderSession mocks base method.
func (m *MockMixin) SetProviderSession(providerSession *auth.ProviderSession) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderSession", providerSession)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetProviderSession indicates an expected call of SetProviderSession.
func (mr *MockMixinMockRecorder) SetProviderSession(providerSession any) *MockMixinSetProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderSession", reflect.TypeOf((*MockMixin)(nil).SetProviderSession), providerSession)
	return &MockMixinSetProviderSessionCall{Call: call}
}

// MockMixinSetProviderSessionCall wrap *gomock.Call
type MockMixinSetProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinSetProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinSetProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinSetProviderSessionCall) Do(f func(*auth.ProviderSession) *work.ProcessResult) *MockMixinSetProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinSetProviderSessionCall) DoAndReturn(f func(*auth.ProviderSession) *work.ProcessResult) *MockMixinSetProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProviderSession mocks base method.
func (m *MockMixin) UpdateProviderSession(providerSessionUpdate *auth.ProviderSessionUpdate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderSession", providerSessionUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateProviderSession indicates an expected call of UpdateProviderSession.
func (mr *MockMixinMockRecorder) UpdateProviderSession(providerSessionUpdate any) *MockMixinUpdateProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderSession", reflect.TypeOf((*MockMixin)(nil).UpdateProviderSession), providerSessionUpdate)
	return &MockMixinUpdateProviderSessionCall{Call: call}
}

// MockMixinUpdateProviderSessionCall wrap *gomock.Call
type MockMixinUpdateProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinUpdateProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinUpdateProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinUpdateProviderSessionCall) Do(f func(*auth.ProviderSessionUpdate) *work.ProcessResult) *MockMixinUpdateProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinUpdateProviderSessionCall) DoAndReturn(f func(*auth.ProviderSessionUpdate) *work.ProcessResult) *MockMixinUpdateProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMixinFromWork is a mock of MixinFromWork interface.
type MockMixinFromWork struct {
	ctrl     *gomock.Controller
	recorder *MockMixinFromWorkMockRecorder
	isgomock struct{}
}

// MockMixinFromWorkMockRecorder is the mock recorder for MockMixinFromWork.
type MockMixinFromWorkMockRecorder struct {
	mock *MockMixinFromWork
}

// NewMockMixinFromWork creates a new mock instance.
func NewMockMixinFromWork(ctrl *gomock.Controller) *MockMixinFromWork {
	mock := &MockMixinFromWork{ctrl: ctrl}
	mock.recorder = &MockMixinFromWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinFromWork) EXPECT() *MockMixinFromWorkMockRecorder {
	return m.recorder
}

// AddProviderSessionToContext mocks base method.
func (m *MockMixinFromWork) AddProviderSessionToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProviderSessionToContext")
}

// AddProviderSessionToContext indicates an expected call of AddProviderSessionToContext.
func (mr *MockMixinFromWorkMockRecorder) AddProviderSessionToContext() *MockMixinFromWorkAddProviderSessionToContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProviderSessionToContext", reflect.TypeOf((*MockMixinFromWork)(nil).AddProviderSessionToContext))
	return &MockMixinFromWorkAddProviderSessionToContextCall{Call: call}
}

// MockMixinFromWorkAddProviderSessionToContextCall wrap *gomock.Call
type MockMixinFromWorkAddProviderSessionToContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkAddProviderSessionToContextCall) Return() *MockMixinFromWorkAddProviderSessionToContextCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkAddProviderSessionToContextCall) Do(f func()) *MockMixinFromWorkAddProviderSessionToContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkAddProviderSessionToContextCall) DoAndReturn(f func()) *MockMixinFromWorkAddProviderSessionToContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchProviderSession mocks base method.
func (m *MockMixinFromWork) FetchProviderSession(providerSessionID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProviderSession", providerSessionID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchProviderSession indicates an expected call of FetchProviderSession.
func (mr *MockMixinFromWorkMockRecorder) FetchProviderSession(providerSessionID any) *MockMixinFromWorkFetchProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).FetchProviderSession), providerSessionID)
	return &MockMixinFromWorkFetchProviderSessionCall{Call: call}
}

// MockMixinFromWorkFetchProviderSessionCall wrap *gomock.Call
type MockMixinFromWorkFetchProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkFetchProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkFetchProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkFetchProviderSessionCall) Do(f func(string) *work.ProcessResult) *MockMixinFromWorkFetchProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkFetchProviderSessionCall) DoAndReturn(f func(string) *work.ProcessResult) *MockMixinFromWorkFetchProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchProviderSessionFromWorkMetadata mocks base method.
func (m *MockMixinFromWork) FetchProviderSessionFromWorkMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProviderSessionFromWorkMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchProviderSessionFromWorkMetadata indicates an expected call of FetchProviderSessionFromWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) FetchProviderSessionFromWorkMetadata() *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProviderSessionFromWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).FetchProviderSessionFromWorkMetadata))
	return &MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall{Call: call}
}

// MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall wrap *gomock.Call
type MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall) Do(f func() *work.ProcessResult) *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall) DoAndReturn(f func() *work.ProcessResult) *MockMixinFromWorkFetchProviderSessionFromWorkMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasProviderSession mocks base method.
func (m *MockMixinFromWork) HasProviderSession() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProviderSession")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProviderSession indicates an expected call of HasProviderSession.
func (mr *MockMixinFromWorkMockRecorder) HasProviderSession() *MockMixinFromWorkHasProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).HasProviderSession))
	return &MockMixinFromWorkHasProviderSessionCall{Call: call}
}

// MockMixinFromWorkHasProviderSessionCall wrap *gomock.Call
type MockMixinFromWorkHasProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkHasProviderSessionCall) Return(arg0 bool) *MockMixinFromWorkHasProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkHasProviderSessionCall) Do(f func() bool) *MockMixinFromWorkHasProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkHasProviderSessionCall) DoAndReturn(f func() bool) *MockMixinFromWorkHasProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasWorkMetadata mocks base method.
func (m *MockMixinFromWork) HasWorkMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWorkMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWorkMetadata indicates an expected call of HasWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) HasWorkMetadata() *MockMixinFromWorkHasWorkMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).HasWorkMetadata))
	return &MockMixinFromWorkHasWorkMetadataCall{Call: call}
}

// MockMixinFromWorkHasWorkMetadataCall wrap *gomock.Call
type MockMixinFromWorkHasWorkMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkHasWorkMetadataCall) Return(arg0 bool) *MockMixinFromWorkHasWorkMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkHasWorkMetadataCall) Do(f func() bool) *MockMixinFromWorkHasWorkMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkHasWorkMetadataCall) DoAndReturn(f func() bool) *MockMixinFromWorkHasWorkMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProviderSession mocks base method.
func (m *MockMixinFromWork) ProviderSession() *auth.ProviderSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSession")
	ret0, _ := ret[0].(*auth.ProviderSession)
	return ret0
}

// ProviderSession indicates an expected call of ProviderSession.
func (mr *MockMixinFromWorkMockRecorder) ProviderSession() *MockMixinFromWorkProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).ProviderSession))
	return &MockMixinFromWorkProviderSessionCall{Call: call}
}

// MockMixinFromWorkProviderSessionCall wrap *gomock.Call
type MockMixinFromWorkProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkProviderSessionCall) Return(arg0 *auth.ProviderSession) *MockMixinFromWorkProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkProviderSessionCall) Do(f func() *auth.ProviderSession) *MockMixinFromWorkProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkProviderSessionCall) DoAndReturn(f func() *auth.ProviderSession) *MockMixinFromWorkProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProviderSessionClient mocks base method.
func (m *MockMixinFromWork) ProviderSessionClient() providersession.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSessionClient")
	ret0, _ := ret[0].(providersession.Client)
	return ret0
}

// ProviderSessionClient indicates an expected call of ProviderSessionClient.
func (mr *MockMixinFromWorkMockRecorder) ProviderSessionClient() *MockMixinFromWorkProviderSessionClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSessionClient", reflect.TypeOf((*MockMixinFromWork)(nil).ProviderSessionClient))
	return &MockMixinFromWorkProviderSessionClientCall{Call: call}
}

// MockMixinFromWorkProviderSessionClientCall wrap *gomock.Call
type MockMixinFromWorkProviderSessionClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkProviderSessionClientCall) Return(arg0 providersession.Client) *MockMixinFromWorkProviderSessionClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkProviderSessionClientCall) Do(f func() providersession.Client) *MockMixinFromWorkProviderSessionClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkProviderSessionClientCall) DoAndReturn(f func() providersession.Client) *MockMixinFromWorkProviderSessionClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetProviderSession mocks base method.
func (m *MockMixinFromWork) SetProviderSession(providerSession *auth.ProviderSession) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderSession", providerSession)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetProviderSession indicates an expected call of SetProviderSession.
func (mr *MockMixinFromWorkMockRecorder) SetProviderSession(providerSession any) *MockMixinFromWorkSetProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).SetProviderSession), providerSession)
	return &MockMixinFromWorkSetProviderSessionCall{Call: call}
}

// MockMixinFromWorkSetProviderSessionCall wrap *gomock.Call
type MockMixinFromWorkSetProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkSetProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkSetProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkSetProviderSessionCall) Do(f func(*auth.ProviderSession) *work.ProcessResult) *MockMixinFromWorkSetProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkSetProviderSessionCall) DoAndReturn(f func(*auth.ProviderSession) *work.ProcessResult) *MockMixinFromWorkSetProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProviderSession mocks base method.
func (m *MockMixinFromWork) UpdateProviderSession(providerSessionUpdate *auth.ProviderSessionUpdate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderSession", providerSessionUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateProviderSession indicates an expected call of UpdateProviderSession.
func (mr *MockMixinFromWorkMockRecorder) UpdateProviderSession(providerSessionUpdate any) *MockMixinFromWorkUpdateProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateProviderSession), providerSessionUpdate)
	return &MockMixinFromWorkUpdateProviderSessionCall{Call: call}
}

// MockMixinFromWorkUpdateProviderSessionCall wrap *gomock.Call
type MockMixinFromWorkUpdateProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkUpdateProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkUpdateProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkUpdateProviderSessionCall) Do(f func(*auth.ProviderSessionUpdate) *work.ProcessResult) *MockMixinFromWorkUpdateProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkUpdateProviderSessionCall) DoAndReturn(f func(*auth.ProviderSessionUpdate) *work.ProcessResult) *MockMixinFromWorkUpdateProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateWorkMetadataFromProviderSession mocks base method.
func (m *MockMixinFromWork) UpdateWorkMetadataFromProviderSession() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkMetadataFromProviderSession")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateWorkMetadataFromProviderSession indicates an expected call of UpdateWorkMetadataFromProviderSession.
func (mr *MockMixinFromWorkMockRecorder) UpdateWorkMetadataFromProviderSession() *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkMetadataFromProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateWorkMetadataFromProviderSession))
	return &MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall{Call: call}
}

// MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall wrap *gomock.Call
type MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall) Do(f func() *work.ProcessResult) *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall) DoAndReturn(f func() *work.ProcessResult) *MockMixinFromWorkUpdateWorkMetadataFromProviderSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
