// Code generated by MockGen. DO NOT EDIT.
// Source: mixin.go
//
// Generated by this command:
//
//	mockgen -source=mixin.go -destination=test/mixin_mocks.go -package=test MixinFromWork
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	auth "github.com/tidepool-org/platform/auth"
	providersession "github.com/tidepool-org/platform/auth/providersession"
	work "github.com/tidepool-org/platform/work"
)

// MockMixin is a mock of Mixin interface.
type MockMixin struct {
	ctrl     *gomock.Controller
	recorder *MockMixinMockRecorder
	isgomock struct{}
}

// MockMixinMockRecorder is the mock recorder for MockMixin.
type MockMixinMockRecorder struct {
	mock *MockMixin
}

// NewMockMixin creates a new mock instance.
func NewMockMixin(ctrl *gomock.Controller) *MockMixin {
	mock := &MockMixin{ctrl: ctrl}
	mock.recorder = &MockMixinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixin) EXPECT() *MockMixinMockRecorder {
	return m.recorder
}

// AddProviderSessionToContext mocks base method.
func (m *MockMixin) AddProviderSessionToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProviderSessionToContext")
}

// AddProviderSessionToContext indicates an expected call of AddProviderSessionToContext.
func (mr *MockMixinMockRecorder) AddProviderSessionToContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProviderSessionToContext", reflect.TypeOf((*MockMixin)(nil).AddProviderSessionToContext))
}

// FetchProviderSession mocks base method.
func (m *MockMixin) FetchProviderSession(providerSessionID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProviderSession", providerSessionID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchProviderSession indicates an expected call of FetchProviderSession.
func (mr *MockMixinMockRecorder) FetchProviderSession(providerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProviderSession", reflect.TypeOf((*MockMixin)(nil).FetchProviderSession), providerSessionID)
}

// HasProviderSession mocks base method.
func (m *MockMixin) HasProviderSession() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProviderSession")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProviderSession indicates an expected call of HasProviderSession.
func (mr *MockMixinMockRecorder) HasProviderSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProviderSession", reflect.TypeOf((*MockMixin)(nil).HasProviderSession))
}

// ProviderSession mocks base method.
func (m *MockMixin) ProviderSession() *auth.ProviderSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSession")
	ret0, _ := ret[0].(*auth.ProviderSession)
	return ret0
}

// ProviderSession indicates an expected call of ProviderSession.
func (mr *MockMixinMockRecorder) ProviderSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSession", reflect.TypeOf((*MockMixin)(nil).ProviderSession))
}

// ProviderSessionClient mocks base method.
func (m *MockMixin) ProviderSessionClient() providersession.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSessionClient")
	ret0, _ := ret[0].(providersession.Client)
	return ret0
}

// ProviderSessionClient indicates an expected call of ProviderSessionClient.
func (mr *MockMixinMockRecorder) ProviderSessionClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSessionClient", reflect.TypeOf((*MockMixin)(nil).ProviderSessionClient))
}

// SetProviderSession mocks base method.
func (m *MockMixin) SetProviderSession(providerSession *auth.ProviderSession) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderSession", providerSession)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetProviderSession indicates an expected call of SetProviderSession.
func (mr *MockMixinMockRecorder) SetProviderSession(providerSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderSession", reflect.TypeOf((*MockMixin)(nil).SetProviderSession), providerSession)
}

// UpdateProviderSession mocks base method.
func (m *MockMixin) UpdateProviderSession(providerSessionUpdate *auth.ProviderSessionUpdate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderSession", providerSessionUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateProviderSession indicates an expected call of UpdateProviderSession.
func (mr *MockMixinMockRecorder) UpdateProviderSession(providerSessionUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderSession", reflect.TypeOf((*MockMixin)(nil).UpdateProviderSession), providerSessionUpdate)
}

// MockMixinFromWork is a mock of MixinFromWork interface.
type MockMixinFromWork struct {
	ctrl     *gomock.Controller
	recorder *MockMixinFromWorkMockRecorder
	isgomock struct{}
}

// MockMixinFromWorkMockRecorder is the mock recorder for MockMixinFromWork.
type MockMixinFromWorkMockRecorder struct {
	mock *MockMixinFromWork
}

// NewMockMixinFromWork creates a new mock instance.
func NewMockMixinFromWork(ctrl *gomock.Controller) *MockMixinFromWork {
	mock := &MockMixinFromWork{ctrl: ctrl}
	mock.recorder = &MockMixinFromWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinFromWork) EXPECT() *MockMixinFromWorkMockRecorder {
	return m.recorder
}

// AddProviderSessionToContext mocks base method.
func (m *MockMixinFromWork) AddProviderSessionToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProviderSessionToContext")
}

// AddProviderSessionToContext indicates an expected call of AddProviderSessionToContext.
func (mr *MockMixinFromWorkMockRecorder) AddProviderSessionToContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProviderSessionToContext", reflect.TypeOf((*MockMixinFromWork)(nil).AddProviderSessionToContext))
}

// FetchProviderSession mocks base method.
func (m *MockMixinFromWork) FetchProviderSession(providerSessionID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProviderSession", providerSessionID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchProviderSession indicates an expected call of FetchProviderSession.
func (mr *MockMixinFromWorkMockRecorder) FetchProviderSession(providerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).FetchProviderSession), providerSessionID)
}

// FetchProviderSessionFromWorkMetadata mocks base method.
func (m *MockMixinFromWork) FetchProviderSessionFromWorkMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProviderSessionFromWorkMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchProviderSessionFromWorkMetadata indicates an expected call of FetchProviderSessionFromWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) FetchProviderSessionFromWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProviderSessionFromWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).FetchProviderSessionFromWorkMetadata))
}

// HasProviderSession mocks base method.
func (m *MockMixinFromWork) HasProviderSession() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProviderSession")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProviderSession indicates an expected call of HasProviderSession.
func (mr *MockMixinFromWorkMockRecorder) HasProviderSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).HasProviderSession))
}

// HasWorkMetadata mocks base method.
func (m *MockMixinFromWork) HasWorkMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWorkMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWorkMetadata indicates an expected call of HasWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) HasWorkMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).HasWorkMetadata))
}

// ProviderSession mocks base method.
func (m *MockMixinFromWork) ProviderSession() *auth.ProviderSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSession")
	ret0, _ := ret[0].(*auth.ProviderSession)
	return ret0
}

// ProviderSession indicates an expected call of ProviderSession.
func (mr *MockMixinFromWorkMockRecorder) ProviderSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).ProviderSession))
}

// ProviderSessionClient mocks base method.
func (m *MockMixinFromWork) ProviderSessionClient() providersession.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderSessionClient")
	ret0, _ := ret[0].(providersession.Client)
	return ret0
}

// ProviderSessionClient indicates an expected call of ProviderSessionClient.
func (mr *MockMixinFromWorkMockRecorder) ProviderSessionClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderSessionClient", reflect.TypeOf((*MockMixinFromWork)(nil).ProviderSessionClient))
}

// SetProviderSession mocks base method.
func (m *MockMixinFromWork) SetProviderSession(providerSession *auth.ProviderSession) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderSession", providerSession)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetProviderSession indicates an expected call of SetProviderSession.
func (mr *MockMixinFromWorkMockRecorder) SetProviderSession(providerSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).SetProviderSession), providerSession)
}

// UpdateProviderSession mocks base method.
func (m *MockMixinFromWork) UpdateProviderSession(providerSessionUpdate *auth.ProviderSessionUpdate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderSession", providerSessionUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateProviderSession indicates an expected call of UpdateProviderSession.
func (mr *MockMixinFromWorkMockRecorder) UpdateProviderSession(providerSessionUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateProviderSession), providerSessionUpdate)
}

// UpdateWorkMetadataFromProviderSession mocks base method.
func (m *MockMixinFromWork) UpdateWorkMetadataFromProviderSession() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkMetadataFromProviderSession")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateWorkMetadataFromProviderSession indicates an expected call of UpdateWorkMetadataFromProviderSession.
func (mr *MockMixinFromWorkMockRecorder) UpdateWorkMetadataFromProviderSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkMetadataFromProviderSession", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateWorkMetadataFromProviderSession))
}
