// Code generated by MockGen. DO NOT EDIT.
// Source: processing.go
//
// Generated by this command:
//
//	mockgen -source=processing.go -destination=test/processing_mocks.go -package=test Client
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	auth "github.com/tidepool-org/platform/auth"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DeleteProviderSession mocks base method.
func (m *MockClient) DeleteProviderSession(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProviderSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProviderSession indicates an expected call of DeleteProviderSession.
func (mr *MockClientMockRecorder) DeleteProviderSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProviderSession", reflect.TypeOf((*MockClient)(nil).DeleteProviderSession), ctx, id)
}

// GetProviderSession mocks base method.
func (m *MockClient) GetProviderSession(ctx context.Context, id string) (*auth.ProviderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderSession", ctx, id)
	ret0, _ := ret[0].(*auth.ProviderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderSession indicates an expected call of GetProviderSession.
func (mr *MockClientMockRecorder) GetProviderSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderSession", reflect.TypeOf((*MockClient)(nil).GetProviderSession), ctx, id)
}

// UpdateProviderSession mocks base method.
func (m *MockClient) UpdateProviderSession(ctx context.Context, id string, update *auth.ProviderSessionUpdate) (*auth.ProviderSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderSession", ctx, id, update)
	ret0, _ := ret[0].(*auth.ProviderSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProviderSession indicates an expected call of UpdateProviderSession.
func (mr *MockClientMockRecorder) UpdateProviderSession(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderSession", reflect.TypeOf((*MockClient)(nil).UpdateProviderSession), ctx, id, update)
}
