// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go
//
// Generated by this command:
//
//	mockgen -source=factory.go -destination=test/factory_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSummaryLister is a mock of SummaryLister interface.
type MockSummaryLister struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryListerMockRecorder
	isgomock struct{}
}

// MockSummaryListerMockRecorder is the mock recorder for MockSummaryLister.
type MockSummaryListerMockRecorder struct {
	mock *MockSummaryLister
}

// NewMockSummaryLister creates a new mock instance.
func NewMockSummaryLister(ctrl *gomock.Controller) *MockSummaryLister {
	mock := &MockSummaryLister{ctrl: ctrl}
	mock.recorder = &MockSummaryListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryLister) EXPECT() *MockSummaryListerMockRecorder {
	return m.recorder
}

// ListUserIDs mocks base method.
func (m *MockSummaryLister) ListUserIDs(ctx context.Context, afterUserID *string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserIDs", ctx, afterUserID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserIDs indicates an expected call of ListUserIDs.
func (mr *MockSummaryListerMockRecorder) ListUserIDs(ctx, afterUserID, limit any) *MockSummaryListerListUserIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserIDs", reflect.TypeOf((*MockSummaryLister)(nil).ListUserIDs), ctx, afterUserID, limit)
	return &MockSummaryListerListUserIDsCall{Call: call}
}

// MockSummaryListerListUserIDsCall wrap *gomock.Call
type MockSummaryListerListUserIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummaryListerListUserIDsCall) Return(arg0 []string, arg1 error) *MockSummaryListerListUserIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummaryListerListUserIDsCall) Do(f func(context.Context, *string, int) ([]string, error)) *MockSummaryListerListUserIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummaryListerListUserIDsCall) DoAndReturn(f func(context.Context, *string, int) ([]string, error)) *MockSummaryListerListUserIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
