// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=test/client_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	page "github.com/tidepool-org/platform/page"
	structured "github.com/tidepool-org/platform/store/structured"
	work "github.com/tidepool-org/platform/work"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStore) Create(ctx context.Context, create *work.Create) (*work.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, create)
	ret0, _ := ret[0].(*work.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(ctx, create any) *MockStoreCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), ctx, create)
	return &MockStoreCreateCall{Call: call}
}

// MockStoreCreateCall wrap *gomock.Call
type MockStoreCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCreateCall) Return(arg0 *work.Work, arg1 error) *MockStoreCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCreateCall) Do(f func(context.Context, *work.Create) (*work.Work, error)) *MockStoreCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCreateCall) DoAndReturn(f func(context.Context, *work.Create) (*work.Work, error)) *MockStoreCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockStore) Delete(ctx context.Context, id string, condition *structured.Condition) (*work.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, condition)
	ret0, _ := ret[0].(*work.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(ctx, id, condition any) *MockStoreDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), ctx, id, condition)
	return &MockStoreDeleteCall{Call: call}
}

// MockStoreDeleteCall wrap *gomock.Call
type MockStoreDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteCall) Return(arg0 *work.Work, arg1 error) *MockStoreDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteCall) Do(f func(context.Context, string, *structured.Condition) (*work.Work, error)) *MockStoreDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteCall) DoAndReturn(f func(context.Context, string, *structured.Condition) (*work.Work, error)) *MockStoreDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAllByGroupID mocks base method.
func (m *MockStore) DeleteAllByGroupID(ctx context.Context, groupID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByGroupID", ctx, groupID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllByGroupID indicates an expected call of DeleteAllByGroupID.
func (mr *MockStoreMockRecorder) DeleteAllByGroupID(ctx, groupID any) *MockStoreDeleteAllByGroupIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByGroupID", reflect.TypeOf((*MockStore)(nil).DeleteAllByGroupID), ctx, groupID)
	return &MockStoreDeleteAllByGroupIDCall{Call: call}
}

// MockStoreDeleteAllByGroupIDCall wrap *gomock.Call
type MockStoreDeleteAllByGroupIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteAllByGroupIDCall) Return(arg0 int, arg1 error) *MockStoreDeleteAllByGroupIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteAllByGroupIDCall) Do(f func(context.Context, string) (int, error)) *MockStoreDeleteAllByGroupIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteAllByGroupIDCall) DoAndReturn(f func(context.Context, string) (int, error)) *MockStoreDeleteAllByGroupIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, id string, condition *structured.Condition) (*work.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, condition)
	ret0, _ := ret[0].(*work.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, id, condition any) *MockStoreGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, id, condition)
	return &MockStoreGetCall{Call: call}
}

// MockStoreGetCall wrap *gomock.Call
type MockStoreGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetCall) Return(arg0 *work.Work, arg1 error) *MockStoreGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetCall) Do(f func(context.Context, string, *structured.Condition) (*work.Work, error)) *MockStoreGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetCall) DoAndReturn(f func(context.Context, string, *structured.Condition) (*work.Work, error)) *MockStoreGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockStore) List(ctx context.Context, filter *work.Filter, pagination *page.Pagination) ([]*work.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, pagination)
	ret0, _ := ret[0].([]*work.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(ctx, filter, pagination any) *MockStoreListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), ctx, filter, pagination)
	return &MockStoreListCall{Call: call}
}

// MockStoreListCall wrap *gomock.Call
type MockStoreListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreListCall) Return(arg0 []*work.Work, arg1 error) *MockStoreListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreListCall) Do(f func(context.Context, *work.Filter, *page.Pagination) ([]*work.Work, error)) *MockStoreListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreListCall) DoAndReturn(f func(context.Context, *work.Filter, *page.Pagination) ([]*work.Work, error)) *MockStoreListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Poll mocks base method.
func (m *MockStore) Poll(ctx context.Context, poll *work.Poll) ([]*work.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", ctx, poll)
	ret0, _ := ret[0].([]*work.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockStoreMockRecorder) Poll(ctx, poll any) *MockStorePollCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockStore)(nil).Poll), ctx, poll)
	return &MockStorePollCall{Call: call}
}

// MockStorePollCall wrap *gomock.Call
type MockStorePollCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorePollCall) Return(arg0 []*work.Work, arg1 error) *MockStorePollCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorePollCall) Do(f func(context.Context, *work.Poll) ([]*work.Work, error)) *MockStorePollCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorePollCall) DoAndReturn(f func(context.Context, *work.Poll) ([]*work.Work, error)) *MockStorePollCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockStore) Update(ctx context.Context, id string, condition *structured.Condition, update *work.Update) (*work.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, condition, update)
	ret0, _ := ret[0].(*work.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStoreMockRecorder) Update(ctx, id, condition, update any) *MockStoreUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStore)(nil).Update), ctx, id, condition, update)
	return &MockStoreUpdateCall{Call: call}
}

// MockStoreUpdateCall wrap *gomock.Call
type MockStoreUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUpdateCall) Return(arg0 *work.Work, arg1 error) *MockStoreUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUpdateCall) Do(f func(context.Context, string, *structured.Condition, *work.Update) (*work.Work, error)) *MockStoreUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUpdateCall) DoAndReturn(f func(context.Context, string, *structured.Condition, *work.Update) (*work.Work, error)) *MockStoreUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
