// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=test/service_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	api "github.com/tidepool-org/hydrophone/client"
	gomock "go.uber.org/mock/gomock"

	apple "github.com/tidepool-org/platform/apple"
	appvalidate "github.com/tidepool-org/platform/appvalidate"
	auth "github.com/tidepool-org/platform/auth"
	service "github.com/tidepool-org/platform/auth/service"
	store "github.com/tidepool-org/platform/auth/store"
	config "github.com/tidepool-org/platform/config"
	log "github.com/tidepool-org/platform/log"
	provider "github.com/tidepool-org/platform/provider"
	task "github.com/tidepool-org/platform/task"
	version "github.com/tidepool-org/platform/version"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AppValidator mocks base method.
func (m *MockService) AppValidator() *appvalidate.Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppValidator")
	ret0, _ := ret[0].(*appvalidate.Validator)
	return ret0
}

// AppValidator indicates an expected call of AppValidator.
func (mr *MockServiceMockRecorder) AppValidator() *MockServiceAppValidatorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppValidator", reflect.TypeOf((*MockService)(nil).AppValidator))
	return &MockServiceAppValidatorCall{Call: call}
}

// MockServiceAppValidatorCall wrap *gomock.Call
type MockServiceAppValidatorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAppValidatorCall) Return(arg0 *appvalidate.Validator) *MockServiceAppValidatorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAppValidatorCall) Do(f func() *appvalidate.Validator) *MockServiceAppValidatorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAppValidatorCall) DoAndReturn(f func() *appvalidate.Validator) *MockServiceAppValidatorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AuthClient mocks base method.
func (m *MockService) AuthClient() auth.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthClient")
	ret0, _ := ret[0].(auth.Client)
	return ret0
}

// AuthClient indicates an expected call of AuthClient.
func (mr *MockServiceMockRecorder) AuthClient() *MockServiceAuthClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthClient", reflect.TypeOf((*MockService)(nil).AuthClient))
	return &MockServiceAuthClientCall{Call: call}
}

// MockServiceAuthClientCall wrap *gomock.Call
type MockServiceAuthClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAuthClientCall) Return(arg0 auth.Client) *MockServiceAuthClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAuthClientCall) Do(f func() auth.Client) *MockServiceAuthClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAuthClientCall) DoAndReturn(f func() auth.Client) *MockServiceAuthClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AuthStore mocks base method.
func (m *MockService) AuthStore() store.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthStore")
	ret0, _ := ret[0].(store.Store)
	return ret0
}

// AuthStore indicates an expected call of AuthStore.
func (mr *MockServiceMockRecorder) AuthStore() *MockServiceAuthStoreCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthStore", reflect.TypeOf((*MockService)(nil).AuthStore))
	return &MockServiceAuthStoreCall{Call: call}
}

// MockServiceAuthStoreCall wrap *gomock.Call
type MockServiceAuthStoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAuthStoreCall) Return(arg0 store.Store) *MockServiceAuthStoreCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAuthStoreCall) Do(f func() store.Store) *MockServiceAuthStoreCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAuthStoreCall) DoAndReturn(f func() store.Store) *MockServiceAuthStoreCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfigReporter mocks base method.
func (m *MockService) ConfigReporter() config.Reporter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigReporter")
	ret0, _ := ret[0].(config.Reporter)
	return ret0
}

// ConfigReporter indicates an expected call of ConfigReporter.
func (mr *MockServiceMockRecorder) ConfigReporter() *MockServiceConfigReporterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigReporter", reflect.TypeOf((*MockService)(nil).ConfigReporter))
	return &MockServiceConfigReporterCall{Call: call}
}

// MockServiceConfigReporterCall wrap *gomock.Call
type MockServiceConfigReporterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceConfigReporterCall) Return(arg0 config.Reporter) *MockServiceConfigReporterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceConfigReporterCall) Do(f func() config.Reporter) *MockServiceConfigReporterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceConfigReporterCall) DoAndReturn(f func() config.Reporter) *MockServiceConfigReporterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConfirmationClient mocks base method.
func (m *MockService) ConfirmationClient() api.ClientWithResponsesInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmationClient")
	ret0, _ := ret[0].(api.ClientWithResponsesInterface)
	return ret0
}

// ConfirmationClient indicates an expected call of ConfirmationClient.
func (mr *MockServiceMockRecorder) ConfirmationClient() *MockServiceConfirmationClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmationClient", reflect.TypeOf((*MockService)(nil).ConfirmationClient))
	return &MockServiceConfirmationClientCall{Call: call}
}

// MockServiceConfirmationClientCall wrap *gomock.Call
type MockServiceConfirmationClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceConfirmationClientCall) Return(arg0 api.ClientWithResponsesInterface) *MockServiceConfirmationClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceConfirmationClientCall) Do(f func() api.ClientWithResponsesInterface) *MockServiceConfirmationClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceConfirmationClientCall) DoAndReturn(f func() api.ClientWithResponsesInterface) *MockServiceConfirmationClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeviceCheck mocks base method.
func (m *MockService) DeviceCheck() apple.DeviceCheck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceCheck")
	ret0, _ := ret[0].(apple.DeviceCheck)
	return ret0
}

// DeviceCheck indicates an expected call of DeviceCheck.
func (mr *MockServiceMockRecorder) DeviceCheck() *MockServiceDeviceCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceCheck", reflect.TypeOf((*MockService)(nil).DeviceCheck))
	return &MockServiceDeviceCheckCall{Call: call}
}

// MockServiceDeviceCheckCall wrap *gomock.Call
type MockServiceDeviceCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeviceCheckCall) Return(arg0 apple.DeviceCheck) *MockServiceDeviceCheckCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeviceCheckCall) Do(f func() apple.DeviceCheck) *MockServiceDeviceCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeviceCheckCall) DoAndReturn(f func() apple.DeviceCheck) *MockServiceDeviceCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Domain mocks base method.
func (m *MockService) Domain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Domain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Domain indicates an expected call of Domain.
func (mr *MockServiceMockRecorder) Domain() *MockServiceDomainCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Domain", reflect.TypeOf((*MockService)(nil).Domain))
	return &MockServiceDomainCall{Call: call}
}

// MockServiceDomainCall wrap *gomock.Call
type MockServiceDomainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDomainCall) Return(arg0 string) *MockServiceDomainCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDomainCall) Do(f func() string) *MockServiceDomainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDomainCall) DoAndReturn(f func() string) *MockServiceDomainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logger mocks base method.
func (m *MockService) Logger() log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(log.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockServiceMockRecorder) Logger() *MockServiceLoggerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockService)(nil).Logger))
	return &MockServiceLoggerCall{Call: call}
}

// MockServiceLoggerCall wrap *gomock.Call
type MockServiceLoggerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceLoggerCall) Return(arg0 log.Logger) *MockServiceLoggerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceLoggerCall) Do(f func() log.Logger) *MockServiceLoggerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceLoggerCall) DoAndReturn(f func() log.Logger) *MockServiceLoggerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PartnerSecrets mocks base method.
func (m *MockService) PartnerSecrets() *appvalidate.PartnerSecrets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartnerSecrets")
	ret0, _ := ret[0].(*appvalidate.PartnerSecrets)
	return ret0
}

// PartnerSecrets indicates an expected call of PartnerSecrets.
func (mr *MockServiceMockRecorder) PartnerSecrets() *MockServicePartnerSecretsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartnerSecrets", reflect.TypeOf((*MockService)(nil).PartnerSecrets))
	return &MockServicePartnerSecretsCall{Call: call}
}

// MockServicePartnerSecretsCall wrap *gomock.Call
type MockServicePartnerSecretsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServicePartnerSecretsCall) Return(arg0 *appvalidate.PartnerSecrets) *MockServicePartnerSecretsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServicePartnerSecretsCall) Do(f func() *appvalidate.PartnerSecrets) *MockServicePartnerSecretsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServicePartnerSecretsCall) DoAndReturn(f func() *appvalidate.PartnerSecrets) *MockServicePartnerSecretsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProviderFactory mocks base method.
func (m *MockService) ProviderFactory() provider.Factory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderFactory")
	ret0, _ := ret[0].(provider.Factory)
	return ret0
}

// ProviderFactory indicates an expected call of ProviderFactory.
func (mr *MockServiceMockRecorder) ProviderFactory() *MockServiceProviderFactoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderFactory", reflect.TypeOf((*MockService)(nil).ProviderFactory))
	return &MockServiceProviderFactoryCall{Call: call}
}

// MockServiceProviderFactoryCall wrap *gomock.Call
type MockServiceProviderFactoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceProviderFactoryCall) Return(arg0 provider.Factory) *MockServiceProviderFactoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceProviderFactoryCall) Do(f func() provider.Factory) *MockServiceProviderFactoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceProviderFactoryCall) DoAndReturn(f func() provider.Factory) *MockServiceProviderFactoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Secret mocks base method.
func (m *MockService) Secret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secret")
	ret0, _ := ret[0].(string)
	return ret0
}

// Secret indicates an expected call of Secret.
func (mr *MockServiceMockRecorder) Secret() *MockServiceSecretCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secret", reflect.TypeOf((*MockService)(nil).Secret))
	return &MockServiceSecretCall{Call: call}
}

// MockServiceSecretCall wrap *gomock.Call
type MockServiceSecretCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSecretCall) Return(arg0 string) *MockServiceSecretCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSecretCall) Do(f func() string) *MockServiceSecretCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSecretCall) DoAndReturn(f func() string) *MockServiceSecretCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockService) Status(arg0 context.Context) *service.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(*service.Status)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockServiceMockRecorder) Status(arg0 any) *MockServiceStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockService)(nil).Status), arg0)
	return &MockServiceStatusCall{Call: call}
}

// MockServiceStatusCall wrap *gomock.Call
type MockServiceStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceStatusCall) Return(arg0 *service.Status) *MockServiceStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceStatusCall) Do(f func(context.Context) *service.Status) *MockServiceStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceStatusCall) DoAndReturn(f func(context.Context) *service.Status) *MockServiceStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TaskClient mocks base method.
func (m *MockService) TaskClient() task.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskClient")
	ret0, _ := ret[0].(task.Client)
	return ret0
}

// TaskClient indicates an expected call of TaskClient.
func (mr *MockServiceMockRecorder) TaskClient() *MockServiceTaskClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskClient", reflect.TypeOf((*MockService)(nil).TaskClient))
	return &MockServiceTaskClientCall{Call: call}
}

// MockServiceTaskClientCall wrap *gomock.Call
type MockServiceTaskClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTaskClientCall) Return(arg0 task.Client) *MockServiceTaskClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTaskClientCall) Do(f func() task.Client) *MockServiceTaskClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTaskClientCall) DoAndReturn(f func() task.Client) *MockServiceTaskClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TwiistServiceAccountAuthorizer mocks base method.
func (m *MockService) TwiistServiceAccountAuthorizer() auth.ServiceAccountAuthorizer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TwiistServiceAccountAuthorizer")
	ret0, _ := ret[0].(auth.ServiceAccountAuthorizer)
	return ret0
}

// TwiistServiceAccountAuthorizer indicates an expected call of TwiistServiceAccountAuthorizer.
func (mr *MockServiceMockRecorder) TwiistServiceAccountAuthorizer() *MockServiceTwiistServiceAccountAuthorizerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TwiistServiceAccountAuthorizer", reflect.TypeOf((*MockService)(nil).TwiistServiceAccountAuthorizer))
	return &MockServiceTwiistServiceAccountAuthorizerCall{Call: call}
}

// MockServiceTwiistServiceAccountAuthorizerCall wrap *gomock.Call
type MockServiceTwiistServiceAccountAuthorizerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTwiistServiceAccountAuthorizerCall) Return(arg0 auth.ServiceAccountAuthorizer) *MockServiceTwiistServiceAccountAuthorizerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTwiistServiceAccountAuthorizerCall) Do(f func() auth.ServiceAccountAuthorizer) *MockServiceTwiistServiceAccountAuthorizerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTwiistServiceAccountAuthorizerCall) DoAndReturn(f func() auth.ServiceAccountAuthorizer) *MockServiceTwiistServiceAccountAuthorizerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VersionReporter mocks base method.
func (m *MockService) VersionReporter() version.Reporter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VersionReporter")
	ret0, _ := ret[0].(version.Reporter)
	return ret0
}

// VersionReporter indicates an expected call of VersionReporter.
func (mr *MockServiceMockRecorder) VersionReporter() *MockServiceVersionReporterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VersionReporter", reflect.TypeOf((*MockService)(nil).VersionReporter))
	return &MockServiceVersionReporterCall{Call: call}
}

// MockServiceVersionReporterCall wrap *gomock.Call
type MockServiceVersionReporterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceVersionReporterCall) Return(arg0 version.Reporter) *MockServiceVersionReporterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceVersionReporterCall) Do(f func() version.Reporter) *MockServiceVersionReporterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceVersionReporterCall) DoAndReturn(f func() version.Reporter) *MockServiceVersionReporterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
