// Code generated by MockGen. DO NOT EDIT.
// Source: mixin.go
//
// Generated by this command:
//
//	mockgen -source=mixin.go -destination=test/mixin_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	data "github.com/tidepool-org/platform/data"
	set "github.com/tidepool-org/platform/data/set"
	work "github.com/tidepool-org/platform/work"
)

// MockMixin is a mock of Mixin interface.
type MockMixin struct {
	ctrl     *gomock.Controller
	recorder *MockMixinMockRecorder
	isgomock struct{}
}

// MockMixinMockRecorder is the mock recorder for MockMixin.
type MockMixinMockRecorder struct {
	mock *MockMixin
}

// NewMockMixin creates a new mock instance.
func NewMockMixin(ctrl *gomock.Controller) *MockMixin {
	mock := &MockMixin{ctrl: ctrl}
	mock.recorder = &MockMixinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixin) EXPECT() *MockMixinMockRecorder {
	return m.recorder
}

// AddDataSetToContext mocks base method.
func (m *MockMixin) AddDataSetToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDataSetToContext")
}

// AddDataSetToContext indicates an expected call of AddDataSetToContext.
func (mr *MockMixinMockRecorder) AddDataSetToContext() *MockMixinAddDataSetToContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataSetToContext", reflect.TypeOf((*MockMixin)(nil).AddDataSetToContext))
	return &MockMixinAddDataSetToContextCall{Call: call}
}

// MockMixinAddDataSetToContextCall wrap *gomock.Call
type MockMixinAddDataSetToContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinAddDataSetToContextCall) Return() *MockMixinAddDataSetToContextCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinAddDataSetToContextCall) Do(f func()) *MockMixinAddDataSetToContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinAddDataSetToContextCall) DoAndReturn(f func()) *MockMixinAddDataSetToContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateDataSet mocks base method.
func (m *MockMixin) CreateDataSet(userID string, dataSetCreate *data.DataSetCreate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataSet", userID, dataSetCreate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// CreateDataSet indicates an expected call of CreateDataSet.
func (mr *MockMixinMockRecorder) CreateDataSet(userID, dataSetCreate any) *MockMixinCreateDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataSet", reflect.TypeOf((*MockMixin)(nil).CreateDataSet), userID, dataSetCreate)
	return &MockMixinCreateDataSetCall{Call: call}
}

// MockMixinCreateDataSetCall wrap *gomock.Call
type MockMixinCreateDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinCreateDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinCreateDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinCreateDataSetCall) Do(f func(string, *data.DataSetCreate) *work.ProcessResult) *MockMixinCreateDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinCreateDataSetCall) DoAndReturn(f func(string, *data.DataSetCreate) *work.ProcessResult) *MockMixinCreateDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataSet mocks base method.
func (m *MockMixin) DataSet() *data.DataSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSet")
	ret0, _ := ret[0].(*data.DataSet)
	return ret0
}

// DataSet indicates an expected call of DataSet.
func (mr *MockMixinMockRecorder) DataSet() *MockMixinDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSet", reflect.TypeOf((*MockMixin)(nil).DataSet))
	return &MockMixinDataSetCall{Call: call}
}

// MockMixinDataSetCall wrap *gomock.Call
type MockMixinDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinDataSetCall) Return(arg0 *data.DataSet) *MockMixinDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinDataSetCall) Do(f func() *data.DataSet) *MockMixinDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinDataSetCall) DoAndReturn(f func() *data.DataSet) *MockMixinDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataSetClient mocks base method.
func (m *MockMixin) DataSetClient() set.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSetClient")
	ret0, _ := ret[0].(set.Client)
	return ret0
}

// DataSetClient indicates an expected call of DataSetClient.
func (mr *MockMixinMockRecorder) DataSetClient() *MockMixinDataSetClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSetClient", reflect.TypeOf((*MockMixin)(nil).DataSetClient))
	return &MockMixinDataSetClientCall{Call: call}
}

// MockMixinDataSetClientCall wrap *gomock.Call
type MockMixinDataSetClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinDataSetClientCall) Return(arg0 set.Client) *MockMixinDataSetClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinDataSetClientCall) Do(f func() set.Client) *MockMixinDataSetClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinDataSetClientCall) DoAndReturn(f func() set.Client) *MockMixinDataSetClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchDataSet mocks base method.
func (m *MockMixin) FetchDataSet(dataSetID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataSet", dataSetID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataSet indicates an expected call of FetchDataSet.
func (mr *MockMixinMockRecorder) FetchDataSet(dataSetID any) *MockMixinFetchDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataSet", reflect.TypeOf((*MockMixin)(nil).FetchDataSet), dataSetID)
	return &MockMixinFetchDataSetCall{Call: call}
}

// MockMixinFetchDataSetCall wrap *gomock.Call
type MockMixinFetchDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFetchDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinFetchDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFetchDataSetCall) Do(f func(string) *work.ProcessResult) *MockMixinFetchDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFetchDataSetCall) DoAndReturn(f func(string) *work.ProcessResult) *MockMixinFetchDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasDataSet mocks base method.
func (m *MockMixin) HasDataSet() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataSet")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataSet indicates an expected call of HasDataSet.
func (mr *MockMixinMockRecorder) HasDataSet() *MockMixinHasDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataSet", reflect.TypeOf((*MockMixin)(nil).HasDataSet))
	return &MockMixinHasDataSetCall{Call: call}
}

// MockMixinHasDataSetCall wrap *gomock.Call
type MockMixinHasDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinHasDataSetCall) Return(arg0 bool) *MockMixinHasDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinHasDataSetCall) Do(f func() bool) *MockMixinHasDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinHasDataSetCall) DoAndReturn(f func() bool) *MockMixinHasDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetDataSet mocks base method.
func (m *MockMixin) SetDataSet(dataSet *data.DataSet) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataSet", dataSet)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataSet indicates an expected call of SetDataSet.
func (mr *MockMixinMockRecorder) SetDataSet(dataSet any) *MockMixinSetDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataSet", reflect.TypeOf((*MockMixin)(nil).SetDataSet), dataSet)
	return &MockMixinSetDataSetCall{Call: call}
}

// MockMixinSetDataSetCall wrap *gomock.Call
type MockMixinSetDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinSetDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinSetDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinSetDataSetCall) Do(f func(*data.DataSet) *work.ProcessResult) *MockMixinSetDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinSetDataSetCall) DoAndReturn(f func(*data.DataSet) *work.ProcessResult) *MockMixinSetDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDataSet mocks base method.
func (m *MockMixin) UpdateDataSet(dataSetUpdate *data.DataSetUpdate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataSet", dataSetUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataSet indicates an expected call of UpdateDataSet.
func (mr *MockMixinMockRecorder) UpdateDataSet(dataSetUpdate any) *MockMixinUpdateDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataSet", reflect.TypeOf((*MockMixin)(nil).UpdateDataSet), dataSetUpdate)
	return &MockMixinUpdateDataSetCall{Call: call}
}

// MockMixinUpdateDataSetCall wrap *gomock.Call
type MockMixinUpdateDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinUpdateDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinUpdateDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinUpdateDataSetCall) Do(f func(*data.DataSetUpdate) *work.ProcessResult) *MockMixinUpdateDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinUpdateDataSetCall) DoAndReturn(f func(*data.DataSetUpdate) *work.ProcessResult) *MockMixinUpdateDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMixinFromWork is a mock of MixinFromWork interface.
type MockMixinFromWork struct {
	ctrl     *gomock.Controller
	recorder *MockMixinFromWorkMockRecorder
	isgomock struct{}
}

// MockMixinFromWorkMockRecorder is the mock recorder for MockMixinFromWork.
type MockMixinFromWorkMockRecorder struct {
	mock *MockMixinFromWork
}

// NewMockMixinFromWork creates a new mock instance.
func NewMockMixinFromWork(ctrl *gomock.Controller) *MockMixinFromWork {
	mock := &MockMixinFromWork{ctrl: ctrl}
	mock.recorder = &MockMixinFromWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMixinFromWork) EXPECT() *MockMixinFromWorkMockRecorder {
	return m.recorder
}

// AddDataSetToContext mocks base method.
func (m *MockMixinFromWork) AddDataSetToContext() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDataSetToContext")
}

// AddDataSetToContext indicates an expected call of AddDataSetToContext.
func (mr *MockMixinFromWorkMockRecorder) AddDataSetToContext() *MockMixinFromWorkAddDataSetToContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataSetToContext", reflect.TypeOf((*MockMixinFromWork)(nil).AddDataSetToContext))
	return &MockMixinFromWorkAddDataSetToContextCall{Call: call}
}

// MockMixinFromWorkAddDataSetToContextCall wrap *gomock.Call
type MockMixinFromWorkAddDataSetToContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkAddDataSetToContextCall) Return() *MockMixinFromWorkAddDataSetToContextCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkAddDataSetToContextCall) Do(f func()) *MockMixinFromWorkAddDataSetToContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkAddDataSetToContextCall) DoAndReturn(f func()) *MockMixinFromWorkAddDataSetToContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateDataSet mocks base method.
func (m *MockMixinFromWork) CreateDataSet(userID string, dataSetCreate *data.DataSetCreate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataSet", userID, dataSetCreate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// CreateDataSet indicates an expected call of CreateDataSet.
func (mr *MockMixinFromWorkMockRecorder) CreateDataSet(userID, dataSetCreate any) *MockMixinFromWorkCreateDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataSet", reflect.TypeOf((*MockMixinFromWork)(nil).CreateDataSet), userID, dataSetCreate)
	return &MockMixinFromWorkCreateDataSetCall{Call: call}
}

// MockMixinFromWorkCreateDataSetCall wrap *gomock.Call
type MockMixinFromWorkCreateDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkCreateDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkCreateDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkCreateDataSetCall) Do(f func(string, *data.DataSetCreate) *work.ProcessResult) *MockMixinFromWorkCreateDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkCreateDataSetCall) DoAndReturn(f func(string, *data.DataSetCreate) *work.ProcessResult) *MockMixinFromWorkCreateDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataSet mocks base method.
func (m *MockMixinFromWork) DataSet() *data.DataSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSet")
	ret0, _ := ret[0].(*data.DataSet)
	return ret0
}

// DataSet indicates an expected call of DataSet.
func (mr *MockMixinFromWorkMockRecorder) DataSet() *MockMixinFromWorkDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSet", reflect.TypeOf((*MockMixinFromWork)(nil).DataSet))
	return &MockMixinFromWorkDataSetCall{Call: call}
}

// MockMixinFromWorkDataSetCall wrap *gomock.Call
type MockMixinFromWorkDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkDataSetCall) Return(arg0 *data.DataSet) *MockMixinFromWorkDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkDataSetCall) Do(f func() *data.DataSet) *MockMixinFromWorkDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkDataSetCall) DoAndReturn(f func() *data.DataSet) *MockMixinFromWorkDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataSetClient mocks base method.
func (m *MockMixinFromWork) DataSetClient() set.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSetClient")
	ret0, _ := ret[0].(set.Client)
	return ret0
}

// DataSetClient indicates an expected call of DataSetClient.
func (mr *MockMixinFromWorkMockRecorder) DataSetClient() *MockMixinFromWorkDataSetClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSetClient", reflect.TypeOf((*MockMixinFromWork)(nil).DataSetClient))
	return &MockMixinFromWorkDataSetClientCall{Call: call}
}

// MockMixinFromWorkDataSetClientCall wrap *gomock.Call
type MockMixinFromWorkDataSetClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkDataSetClientCall) Return(arg0 set.Client) *MockMixinFromWorkDataSetClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkDataSetClientCall) Do(f func() set.Client) *MockMixinFromWorkDataSetClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkDataSetClientCall) DoAndReturn(f func() set.Client) *MockMixinFromWorkDataSetClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchDataSet mocks base method.
func (m *MockMixinFromWork) FetchDataSet(dataSetID string) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataSet", dataSetID)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataSet indicates an expected call of FetchDataSet.
func (mr *MockMixinFromWorkMockRecorder) FetchDataSet(dataSetID any) *MockMixinFromWorkFetchDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataSet", reflect.TypeOf((*MockMixinFromWork)(nil).FetchDataSet), dataSetID)
	return &MockMixinFromWorkFetchDataSetCall{Call: call}
}

// MockMixinFromWorkFetchDataSetCall wrap *gomock.Call
type MockMixinFromWorkFetchDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkFetchDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkFetchDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkFetchDataSetCall) Do(f func(string) *work.ProcessResult) *MockMixinFromWorkFetchDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkFetchDataSetCall) DoAndReturn(f func(string) *work.ProcessResult) *MockMixinFromWorkFetchDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchDataSetFromWorkMetadata mocks base method.
func (m *MockMixinFromWork) FetchDataSetFromWorkMetadata() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDataSetFromWorkMetadata")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// FetchDataSetFromWorkMetadata indicates an expected call of FetchDataSetFromWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) FetchDataSetFromWorkMetadata() *MockMixinFromWorkFetchDataSetFromWorkMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDataSetFromWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).FetchDataSetFromWorkMetadata))
	return &MockMixinFromWorkFetchDataSetFromWorkMetadataCall{Call: call}
}

// MockMixinFromWorkFetchDataSetFromWorkMetadataCall wrap *gomock.Call
type MockMixinFromWorkFetchDataSetFromWorkMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkFetchDataSetFromWorkMetadataCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkFetchDataSetFromWorkMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkFetchDataSetFromWorkMetadataCall) Do(f func() *work.ProcessResult) *MockMixinFromWorkFetchDataSetFromWorkMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkFetchDataSetFromWorkMetadataCall) DoAndReturn(f func() *work.ProcessResult) *MockMixinFromWorkFetchDataSetFromWorkMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasDataSet mocks base method.
func (m *MockMixinFromWork) HasDataSet() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDataSet")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasDataSet indicates an expected call of HasDataSet.
func (mr *MockMixinFromWorkMockRecorder) HasDataSet() *MockMixinFromWorkHasDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDataSet", reflect.TypeOf((*MockMixinFromWork)(nil).HasDataSet))
	return &MockMixinFromWorkHasDataSetCall{Call: call}
}

// MockMixinFromWorkHasDataSetCall wrap *gomock.Call
type MockMixinFromWorkHasDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkHasDataSetCall) Return(arg0 bool) *MockMixinFromWorkHasDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkHasDataSetCall) Do(f func() bool) *MockMixinFromWorkHasDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkHasDataSetCall) DoAndReturn(f func() bool) *MockMixinFromWorkHasDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasWorkMetadata mocks base method.
func (m *MockMixinFromWork) HasWorkMetadata() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasWorkMetadata")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasWorkMetadata indicates an expected call of HasWorkMetadata.
func (mr *MockMixinFromWorkMockRecorder) HasWorkMetadata() *MockMixinFromWorkHasWorkMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasWorkMetadata", reflect.TypeOf((*MockMixinFromWork)(nil).HasWorkMetadata))
	return &MockMixinFromWorkHasWorkMetadataCall{Call: call}
}

// MockMixinFromWorkHasWorkMetadataCall wrap *gomock.Call
type MockMixinFromWorkHasWorkMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkHasWorkMetadataCall) Return(arg0 bool) *MockMixinFromWorkHasWorkMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkHasWorkMetadataCall) Do(f func() bool) *MockMixinFromWorkHasWorkMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkHasWorkMetadataCall) DoAndReturn(f func() bool) *MockMixinFromWorkHasWorkMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetDataSet mocks base method.
func (m *MockMixinFromWork) SetDataSet(dataSet *data.DataSet) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataSet", dataSet)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// SetDataSet indicates an expected call of SetDataSet.
func (mr *MockMixinFromWorkMockRecorder) SetDataSet(dataSet any) *MockMixinFromWorkSetDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataSet", reflect.TypeOf((*MockMixinFromWork)(nil).SetDataSet), dataSet)
	return &MockMixinFromWorkSetDataSetCall{Call: call}
}

// MockMixinFromWorkSetDataSetCall wrap *gomock.Call
type MockMixinFromWorkSetDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkSetDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkSetDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkSetDataSetCall) Do(f func(*data.DataSet) *work.ProcessResult) *MockMixinFromWorkSetDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkSetDataSetCall) DoAndReturn(f func(*data.DataSet) *work.ProcessResult) *MockMixinFromWorkSetDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDataSet mocks base method.
func (m *MockMixinFromWork) UpdateDataSet(dataSetUpdate *data.DataSetUpdate) *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataSet", dataSetUpdate)
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateDataSet indicates an expected call of UpdateDataSet.
func (mr *MockMixinFromWorkMockRecorder) UpdateDataSet(dataSetUpdate any) *MockMixinFromWorkUpdateDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataSet", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateDataSet), dataSetUpdate)
	return &MockMixinFromWorkUpdateDataSetCall{Call: call}
}

// MockMixinFromWorkUpdateDataSetCall wrap *gomock.Call
type MockMixinFromWorkUpdateDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkUpdateDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkUpdateDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkUpdateDataSetCall) Do(f func(*data.DataSetUpdate) *work.ProcessResult) *MockMixinFromWorkUpdateDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkUpdateDataSetCall) DoAndReturn(f func(*data.DataSetUpdate) *work.ProcessResult) *MockMixinFromWorkUpdateDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateWorkMetadataFromDataSet mocks base method.
func (m *MockMixinFromWork) UpdateWorkMetadataFromDataSet() *work.ProcessResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkMetadataFromDataSet")
	ret0, _ := ret[0].(*work.ProcessResult)
	return ret0
}

// UpdateWorkMetadataFromDataSet indicates an expected call of UpdateWorkMetadataFromDataSet.
func (mr *MockMixinFromWorkMockRecorder) UpdateWorkMetadataFromDataSet() *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkMetadataFromDataSet", reflect.TypeOf((*MockMixinFromWork)(nil).UpdateWorkMetadataFromDataSet))
	return &MockMixinFromWorkUpdateWorkMetadataFromDataSetCall{Call: call}
}

// MockMixinFromWorkUpdateWorkMetadataFromDataSetCall wrap *gomock.Call
type MockMixinFromWorkUpdateWorkMetadataFromDataSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall) Return(arg0 *work.ProcessResult) *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall) Do(f func() *work.ProcessResult) *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall) DoAndReturn(f func() *work.ProcessResult) *MockMixinFromWorkUpdateWorkMetadataFromDataSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
