// Code generated by MockGen. DO NOT EDIT.
// Source: outdated.go
//
// Generated by this command:
//
//	mockgen -source=outdated.go -destination=test/outdated_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	store "github.com/tidepool-org/platform/summary/store"
)

// MockSummaries is a mock of Summaries interface.
type MockSummaries struct {
	ctrl     *gomock.Controller
	recorder *MockSummariesMockRecorder
	isgomock struct{}
}

// MockSummariesMockRecorder is the mock recorder for MockSummaries.
type MockSummariesMockRecorder struct {
	mock *MockSummaries
}

// NewMockSummaries creates a new mock instance.
func NewMockSummaries(ctrl *gomock.Controller) *MockSummaries {
	mock := &MockSummaries{ctrl: ctrl}
	mock.recorder = &MockSummariesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaries) EXPECT() *MockSummariesMockRecorder {
	return m.recorder
}

// ClearOutdated mocks base method.
func (m *MockSummaries) ClearOutdated(ctx context.Context, userID, typ string, observed time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearOutdated", ctx, userID, typ, observed)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearOutdated indicates an expected call of ClearOutdated.
func (mr *MockSummariesMockRecorder) ClearOutdated(ctx, userID, typ, observed any) *MockSummariesClearOutdatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearOutdated", reflect.TypeOf((*MockSummaries)(nil).ClearOutdated), ctx, userID, typ, observed)
	return &MockSummariesClearOutdatedCall{Call: call}
}

// MockSummariesClearOutdatedCall wrap *gomock.Call
type MockSummariesClearOutdatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummariesClearOutdatedCall) Return(arg0 error) *MockSummariesClearOutdatedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummariesClearOutdatedCall) Do(f func(context.Context, string, string, time.Time) error) *MockSummariesClearOutdatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummariesClearOutdatedCall) DoAndReturn(f func(context.Context, string, string, time.Time) error) *MockSummariesClearOutdatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListOutdated mocks base method.
func (m *MockSummaries) ListOutdated(ctx context.Context, limit int) ([]store.OutdatedSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOutdated", ctx, limit)
	ret0, _ := ret[0].([]store.OutdatedSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOutdated indicates an expected call of ListOutdated.
func (mr *MockSummariesMockRecorder) ListOutdated(ctx, limit any) *MockSummariesListOutdatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOutdated", reflect.TypeOf((*MockSummaries)(nil).ListOutdated), ctx, limit)
	return &MockSummariesListOutdatedCall{Call: call}
}

// MockSummariesListOutdatedCall wrap *gomock.Call
type MockSummariesListOutdatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummariesListOutdatedCall) Return(arg0 []store.OutdatedSummary, arg1 error) *MockSummariesListOutdatedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummariesListOutdatedCall) Do(f func(context.Context, int) ([]store.OutdatedSummary, error)) *MockSummariesListOutdatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummariesListOutdatedCall) DoAndReturn(f func(context.Context, int) ([]store.OutdatedSummary, error)) *MockSummariesListOutdatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
