// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tidepool-org/platform/user (interfaces: UserProfileAccessor,UserAccessor)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination=./user_mock.go -package=user . UserProfileAccessor,UserAccessor
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserProfileAccessor is a mock of UserProfileAccessor interface.
type MockUserProfileAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileAccessorMockRecorder
	isgomock struct{}
}

// MockUserProfileAccessorMockRecorder is the mock recorder for MockUserProfileAccessor.
type MockUserProfileAccessorMockRecorder struct {
	mock *MockUserProfileAccessor
}

// NewMockUserProfileAccessor creates a new mock instance.
func NewMockUserProfileAccessor(ctrl *gomock.Controller) *MockUserProfileAccessor {
	mock := &MockUserProfileAccessor{ctrl: ctrl}
	mock.recorder = &MockUserProfileAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileAccessor) EXPECT() *MockUserProfileAccessorMockRecorder {
	return m.recorder
}

// DeleteUserProfile mocks base method.
func (m *MockUserProfileAccessor) DeleteUserProfile(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserProfile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserProfile indicates an expected call of DeleteUserProfile.
func (mr *MockUserProfileAccessorMockRecorder) DeleteUserProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserProfile", reflect.TypeOf((*MockUserProfileAccessor)(nil).DeleteUserProfile), ctx, id)
}

// FindUserProfile mocks base method.
func (m *MockUserProfileAccessor) FindUserProfile(ctx context.Context, id string) (*UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserProfile", ctx, id)
	ret0, _ := ret[0].(*UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserProfile indicates an expected call of FindUserProfile.
func (mr *MockUserProfileAccessorMockRecorder) FindUserProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserProfile", reflect.TypeOf((*MockUserProfileAccessor)(nil).FindUserProfile), ctx, id)
}

// UpdateUserProfile mocks base method.
func (m *MockUserProfileAccessor) UpdateUserProfile(ctx context.Context, id string, p *UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, id, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserProfileAccessorMockRecorder) UpdateUserProfile(ctx, id, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserProfileAccessor)(nil).UpdateUserProfile), ctx, id, p)
}

// MockUserAccessor is a mock of UserAccessor interface.
type MockUserAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccessorMockRecorder
	isgomock struct{}
}

// MockUserAccessorMockRecorder is the mock recorder for MockUserAccessor.
type MockUserAccessorMockRecorder struct {
	mock *MockUserAccessor
}

// NewMockUserAccessor creates a new mock instance.
func NewMockUserAccessor(ctrl *gomock.Controller) *MockUserAccessor {
	mock := &MockUserAccessor{ctrl: ctrl}
	mock.recorder = &MockUserAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccessor) EXPECT() *MockUserAccessorMockRecorder {
	return m.recorder
}

// DeleteUserProfile mocks base method.
func (m *MockUserAccessor) DeleteUserProfile(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserProfile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserProfile indicates an expected call of DeleteUserProfile.
func (mr *MockUserAccessorMockRecorder) DeleteUserProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserProfile", reflect.TypeOf((*MockUserAccessor)(nil).DeleteUserProfile), ctx, id)
}

// FindUser mocks base method.
func (m *MockUserAccessor) FindUser(ctx context.Context, user *User) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUser", ctx, user)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUser indicates an expected call of FindUser.
func (mr *MockUserAccessorMockRecorder) FindUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockUserAccessor)(nil).FindUser), ctx, user)
}

// FindUserById mocks base method.
func (m *MockUserAccessor) FindUserById(ctx context.Context, id string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserById", ctx, id)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserById indicates an expected call of FindUserById.
func (mr *MockUserAccessorMockRecorder) FindUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockUserAccessor)(nil).FindUserById), ctx, id)
}

// FindUserProfile mocks base method.
func (m *MockUserAccessor) FindUserProfile(ctx context.Context, id string) (*UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserProfile", ctx, id)
	ret0, _ := ret[0].(*UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserProfile indicates an expected call of FindUserProfile.
func (mr *MockUserAccessorMockRecorder) FindUserProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserProfile", reflect.TypeOf((*MockUserAccessor)(nil).FindUserProfile), ctx, id)
}

// FindUsersWithIds mocks base method.
func (m *MockUserAccessor) FindUsersWithIds(ctx context.Context, ids []string) ([]*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersWithIds", ctx, ids)
	ret0, _ := ret[0].([]*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersWithIds indicates an expected call of FindUsersWithIds.
func (mr *MockUserAccessorMockRecorder) FindUsersWithIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersWithIds", reflect.TypeOf((*MockUserAccessor)(nil).FindUsersWithIds), ctx, ids)
}

// UpdateUserProfile mocks base method.
func (m *MockUserAccessor) UpdateUserProfile(ctx context.Context, id string, p *UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, id, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserAccessorMockRecorder) UpdateUserProfile(ctx, id, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserAccessor)(nil).UpdateUserProfile), ctx, id, p)
}
