// Code generated by MockGen. DO NOT EDIT.
// Source: context.go
//
// Generated by this command:
//
//	mockgen -source=context.go -destination=test/context_mocks.go -package=test -typed
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	rest "github.com/ant0ine/go-json-rest/rest"
	gomock "go.uber.org/mock/gomock"

	service "github.com/tidepool-org/platform-plugin-abbott/abbott/service"
	alerts "github.com/tidepool-org/platform/alerts"
	auth "github.com/tidepool-org/platform/auth"
	clinics "github.com/tidepool-org/platform/clinics"
	client "github.com/tidepool-org/platform/data/client"
	deduplicator "github.com/tidepool-org/platform/data/deduplicator"
	raw "github.com/tidepool-org/platform/data/raw"
	source "github.com/tidepool-org/platform/data/source"
	store "github.com/tidepool-org/platform/data/store"
	metric "github.com/tidepool-org/platform/metric"
	oura "github.com/tidepool-org/platform/oura"
	permission "github.com/tidepool-org/platform/permission"
	service0 "github.com/tidepool-org/platform/service"
	summary "github.com/tidepool-org/platform/summary"
	reporters "github.com/tidepool-org/platform/summary/reporters"
	store0 "github.com/tidepool-org/platform/synctask/store"
	work "github.com/tidepool-org/platform/work"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// AbbottServiceRequestAuthorizer mocks base method.
func (m *MockContext) AbbottServiceRequestAuthorizer() service.RequestAuthorizer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbbottServiceRequestAuthorizer")
	ret0, _ := ret[0].(service.RequestAuthorizer)
	return ret0
}

// AbbottServiceRequestAuthorizer indicates an expected call of AbbottServiceRequestAuthorizer.
func (mr *MockContextMockRecorder) AbbottServiceRequestAuthorizer() *MockContextAbbottServiceRequestAuthorizerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbbottServiceRequestAuthorizer", reflect.TypeOf((*MockContext)(nil).AbbottServiceRequestAuthorizer))
	return &MockContextAbbottServiceRequestAuthorizerCall{Call: call}
}

// MockContextAbbottServiceRequestAuthorizerCall wrap *gomock.Call
type MockContextAbbottServiceRequestAuthorizerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextAbbottServiceRequestAuthorizerCall) Return(arg0 service.RequestAuthorizer) *MockContextAbbottServiceRequestAuthorizerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextAbbottServiceRequestAuthorizerCall) Do(f func() service.RequestAuthorizer) *MockContextAbbottServiceRequestAuthorizerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextAbbottServiceRequestAuthorizerCall) DoAndReturn(f func() service.RequestAuthorizer) *MockContextAbbottServiceRequestAuthorizerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AlertsRepository mocks base method.
func (m *MockContext) AlertsRepository() alerts.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertsRepository")
	ret0, _ := ret[0].(alerts.Repository)
	return ret0
}

// AlertsRepository indicates an expected call of AlertsRepository.
func (mr *MockContextMockRecorder) AlertsRepository() *MockContextAlertsRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertsRepository", reflect.TypeOf((*MockContext)(nil).AlertsRepository))
	return &MockContextAlertsRepositoryCall{Call: call}
}

// MockContextAlertsRepositoryCall wrap *gomock.Call
type MockContextAlertsRepositoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextAlertsRepositoryCall) Return(arg0 alerts.Repository) *MockContextAlertsRepositoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextAlertsRepositoryCall) Do(f func() alerts.Repository) *MockContextAlertsRepositoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextAlertsRepositoryCall) DoAndReturn(f func() alerts.Repository) *MockContextAlertsRepositoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AuthClient mocks base method.
func (m *MockContext) AuthClient() auth.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthClient")
	ret0, _ := ret[0].(auth.Client)
	return ret0
}

// AuthClient indicates an expected call of AuthClient.
func (mr *MockContextMockRecorder) AuthClient() *MockContextAuthClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthClient", reflect.TypeOf((*MockContext)(nil).AuthClient))
	return &MockContextAuthClientCall{Call: call}
}

// MockContextAuthClientCall wrap *gomock.Call
type MockContextAuthClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextAuthClientCall) Return(arg0 auth.Client) *MockContextAuthClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextAuthClientCall) Do(f func() auth.Client) *MockContextAuthClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextAuthClientCall) DoAndReturn(f func() auth.Client) *MockContextAuthClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClinicsClient mocks base method.
func (m *MockContext) ClinicsClient() clinics.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClinicsClient")
	ret0, _ := ret[0].(clinics.Client)
	return ret0
}

// ClinicsClient indicates an expected call of ClinicsClient.
func (mr *MockContextMockRecorder) ClinicsClient() *MockContextClinicsClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClinicsClient", reflect.TypeOf((*MockContext)(nil).ClinicsClient))
	return &MockContextClinicsClientCall{Call: call}
}

// MockContextClinicsClientCall wrap *gomock.Call
type MockContextClinicsClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextClinicsClientCall) Return(arg0 clinics.Client) *MockContextClinicsClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextClinicsClientCall) Do(f func() clinics.Client) *MockContextClinicsClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextClinicsClientCall) DoAndReturn(f func() clinics.Client) *MockContextClinicsClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataClient mocks base method.
func (m *MockContext) DataClient() client.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataClient")
	ret0, _ := ret[0].(client.Client)
	return ret0
}

// DataClient indicates an expected call of DataClient.
func (mr *MockContextMockRecorder) DataClient() *MockContextDataClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataClient", reflect.TypeOf((*MockContext)(nil).DataClient))
	return &MockContextDataClientCall{Call: call}
}

// MockContextDataClientCall wrap *gomock.Call
type MockContextDataClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextDataClientCall) Return(arg0 client.Client) *MockContextDataClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextDataClientCall) Do(f func() client.Client) *MockContextDataClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextDataClientCall) DoAndReturn(f func() client.Client) *MockContextDataClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataDeduplicatorFactory mocks base method.
func (m *MockContext) DataDeduplicatorFactory() deduplicator.Factory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataDeduplicatorFactory")
	ret0, _ := ret[0].(deduplicator.Factory)
	return ret0
}

// DataDeduplicatorFactory indicates an expected call of DataDeduplicatorFactory.
func (mr *MockContextMockRecorder) DataDeduplicatorFactory() *MockContextDataDeduplicatorFactoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataDeduplicatorFactory", reflect.TypeOf((*MockContext)(nil).DataDeduplicatorFactory))
	return &MockContextDataDeduplicatorFactoryCall{Call: call}
}

// MockContextDataDeduplicatorFactoryCall wrap *gomock.Call
type MockContextDataDeduplicatorFactoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextDataDeduplicatorFactoryCall) Return(arg0 deduplicator.Factory) *MockContextDataDeduplicatorFactoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextDataDeduplicatorFactoryCall) Do(f func() deduplicator.Factory) *MockContextDataDeduplicatorFactoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextDataDeduplicatorFactoryCall) DoAndReturn(f func() deduplicator.Factory) *MockContextDataDeduplicatorFactoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataRawClient mocks base method.
func (m *MockContext) DataRawClient() raw.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRawClient")
	ret0, _ := ret[0].(raw.Client)
	return ret0
}

// DataRawClient indicates an expected call of DataRawClient.
func (mr *MockContextMockRecorder) DataRawClient() *MockContextDataRawClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRawClient", reflect.TypeOf((*MockContext)(nil).DataRawClient))
	return &MockContextDataRawClientCall{Call: call}
}

// MockContextDataRawClientCall wrap *gomock.Call
type MockContextDataRawClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextDataRawClientCall) Return(arg0 raw.Client) *MockContextDataRawClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextDataRawClientCall) Do(f func() raw.Client) *MockContextDataRawClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextDataRawClientCall) DoAndReturn(f func() raw.Client) *MockContextDataRawClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataRepository mocks base method.
func (m *MockContext) DataRepository() store.DataRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataRepository")
	ret0, _ := ret[0].(store.DataRepository)
	return ret0
}

// DataRepository indicates an expected call of DataRepository.
func (mr *MockContextMockRecorder) DataRepository() *MockContextDataRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataRepository", reflect.TypeOf((*MockContext)(nil).DataRepository))
	return &MockContextDataRepositoryCall{Call: call}
}

// MockContextDataRepositoryCall wrap *gomock.Call
type MockContextDataRepositoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextDataRepositoryCall) Return(arg0 store.DataRepository) *MockContextDataRepositoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextDataRepositoryCall) Do(f func() store.DataRepository) *MockContextDataRepositoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextDataRepositoryCall) DoAndReturn(f func() store.DataRepository) *MockContextDataRepositoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DataSourceClient mocks base method.
func (m *MockContext) DataSourceClient() source.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSourceClient")
	ret0, _ := ret[0].(source.Client)
	return ret0
}

// DataSourceClient indicates an expected call of DataSourceClient.
func (mr *MockContextMockRecorder) DataSourceClient() *MockContextDataSourceClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSourceClient", reflect.TypeOf((*MockContext)(nil).DataSourceClient))
	return &MockContextDataSourceClientCall{Call: call}
}

// MockContextDataSourceClientCall wrap *gomock.Call
type MockContextDataSourceClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextDataSourceClientCall) Return(arg0 source.Client) *MockContextDataSourceClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextDataSourceClientCall) Do(f func() source.Client) *MockContextDataSourceClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextDataSourceClientCall) DoAndReturn(f func() source.Client) *MockContextDataSourceClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MetricClient mocks base method.
func (m *MockContext) MetricClient() metric.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricClient")
	ret0, _ := ret[0].(metric.Client)
	return ret0
}

// MetricClient indicates an expected call of MetricClient.
func (mr *MockContextMockRecorder) MetricClient() *MockContextMetricClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricClient", reflect.TypeOf((*MockContext)(nil).MetricClient))
	return &MockContextMetricClientCall{Call: call}
}

// MockContextMetricClientCall wrap *gomock.Call
type MockContextMetricClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextMetricClientCall) Return(arg0 metric.Client) *MockContextMetricClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextMetricClientCall) Do(f func() metric.Client) *MockContextMetricClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextMetricClientCall) DoAndReturn(f func() metric.Client) *MockContextMetricClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OuraClient mocks base method.
func (m *MockContext) OuraClient() oura.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OuraClient")
	ret0, _ := ret[0].(oura.Client)
	return ret0
}

// OuraClient indicates an expected call of OuraClient.
func (mr *MockContextMockRecorder) OuraClient() *MockContextOuraClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OuraClient", reflect.TypeOf((*MockContext)(nil).OuraClient))
	return &MockContextOuraClientCall{Call: call}
}

// MockContextOuraClientCall wrap *gomock.Call
type MockContextOuraClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextOuraClientCall) Return(arg0 oura.Client) *MockContextOuraClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextOuraClientCall) Do(f func() oura.Client) *MockContextOuraClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextOuraClientCall) DoAndReturn(f func() oura.Client) *MockContextOuraClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PermissionClient mocks base method.
func (m *MockContext) PermissionClient() permission.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionClient")
	ret0, _ := ret[0].(permission.Client)
	return ret0
}

// PermissionClient indicates an expected call of PermissionClient.
func (mr *MockContextMockRecorder) PermissionClient() *MockContextPermissionClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionClient", reflect.TypeOf((*MockContext)(nil).PermissionClient))
	return &MockContextPermissionClientCall{Call: call}
}

// MockContextPermissionClientCall wrap *gomock.Call
type MockContextPermissionClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextPermissionClientCall) Return(arg0 permission.Client) *MockContextPermissionClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextPermissionClientCall) Do(f func() permission.Client) *MockContextPermissionClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextPermissionClientCall) DoAndReturn(f func() permission.Client) *MockContextPermissionClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Request mocks base method.
func (m *MockContext) Request() *rest.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request")
	ret0, _ := ret[0].(*rest.Request)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockContextMockRecorder) Request() *MockContextRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockContext)(nil).Request))
	return &MockContextRequestCall{Call: call}
}

// MockContextRequestCall wrap *gomock.Call
type MockContextRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextRequestCall) Return(arg0 *rest.Request) *MockContextRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextRequestCall) Do(f func() *rest.Request) *MockContextRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextRequestCall) DoAndReturn(f func() *rest.Request) *MockContextRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RespondWithError mocks base method.
func (m *MockContext) RespondWithError(err *service0.Error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RespondWithError", err)
}

// RespondWithError indicates an expected call of RespondWithError.
func (mr *MockContextMockRecorder) RespondWithError(err any) *MockContextRespondWithErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondWithError", reflect.TypeOf((*MockContext)(nil).RespondWithError), err)
	return &MockContextRespondWithErrorCall{Call: call}
}

// MockContextRespondWithErrorCall wrap *gomock.Call
type MockContextRespondWithErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextRespondWithErrorCall) Return() *MockContextRespondWithErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextRespondWithErrorCall) Do(f func(*service0.Error)) *MockContextRespondWithErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextRespondWithErrorCall) DoAndReturn(f func(*service0.Error)) *MockContextRespondWithErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RespondWithInternalServerFailure mocks base method.
func (m *MockContext) RespondWithInternalServerFailure(message string, failure ...any) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range failure {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RespondWithInternalServerFailure", varargs...)
}

// RespondWithInternalServerFailure indicates an expected call of RespondWithInternalServerFailure.
func (mr *MockContextMockRecorder) RespondWithInternalServerFailure(message any, failure ...any) *MockContextRespondWithInternalServerFailureCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, failure...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondWithInternalServerFailure", reflect.TypeOf((*MockContext)(nil).RespondWithInternalServerFailure), varargs...)
	return &MockContextRespondWithInternalServerFailureCall{Call: call}
}

// MockContextRespondWithInternalServerFailureCall wrap *gomock.Call
type MockContextRespondWithInternalServerFailureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextRespondWithInternalServerFailureCall) Return() *MockContextRespondWithInternalServerFailureCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextRespondWithInternalServerFailureCall) Do(f func(string, ...any)) *MockContextRespondWithInternalServerFailureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextRespondWithInternalServerFailureCall) DoAndReturn(f func(string, ...any)) *MockContextRespondWithInternalServerFailureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RespondWithStatusAndData mocks base method.
func (m *MockContext) RespondWithStatusAndData(statusCode int, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RespondWithStatusAndData", statusCode, data)
}

// RespondWithStatusAndData indicates an expected call of RespondWithStatusAndData.
func (mr *MockContextMockRecorder) RespondWithStatusAndData(statusCode, data any) *MockContextRespondWithStatusAndDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondWithStatusAndData", reflect.TypeOf((*MockContext)(nil).RespondWithStatusAndData), statusCode, data)
	return &MockContextRespondWithStatusAndDataCall{Call: call}
}

// MockContextRespondWithStatusAndDataCall wrap *gomock.Call
type MockContextRespondWithStatusAndDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextRespondWithStatusAndDataCall) Return() *MockContextRespondWithStatusAndDataCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextRespondWithStatusAndDataCall) Do(f func(int, any)) *MockContextRespondWithStatusAndDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextRespondWithStatusAndDataCall) DoAndReturn(f func(int, any)) *MockContextRespondWithStatusAndDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RespondWithStatusAndErrors mocks base method.
func (m *MockContext) RespondWithStatusAndErrors(statusCode int, errors []*service0.Error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RespondWithStatusAndErrors", statusCode, errors)
}

// RespondWithStatusAndErrors indicates an expected call of RespondWithStatusAndErrors.
func (mr *MockContextMockRecorder) RespondWithStatusAndErrors(statusCode, errors any) *MockContextRespondWithStatusAndErrorsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondWithStatusAndErrors", reflect.TypeOf((*MockContext)(nil).RespondWithStatusAndErrors), statusCode, errors)
	return &MockContextRespondWithStatusAndErrorsCall{Call: call}
}

// MockContextRespondWithStatusAndErrorsCall wrap *gomock.Call
type MockContextRespondWithStatusAndErrorsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextRespondWithStatusAndErrorsCall) Return() *MockContextRespondWithStatusAndErrorsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextRespondWithStatusAndErrorsCall) Do(f func(int, []*service0.Error)) *MockContextRespondWithStatusAndErrorsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextRespondWithStatusAndErrorsCall) DoAndReturn(f func(int, []*service0.Error)) *MockContextRespondWithStatusAndErrorsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Response mocks base method.
func (m *MockContext) Response() rest.ResponseWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response")
	ret0, _ := ret[0].(rest.ResponseWriter)
	return ret0
}

// Response indicates an expected call of Response.
func (mr *MockContextMockRecorder) Response() *MockContextResponseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockContext)(nil).Response))
	return &MockContextResponseCall{Call: call}
}

// MockContextResponseCall wrap *gomock.Call
type MockContextResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextResponseCall) Return(arg0 rest.ResponseWriter) *MockContextResponseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextResponseCall) Do(f func() rest.ResponseWriter) *MockContextResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextResponseCall) DoAndReturn(f func() rest.ResponseWriter) *MockContextResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SummarizerRegistry mocks base method.
func (m *MockContext) SummarizerRegistry() *summary.SummarizerRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummarizerRegistry")
	ret0, _ := ret[0].(*summary.SummarizerRegistry)
	return ret0
}

// SummarizerRegistry indicates an expected call of SummarizerRegistry.
func (mr *MockContextMockRecorder) SummarizerRegistry() *MockContextSummarizerRegistryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummarizerRegistry", reflect.TypeOf((*MockContext)(nil).SummarizerRegistry))
	return &MockContextSummarizerRegistryCall{Call: call}
}

// MockContextSummarizerRegistryCall wrap *gomock.Call
type MockContextSummarizerRegistryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextSummarizerRegistryCall) Return(arg0 *summary.SummarizerRegistry) *MockContextSummarizerRegistryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextSummarizerRegistryCall) Do(f func() *summary.SummarizerRegistry) *MockContextSummarizerRegistryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextSummarizerRegistryCall) DoAndReturn(f func() *summary.SummarizerRegistry) *MockContextSummarizerRegistryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SummaryReporter mocks base method.
func (m *MockContext) SummaryReporter() *reporters.PatientRealtimeDaysReporter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryReporter")
	ret0, _ := ret[0].(*reporters.PatientRealtimeDaysReporter)
	return ret0
}

// SummaryReporter indicates an expected call of SummaryReporter.
func (mr *MockContextMockRecorder) SummaryReporter() *MockContextSummaryReporterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryReporter", reflect.TypeOf((*MockContext)(nil).SummaryReporter))
	return &MockContextSummaryReporterCall{Call: call}
}

// MockContextSummaryReporterCall wrap *gomock.Call
type MockContextSummaryReporterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextSummaryReporterCall) Return(arg0 *reporters.PatientRealtimeDaysReporter) *MockContextSummaryReporterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextSummaryReporterCall) Do(f func() *reporters.PatientRealtimeDaysReporter) *MockContextSummaryReporterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextSummaryReporterCall) DoAndReturn(f func() *reporters.PatientRealtimeDaysReporter) *MockContextSummaryReporterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SummaryRepository mocks base method.
func (m *MockContext) SummaryRepository() store.SummaryRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryRepository")
	ret0, _ := ret[0].(store.SummaryRepository)
	return ret0
}

// SummaryRepository indicates an expected call of SummaryRepository.
func (mr *MockContextMockRecorder) SummaryRepository() *MockContextSummaryRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryRepository", reflect.TypeOf((*MockContext)(nil).SummaryRepository))
	return &MockContextSummaryRepositoryCall{Call: call}
}

// MockContextSummaryRepositoryCall wrap *gomock.Call
type MockContextSummaryRepositoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextSummaryRepositoryCall) Return(arg0 store.SummaryRepository) *MockContextSummaryRepositoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextSummaryRepositoryCall) Do(f func() store.SummaryRepository) *MockContextSummaryRepositoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextSummaryRepositoryCall) DoAndReturn(f func() store.SummaryRepository) *MockContextSummaryRepositoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SyncTaskRepository mocks base method.
func (m *MockContext) SyncTaskRepository() store0.SyncTaskRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncTaskRepository")
	ret0, _ := ret[0].(store0.SyncTaskRepository)
	return ret0
}

// SyncTaskRepository indicates an expected call of SyncTaskRepository.
func (mr *MockContextMockRecorder) SyncTaskRepository() *MockContextSyncTaskRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncTaskRepository", reflect.TypeOf((*MockContext)(nil).SyncTaskRepository))
	return &MockContextSyncTaskRepositoryCall{Call: call}
}

// MockContextSyncTaskRepositoryCall wrap *gomock.Call
type MockContextSyncTaskRepositoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextSyncTaskRepositoryCall) Return(arg0 store0.SyncTaskRepository) *MockContextSyncTaskRepositoryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextSyncTaskRepositoryCall) Do(f func() store0.SyncTaskRepository) *MockContextSyncTaskRepositoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextSyncTaskRepositoryCall) DoAndReturn(f func() store0.SyncTaskRepository) *MockContextSyncTaskRepositoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TwiistServiceAccountAuthorizer mocks base method.
func (m *MockContext) TwiistServiceAccountAuthorizer() auth.ServiceAccountAuthorizer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TwiistServiceAccountAuthorizer")
	ret0, _ := ret[0].(auth.ServiceAccountAuthorizer)
	return ret0
}

// TwiistServiceAccountAuthorizer indicates an expected call of TwiistServiceAccountAuthorizer.
func (mr *MockContextMockRecorder) TwiistServiceAccountAuthorizer() *MockContextTwiistServiceAccountAuthorizerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TwiistServiceAccountAuthorizer", reflect.TypeOf((*MockContext)(nil).TwiistServiceAccountAuthorizer))
	return &MockContextTwiistServiceAccountAuthorizerCall{Call: call}
}

// MockContextTwiistServiceAccountAuthorizerCall wrap *gomock.Call
type MockContextTwiistServiceAccountAuthorizerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextTwiistServiceAccountAuthorizerCall) Return(arg0 auth.ServiceAccountAuthorizer) *MockContextTwiistServiceAccountAuthorizerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextTwiistServiceAccountAuthorizerCall) Do(f func() auth.ServiceAccountAuthorizer) *MockContextTwiistServiceAccountAuthorizerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextTwiistServiceAccountAuthorizerCall) DoAndReturn(f func() auth.ServiceAccountAuthorizer) *MockContextTwiistServiceAccountAuthorizerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WorkClient mocks base method.
func (m *MockContext) WorkClient() work.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkClient")
	ret0, _ := ret[0].(work.Client)
	return ret0
}

// WorkClient indicates an expected call of WorkClient.
func (mr *MockContextMockRecorder) WorkClient() *MockContextWorkClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkClient", reflect.TypeOf((*MockContext)(nil).WorkClient))
	return &MockContextWorkClientCall{Call: call}
}

// MockContextWorkClientCall wrap *gomock.Call
type MockContextWorkClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContextWorkClientCall) Return(arg0 work.Client) *MockContextWorkClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContextWorkClientCall) Do(f func() work.Client) *MockContextWorkClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContextWorkClientCall) DoAndReturn(f func() work.Client) *MockContextWorkClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
